### ISSUE TITLE
Cultura UX(User eXperience) na ESP

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/DesignLab#1]
Referências:
- Mapa Estratégico da ESP: https://prezi.com/view/5IDYo9te42mDRsPSEZMz/
-

**Comment by rodrigopeixotoespce** [comment]
- [ ] Criar uma nova interface do mapa estratégico

**Comment by drmarcos** [comment]
Transferida para o Trello: https://trello.com/b/PG4dwn3N/designlab
