### ISSUE TITLE
Apreciação do Conselho Editorial da ESP

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#125]
## **Objetivo**

**Como** designer  
**Quero** solicitar apreciação do Conselho Editorial da ESP
**Para** validação do Artefato Impresso e apoio na geração de ISSN e Ficha Catalográfica

## **Contexto**

Após reunião do Grupo Tático 27/09/2021, ficou acordado que a versão definitiva do Artefato Impresso passará pela apreciação do Conselho Editorial da ESP. Dispondo também de ISSN e Ficha Catalográfica. A Maria do Carmo (Carminha) foi citada como pessoa de referência para o trâmite.

## **Escopo**
- [x] Fazer solicitação formal da apreciação do Conselho Editorial
- [x] Fazer ajustes necessários e inserção do ISBN e Ficha Catalográfica

## Observações
https://www.figma.com/file/Avf3SQNDfeglilqOoXXVEY/Agenda-de-Prioridades-2021-2022-SEPOS?node-id=0%3A1

**Comment by pauloamoreira** [comment]
.em resposta ao email enviado para o conselho editorial no dia 29 de setembro, as 12h37, o conselho nos orientou a solicitar por email a ficha catalográfica e o ISBN para as duas versões (impressa e digital). somente os ISBN demandam custos adicionais (R$ 20,00 cada). para fazer essa solicitação, no entanto, se faz necessário finalizar o arquivo, posto que nenhuma alteração será possível após a emissão dos referidos itens. tão logo tenhamos a aprovação final do artefato (#94), iremos encaminhar o arquivo final para o conselho.
