### ISSUE TITLE
Reestruturação dos Cursos das Residências Multiprofissional e Uniprofissional - Turma 07

### ISSUE THREAD

**Issue by rodrigoplimafreire** [EscolaDeSaudePublica/DesignLab#14]
# Objetivo
**Eu como** 
**Quero** 
**Para que** 

# Contexto
Esta é uma demanda emergência de uma nova estruturação dos cursos (Turma 07) das Residenciais Multiprofissional e Uniprofissional. Por ser uma estrutura complexa gostaríamos da visão do Design UX para o desenvolvimento das ideias.
Este curso iniciará início de março a estrutura é prioridade neste momento, já que o conteúdo será readequado ao longo dos 2 anos do curso.

# Definições

- [ ] Definição do trabalho

- [ ] Definição do responsável

- [ ] Prazo

- [ ] Força de trabalho para executar a tarefa

- [ ] Setor gerador da demanda

**Comment by drmarcos** [comment]
Se e somente se trata de Reestruturação de Cursos:
Não é  esta uma atribuição para o CEDES?
Um trabalho de Design Instrucional?
