### ISSUE TITLE
Identidade visual do iSUS

### ISSUE THREAD

**Issue by ClarisCaval** [EscolaDeSaudePublica/DesignLab#142]
Criar identidade visual do iSUS. Atualmente só dispomos do logotipo.
- cards e stories para as redes sociais
- iconografia
- manual de identidade visual (ou orientações para uso da marca)

**Comment by RaniGub** [comment]
@danielgula temos a previsão no futuro que todas as nossas soluções digitais sejam integradas em uma única linguagem visual regida pelo Design System e diretrizes do Manual de Identidade Visual. Isso é entendido pelo time da Gestão como uma iniciativa e o iSus já compõe o escopo.

**Comment by uira** [comment]
humm... isso aqui fiquei na dúvida. 

É a visão correta, mas ideal. Não sei se será possível/viável dessa forma.

Minha previsão é que talvez precisemos adiantar alguns produtos, antes mesmo do Design System
