### ISSUE TITLE
Fluxo das Pessoas/Bolsistas ESP - da Criação do Edital à Outorga

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#147]
## **Objetivo**

**Como** gestor  
**Quero** visualizar as possíveis jornadas de bolsistas na ESP
**Para** permitir identificar fragilidades no Fluxo e oportunidade de melhorias

## **Contexto**

Visto o processo de publicação de edital à formação e avaliação de bolsistas que integram ou virão a fazer parte das soluções da ESP, é preciso visualizar como se dá esse fluxo e identificar o que pode ser melhorado.

## **Escopo**
- [x] Realizar reunião de diagnóstico com Helen Hilário sobre a Criação de Edital, a Efetivação da Bolsa, a Contratação e a Outorga
- [x] Criar board no Figma com a Jornada correspondente a estes processos
- [x] Refinar e Validar com Helen Hilário o board no Figma desta Jornada
- [x] Sugerir aperfeiçoamentos na Jornada, quando for o caso
- [x] Compartilhar com stakeholders o board consolidado

## Observações

- esta tarefa é um desdobramento da tarefa #136 

- board do figma onde estão sendo consolidados os dados coletados:

https://www.figma.com/file/TAKeXiXL7IoBftQlswRRHg/do-Edital-à-Outorga?node-id=0%3A1

**Comment by pauloamoreira** [comment]
.reunião marcada para dia 20/10, no período da tarde, com @helenhilario, para refinar e validar a board do processo da Criação do Edital à Outorga, foi reagendada para 21/10, as 8h, devido a mudanças na agenda da Helen.

**Comment by RaniGub** [comment]
Pareamento realizado. @pauloamoreira vamos marcar um momento com o @uira para finalizarmos o card.

**Comment by RaniGub** [comment]
Pareamento do card #147 e #148 com Uirá dia 03/11, 10h.

**Comment by RaniGub** [comment]
Um Fluxo Geral das Jornadas dos bolsistas foi proposta, agora é necessário dispor essa representação com a visão da pessoa usuária. Essa tarefa tem relação com a #148 e #162
