### ISSUE TITLE
Identificar Jornada da Pessoa / ESP Bolsista - Onboarding

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#148]
## **Objetivo**

**Como** gestor  
**Quero** visualizar as possíveis jornadas de bolsistas na ESP
**Para** permitir identificar fragilidades no Fluxo e oportunidade de melhorias

## **Contexto**

Visto o processo de publicação de edital à formação e avaliação de bolsistas que integram ou virão a fazer parte das soluções da ESP, é preciso visualizar como se dá esse fluxo e identificar o que pode ser melhorado.

## **Escopo**
- [x] Reunião com Mayara Monte sobre o processo de Integração do Bolsista/Onboarding
- [x] Jornada de avaliação/qualificação
- [x] Criação de board no Figma com a Jornada da Pessoa / ESP Bolsista/Onboarding
- [x] Refinar e Validar com Mayara Monte board do Figma com esta Jornada
- [x] Sugerir aperfeiçoamentos na Jornada, quando for o caso
- [ ] Compartilhar com os stakeholders o board consolidado

## Observações

- esta tarefa é um desdobramento da tarefa #136 

- board do figma onde estão sendo consolidados os dados coletados:

https://www.figma.com/file/TAKeXiXL7IoBftQlswRRHg/do-Edital-à-Outorga?node-id=0%3A1

**Comment by pauloamoreira** [comment]
.reunião marcada para dia 20/10, no período da manhã, com @MayaraMonte , para refinar e validar a board do processo de onbording, foi reagendada para 21/10, as 11h, devido a mudanças na agenda da Mayara.

**Comment by RaniGub** [comment]
@pauloamoreira embora tenhamos conversado ontem sobre fragilidades de avaliação/qualificação, acho importante ela estar presente no Escopo, adicionei aqui.

**Comment by RaniGub** [comment]
Pareamento realizado. @pauloamoreira vamos marcar um momento com o @uira para finalizarmos o card.
