### ISSUE TITLE
Desenvolvimento de Declaração de Participação em Oficina de Design de Serviços

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#149]
## **Objetivo**

**Como** colaborador na realização da Oficina de Design de Serviços   
**Quero** descobrir qual o trâmite a seguir para obter da Escola de Saúde Pública do Ceará uma declaração de participação na Oficina de Design de Serviços.
**Para** comprovar a participação nessa atividade essa atividade, para fins de currículo do participante.

## **Contexto**

- Diversas pessoas colaboraram e colaboram com as Oficinas de Design de Serviço, em diferentes funções. Com a finalização de cada momento formativo, é necessário gerar um documento comprobatório oficial da ESP que assinale essa colaboração, indicando os dados da oficina, qual a carga horária, qual o período de realização, e qual função foi exercida.

## **Escopo**

- [ ] Criar texto padrão de participação na Oficina
- [ ] Validar o template com Diretoria de Inovação
- [ ] Encaminhar para Nicholas modelos com todos os nomes para aplicação de timbre, impressão e assinatura das Declarações
- [ ] Informar participantes sobre a disponibilidade das declarações (Nicholas via grupo do Telegram?)

## Observações
O texto padrão da declaração poderá ser visualizado nesse campo.

**Comment by pauloamoreira** [comment]
@uira e @RaniGub segue, para aprovação, link para pasta com dois modelos de declaração para as pessoas que colaboraram na oficina. um para os facilitadores e outro para os participantes: https://drive.google.com/drive/folders/1_tN3FeKlxEJWvgmBV2Eaik5HW7Nyv1UC?usp=sharing

**Comment by RaniGub** [comment]
Em conversa com o Nicolas, essa tarefa já está em tramitação na Board do Adm e com os indicativos necessários. Será encerrada.
