### ISSUE TITLE
Estruturar fluxo experimental para solicitação de demandas de Design ao DIT/ESP-CE

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#151]
## **Objetivo**

**Como** pessoa usuária  
**Quero** solicitar demandas de Design para o DIT/ESP-CE
**Para** atender uma determinada necessidade de Design

## **Contexto**

Considerando o crescente índice de solicitação de demandas de Design ao DIT/ESP-CE, é preciso que seja estabelecido um fluxo para tais ações. 

Stakeholder: Washington

## **Escopo**
- [ ] 1. Estruturar fluxo experimental

## Observações
https://www.figma.com/file/QWDbpo9c4eXZfYRKpoW7dg/Fluxo-para-solicitação-de-demanda-DIT?node-id=0%3A1

**Comment by gabrieladamarques** [comment]
Em dezembro houve uma reunião (liderada pelo Washington, com participação da Camila, Rafael e Gabriela) com o objetivo de fazer um mapeamento inicial dos canais de entrada e das ferramentas utilizadas para gerenciar as demandas. Este mapeamento serviria para orientar o desenho do fluxo ideal, que não foi iniciado. De qualquer forma, pode servir de apoio para a tarefa desta issue: https://www.figma.com/file/CHLQayMR4v4uAeX80VQbKu/Fluxo-de-demandas?node-id=0%3A1

**Comment by RaniGub** [comment]
> Em dezembro houve uma reunião (liderada pelo Washington, com participação da Camila, Rafael e Gabriela) com o objetivo de fazer um mapeamento inicial dos canais de entrada e das ferramentas utilizadas para gerenciar as demandas. Este mapeamento serviria para orientar o desenho do fluxo ideal, que não foi iniciado. De qualquer forma, pode servir de apoio para a tarefa desta issue: https://www.figma.com/file/CHLQayMR4v4uAeX80VQbKu/Fluxo-de-demandas?node-id=0%3A1

Obg Gabi, vou analisar amanhã.
