### ISSUE TITLE
Apoiar a revisão de Arquitetura do Site Felicilab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#153]
## **Objetivo**

**Como** designer
**Quero** realizar revisões no fluxo de desenvolvimento do site do Felicilab
**Para** colaborar com o lançamento

## **Contexto**
Frente ao lançamento do site do Felicilab, foi solicitado que o DesignLab contribua com o fluxo de desenvolvimento.

## **Escopo**

- [ ] Revisar Arquitetura da Informação (Card # 109 da Central de Informações

##**Observações**
Arquiterura de Informação (em desenvolvimento): https://www.figma.com/file/28muBE8lqbjLtlLSPREFAQ/Arquitetura-da-Informa%C3%A7%C3%A3o?node-id=0%3A1

Proposta refinada com Jornada das pessoas:
https://www.figma.com/file/ahyV3xaWLuEpkxl7UmMjZy/Jornada-das-Pessoas-Usu%C3%A1rias-do-Site-Felicilab

**Comment by RaniGub** [comment]
@danielgula você pode postar aqui o link da Inception e da Arquitetura do Site do Felicilab? Vou precisar atender outras demandas e alinhar com o @pauloamoreira amanhã para lhe apoiar nesse sentido.

**Comment by RaniGub** [comment]
@danielgula foi adicionada a dependência #156 para que a Arquitetura possa ser reavaliada. @pauloamoreira por gentileza, compartilhe o link da Arquitetura no escopo da tarefa.

**Comment by RaniGub** [comment]
Em conversa com @Clarisse1983 e @uira, entendemos que deve ser rodada uma Inception para estruturar melhor a Arquitetura do Site do Felicilab nesse novo contexto. No entanto, é preciso estabelecer uma versão emergencial com conteúdo mínimo para os visitantes após a premiação do concurso de inovação (com base na proposta pelo Washington). Em conversa com Clarisse, @pauloamoreira e @danielgula , definimos que, pelo menos, as pessoas usuárias devam ter informações sobre nossos produtos e uma opção de contato. Definimos também que o após a Inception, o aprimoramento do Site do Felicilab deve ser permanente dentro do cronograma dos envolvidos.

**Comment by RaniGub** [comment]
Deve ser incluído no escopo do Projeto de Estruturação do Felicilab para 2022.

**Comment by uira** [comment]
Aproveitar esforço e incluir o site do felicilab no **Projeto de Reestruturação do Site da ESP**

**Comment by RaniGub** [comment]
Tarefa irá tramitar na Board da Central de Informações.

**Comment by RaniGub** [comment]
Essa tarefa será finalizada e um épico do site do Felicilab será criado no repo do Design. Jorge será a pessoa de referência dessa tarefa com o apoio do time de narrativas.
