### ISSUE TITLE
Jornada da Inscrição de Avaliadores

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#158]
## **Objetivo**

**Como** designer
**Quero** criar jornadas de usabilidade no Mapa da Saúde
**Para** contribuir na construção de uma melhor experiência

## **Contexto**
É preciso realizar o fluxo com as principais Jornadas do Mapa da Saúde. Dessa forma será possível realizar testes de usabilidade para identificar gaps na experiência da pessoa usuária e gerar relatórios de sugestões de melhorias.

## **Escopo**

- [x] 1.2.1 Inscrição de Avaliadores

## **Outras Informações**
![photo5174706048991341018](https://user-images.githubusercontent.com/79097920/139433989-b04eebef-0cdd-4968-98c9-34c63ea4b5ab.jpg)

Link do Figma
Figma original: https://www.figma.com/file/MhezZ6o7vmGeqXK6rfL6ts/Jornadas-para-Testes-do-Mapa?node-id=0%3A1
Figma pareado: https://www.figma.com/file/OXtovMznpqqMSOW1Ut0KJV/Pr%C3%AAmio-Munic%C3%ADpio-Inovador---Jornada-de-Ades%C3%A3o-do-Munic%C3%ADpio-e-Inscri%C3%A7%C3%A3o-da-Iniciativa?node-id=0%3A1

**Comment by pauloamoreira** [comment]
.tarefa finalizada. board atualizado.

**Comment by RaniGub** [comment]
@pauloamoreira @danielgula estava olhando a Jornada e não consegui identificar com clareza onde a inscrição dos avaliares se encaixa nela. Fiz alguns acréscimos. Mas precisamos ver essa jornada.

**Comment by RaniGub** [comment]
Um Fluxo Geral das Jornadas dos bolsistas foi proposta, agora é necessário dispor essa representação com a visão da pessoa usuária.

**Comment by RaniGub** [comment]
Último comentário apagado.
Atualização:
Ainda não foi disponibilizada a Jornada de Avaliadores.

**Comment by pauloamoreira** [comment]
.em 18/01/2022 estava agendada reunião de pareamento sobre esta tarefa e a tarefa #159 com @danielgula , que não pode participar por se encontrar adoentado. iremos agendar novo dia e horário para darmos prosseguimento.
