### ISSUE TITLE
Jornada de Inscrição de Iniciativa

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#159]
## **Objetivo**

**Como** designer
**Quero** criar jornadas de usabilidade no Mapa da Saúde
**Para** contribuir na construção de uma melhor experiência

## **Contexto**
É preciso realizar o fluxo com as principais Jornadas do Mapa da Saúde. Dessa forma será possível realizar testes de usabilidade para identificar gaps na experiência da pessoa usuária e gerar relatórios de sugestões de melhorias.

## **Escopo**

- [x] 1.2.2 Inscrição de Iniciativa

## **Outras Informações**
![photo5174706048991341019](https://user-images.githubusercontent.com/79097920/139434377-0be54687-d406-4611-8a26-9d1caee67e3c.jpg)

Link do Figma
https://www.figma.com/file/OXtovMznpqqMSOW1Ut0KJV/Pr%C3%AAmio-Munic%C3%ADpio-Inovador---Jornada-de-Ades%C3%A3o-do-Munic%C3%ADpio-e-Inscri%C3%A7%C3%A3o-da-Iniciativa?node-id=0%3A1

**Comment by pauloamoreira** [comment]
.tarefa finalizada. board atualizado.

**Comment by RaniGub** [comment]
Link do escopo atualizado, sincronizando com épico #155

**Comment by pauloamoreira** [comment]
.em 18/01/2022 estava agendada reunião de pareamento sobre esta tarefa e a tarefa #158 com @danielgula , que não pode participar por se encontrar adoentado. iremos agendar novo dia e horário para darmos prosseguimento.
