### ISSUE TITLE
Reanálise dos modelos de cursos híbridos realizados pela ESP

### ISSUE THREAD

**Issue by rodrigoplimafreire** [EscolaDeSaudePublica/DesignLab#16]
# Objetivo
**Eu como** 
**Quero** 
**Para que** 

# Contexto

# Definições

- [ ] 

# Observações

-

**Comment by drmarcos** [comment]
Se e somente se trata de modelos de cursos: 
Não é  esta uma atribuição para o CEDES? 
Um trabalho de Design Instrucional?
