### ISSUE TITLE
Jornada Adesão do Município

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#160]
## **Objetivo**

**Como** designer
**Quero** criar jornadas de usabilidade no Mapa da Saúde
**Para** contribuir na construção de uma melhor experiência

## **Contexto**
É preciso realizar o fluxo com as principais Jornadas do Mapa da Saúde. Dessa forma será possível realizar testes de usabilidade para identificar gaps na experiência da pessoa usuária e gerar relatórios de sugestões de melhorias.

## **Escopo**

- [x] 1.2.3 Adesão do Município

## **Outras Informações**
![photo5174706048991341020](https://user-images.githubusercontent.com/79097920/139434423-b2eca43c-992e-4180-8e60-bbef522e6468.jpg)

Link do Figma
Proposta Original:
https://www.figma.com/file/MhezZ6o7vmGeqXK6rfL6ts/Jornadas-para-Testes-do-Mapa?node-id=0%3A1

Proposta atual do site:
https://www.figma.com/file/OXtovMznpqqMSOW1Ut0KJV/Jornada-do-usu%C3%A1rio---Ades%C3%A3o-do-Munic%C3%ADpio?node-id=0%3A1

**Comment by RaniGub** [comment]
@pauloamoreira tarefa #158 #159 e #160 são as Jornadas que lhe falei. Compartilham da mesma board no Figma.

**Comment by pauloamoreira** [comment]
.tarefa concluída. board atualizado.

**Comment by RaniGub** [comment]
@pauloamoreira realizou pareamento com Daniel e algumas fragilidades foram mapeadas na jornada. Sugeri que as duas jornadas desenhadas (uma pelo Paulo e outra pelo @danielgula) sejam analisadas e convirjam em uma só. 

Embora a jornada em si não seja traduzida integralmente no infográfico, devem ser definidos pontos-chave para norteamento da adesão. Quais  [pontos] servirão de apoio para que a pessoa usuária deduza os caminhos que não estão sendo apresentados no infográfico?

Ação-Caminho dedutivo-Ação-Caminho dedutivo...

**Comment by pauloamoreira** [comment]
.a partir da orientação do @RaniGub, elaborei uma nova Jornada, sinalizando as fragilidades mapeadas durante o pareamento com @danielgula . esta terceira Jornada pode ser visualizada em: https://www.figma.com/file/OXtovMznpqqMSOW1Ut0KJV/Jornada-do-usu%C3%A1rio---Ades%C3%A3o-do-Munic%C3%ADpio?node-id=0%3A1

**Comment by pauloamoreira** [comment]
> .a partir da orientação do @RaniGub, elaborei uma nova Jornada, sinalizando as fragilidades mapeadas durante o pareamento com @danielgula . esta terceira Jornada pode ser visualizada em: https://www.figma.com/file/OXtovMznpqqMSOW1Ut0KJV/Jornada-do-usu%C3%A1rio---Ades%C3%A3o-do-Munic%C3%ADpio?node-id=0%3A1

@thaistoscano essa é a jornada que citei na reunião de hoje à tarde (05/11), para que você possa avaliar se alguma das fragilidades apontadas serão analisadas ou tratadas nas próximas sprints.
