### ISSUE TITLE
Definir documento de mapeamento de demandas com áreas

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#164]
## **Objetivo**

**Como** gestor  
**Quero** desenvolver o Projeto da Oficina de Design de Serviços Públicos
**Para** ser aplicada às áreas da ESP

## **Contexto**

Em razão da realização do épico #152, é necessário "Consolidar Formato da II Oficina de Design de Serviços Públicos".

## **Escopo**
- [x] 1.3.1 Definir documento de mapeamento de demandas com áreas

## Observações
Stakeholders: Uirá e Alice
https://docs.google.com/document/d/1FgwmraIdH4e_r3sjjrVOrtYn0TGhm7dBZo-VbQoy9UU/edit?usp=sharing

**Comment by RaniGub** [comment]
Documento compartilhado no grupo da Oficina para troca de ideias e revisão de texto.

**Comment by RaniGub** [comment]
@clarissagpeixoto quando você tiver um tempo é possível revisar esse texto também?

**Comment by RaniGub** [comment]
Documento concluído, necessita de revisão de @Clarisse1983 e aprovação do Uirá ou Alice.
