### ISSUE TITLE
Cobertura | 25º Prêmio de Inovação Enap

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#165]
## **Objetivo**

**Como** fotógrafo  
**Quero** realizar a cobertura do evento
**Para** dispor no acervo fotográfico

## **Contexto**

No evento de premiação do 25º Prêmio de Inovação Enap, foi solicitado apoio do DesignLab para reforçar a cobertura de fotografia.

## **Escopo**
- [x] Realizar fotografias
- [x] Tratar imagens
- [x] Dispor no acerto e divulgar link

**Comment by pauloamoreira** [comment]
.criei uma pasta no drive do publicilab onde serão compartilhadas, na medida em que forem tratadas, fotos produzidas por mim no evento: https://drive.google.com/drive/folders/1nF7xzNyQT6LKq6RV9psMI9_p-KFbkW5P?usp=sharing
