### ISSUE TITLE
Apoiar a Inception do Site da Residência

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#166]
## **Objetivo**

**Como** designer  
**Quero** participar da realização da Inception do Site da Residência em Saúde
**Para** direcionar o escopo do Site

## **Contexto**
Foi necessário voltar etapas no desenvolvimento do site da Residência para que houvesse clareza do caminho a ser perseguido.

## **Escopo**
- [x] Participar da Inception com stakeholders (16/11)
- [x] Participar da Inception com stakeholders (18/11)

**Comment by RaniGub** [comment]
Olá @raiannyqz , após Inception da Residência você pode seguir o modelo que vou copiar abaixo para consolidação. Quando você chegar novamente na etapa de AI (considerando que o Brainstorming já foi realizado) você aproxima o @pauloamoreira  novamente para refinamento da AI.

VISÃO GERAL
A JORNADA DA PRESCRIÇÃO A DISPENSAÇÃO DE MEDICAMENTOS é estratégia de acompanhamento da prescrição à dispenção de medicamentos, com foco na pessoa usuária, gestores e trabalhadores da saúde. Esta Jornada, entrega orientações aos cidadãos a cerca da possibilidade de dispensão do medicamento prescrito no SUS-CE.

É importante destacar que a JORNADA DA PRESCRIÇÃO A DISPENÇÃO DE MEDICAMENTOS, é diferente da Relação Estadual de Medicamentos (RESME), do Guia de Estruturação e Organização da Assistência Farmacêutica, de Cartilhas Educativas e do Site da SESA. Não é uma garantia de tratamento da condição de saúde da Pessoa Usuária, nem garantia de acesso ao medicamento pelo SUS-CE. A Jornada também não realiza Atendimento Virtual, Marcação de Exames nem Marcação de Consulta.

A Jornada, por outro lado, é uma regra de negócio, estabelecendo uma estratégia que possibilita o direcionamento de acesso ao Serviço; colabora na redução de judicialização, racioliza o processo de prescrição e uso de medicamentos, e otimiza o percurso da pessoa usuária no SUS-CE. Esta Jornada promove a integração entre os entes gestores, norteando-os nos processos de trabalho e também promove a integração entre os Bancos de Estoque Municipais e Estaduais.

OBJETIVOS

A JORNADA DA PRESCRIÇÃO A DISPENÇÃO DE MEDICAMENTOS é composta pelos seguintes objetivos:
1 - Promover a Satisfação do Usuário;
2 - Promover a Integração dos Profissionais e dos entes gestores;
3 - Ampliar a transparência das Ações do SUS
4 - Propiciar acessibilidade às informações dos instrumentos existentes;
5 - Fomentar o sentimento de inclusão aos serviços de assistência farmacêutica ofertadas pelo SUS-CE.        

PERSONA 1 - Médica
Carla, tem 38 anos, é médica em Juazeiro do Norte. Graduada em Medicina e profissional de Saúde Responsável pela prescrição de medicamentos. Entre suas necessidades que podem ser atendidas pela Jornada, estão: saber se o medicamento existe no SUS-CE, saber se o medicamento está com estoque regular, saber para qual serviço encaminhar a pessoa usuária.

PERSONA 2 - Secretário Municipal de Saúde
Uirá tem 30 anos, é Secretário Municipal de Saúde de Quixeramobim. É graduado em marketing e quer soluções inovadoras para acesso a medicamentos em seus município pelo SUS-CE. Tem necessidade de acessar informações em canais de transparência; de visualizar os medicamentos por nível de atenção que estejam disponíveis nos estabelecimentos em seu município.

PERSONA 3 - Diarista
Fernanda tem 50 anos, é diarista em Fortaleza, onde trabalha de segunda à sábado, no horário comercial. Finalizou seus estudos até o Ensino Fundamental. Tem necessidade de saber onde ela pode encontrar o remédio que foi prescrito; saber quais documentos são necessários apresentar para conseguir o remédio prescrito; saber como usar e como armazenar o medicamento e saber qual a validade da receita para retirada do medicamento.

**Comment by RaniGub** [comment]
> Olá @raiannyqz , após Inception da Residência você pode seguir o modelo que vou copiar abaixo para consolidação. Quando você chegar novamente na etapa de AI (considerando que o Brainstorming já foi realizado) você aproxima o @pauloamoreira novamente para refinamento da AI.
> 
> VISÃO GERAL A JORNADA DA PRESCRIÇÃO A DISPENSAÇÃO DE MEDICAMENTOS é estratégia de acompanhamento da prescrição à dispenção de medicamentos, com foco na pessoa usuária, gestores e trabalhadores da saúde. Esta Jornada, entrega orientações aos cidadãos a cerca da possibilidade de dispensão do medicamento prescrito no SUS-CE.
> 
> É importante destacar que a JORNADA DA PRESCRIÇÃO A DISPENÇÃO DE MEDICAMENTOS, é diferente da Relação Estadual de Medicamentos (RESME), do Guia de Estruturação e Organização da Assistência Farmacêutica, de Cartilhas Educativas e do Site da SESA. Não é uma garantia de tratamento da condição de saúde da Pessoa Usuária, nem garantia de acesso ao medicamento pelo SUS-CE. A Jornada também não realiza Atendimento Virtual, Marcação de Exames nem Marcação de Consulta.
> 
> A Jornada, por outro lado, é uma regra de negócio, estabelecendo uma estratégia que possibilita o direcionamento de acesso ao Serviço; colabora na redução de judicialização, racioliza o processo de prescrição e uso de medicamentos, e otimiza o percurso da pessoa usuária no SUS-CE. Esta Jornada promove a integração entre os entes gestores, norteando-os nos processos de trabalho e também promove a integração entre os Bancos de Estoque Municipais e Estaduais.
> 
> OBJETIVOS
> 
> A JORNADA DA PRESCRIÇÃO A DISPENÇÃO DE MEDICAMENTOS é composta pelos seguintes objetivos: 1 - Promover a Satisfação do Usuário; 2 - Promover a Integração dos Profissionais e dos entes gestores; 3 - Ampliar a transparência das Ações do SUS 4 - Propiciar acessibilidade às informações dos instrumentos existentes; 5 - Fomentar o sentimento de inclusão aos serviços de assistência farmacêutica ofertadas pelo SUS-CE.
> 
> PERSONA 1 - Médica Carla, tem 38 anos, é médica em Juazeiro do Norte. Graduada em Medicina e profissional de Saúde Responsável pela prescrição de medicamentos. Entre suas necessidades que podem ser atendidas pela Jornada, estão: saber se o medicamento existe no SUS-CE, saber se o medicamento está com estoque regular, saber para qual serviço encaminhar a pessoa usuária.
> 
> PERSONA 2 - Secretário Municipal de Saúde Uirá tem 30 anos, é Secretário Municipal de Saúde de Quixeramobim. É graduado em marketing e quer soluções inovadoras para acesso a medicamentos em seus município pelo SUS-CE. Tem necessidade de acessar informações em canais de transparência; de visualizar os medicamentos por nível de atenção que estejam disponíveis nos estabelecimentos em seu município.
> 
> PERSONA 3 - Diarista Fernanda tem 50 anos, é diarista em Fortaleza, onde trabalha de segunda à sábado, no horário comercial. Finalizou seus estudos até o Ensino Fundamental. Tem necessidade de saber onde ela pode encontrar o remédio que foi prescrito; saber quais documentos são necessários apresentar para conseguir o remédio prescrito; saber como usar e como armazenar o medicamento e saber qual a validade da receita para retirada do medicamento.

@raiannyqz

**Comment by pauloamoreira** [comment]
.participei da Inception com a DIPSA, hoje, dia 16/11, das 10h às 11h, com @raiannyqz (publicilab), bárbara e o diego (DIPSA). como a bárbara precisava participar de outra reunião, e não havíamos percorrido todo os campos da Inception, ela solicitou um novo momento na quinta, dia 18/11, as 10h, para finalizar o processo.

**Comment by raiannyqz** [comment]
> Olá @raiannyqz , após Inception da Residência você pode seguir o modelo que vou copiar abaixo para consolidação. Quando você chegar novamente na etapa de AI (considerando que o Brainstorming já foi realizado) você aproxima o @pauloamoreira novamente para refinamento da AI.
> 
> VISÃO GERAL A JORNADA DA PRESCRIÇÃO A DISPENSAÇÃO DE MEDICAMENTOS é estratégia de acompanhamento da prescrição à dispenção de medicamentos, com foco na pessoa usuária, gestores e trabalhadores da saúde. Esta Jornada, entrega orientações aos cidadãos a cerca da possibilidade de dispensão do medicamento prescrito no SUS-CE.
> 
> É importante destacar que a JORNADA DA PRESCRIÇÃO A DISPENÇÃO DE MEDICAMENTOS, é diferente da Relação Estadual de Medicamentos (RESME), do Guia de Estruturação e Organização da Assistência Farmacêutica, de Cartilhas Educativas e do Site da SESA. Não é uma garantia de tratamento da condição de saúde da Pessoa Usuária, nem garantia de acesso ao medicamento pelo SUS-CE. A Jornada também não realiza Atendimento Virtual, Marcação de Exames nem Marcação de Consulta.
> 
> A Jornada, por outro lado, é uma regra de negócio, estabelecendo uma estratégia que possibilita o direcionamento de acesso ao Serviço; colabora na redução de judicialização, racioliza o processo de prescrição e uso de medicamentos, e otimiza o percurso da pessoa usuária no SUS-CE. Esta Jornada promove a integração entre os entes gestores, norteando-os nos processos de trabalho e também promove a integração entre os Bancos de Estoque Municipais e Estaduais.
> 
> OBJETIVOS
> 
> A JORNADA DA PRESCRIÇÃO A DISPENÇÃO DE MEDICAMENTOS é composta pelos seguintes objetivos: 1 - Promover a Satisfação do Usuário; 2 - Promover a Integração dos Profissionais e dos entes gestores; 3 - Ampliar a transparência das Ações do SUS 4 - Propiciar acessibilidade às informações dos instrumentos existentes; 5 - Fomentar o sentimento de inclusão aos serviços de assistência farmacêutica ofertadas pelo SUS-CE.
> 
> PERSONA 1 - Médica Carla, tem 38 anos, é médica em Juazeiro do Norte. Graduada em Medicina e profissional de Saúde Responsável pela prescrição de medicamentos. Entre suas necessidades que podem ser atendidas pela Jornada, estão: saber se o medicamento existe no SUS-CE, saber se o medicamento está com estoque regular, saber para qual serviço encaminhar a pessoa usuária.
> 
> PERSONA 2 - Secretário Municipal de Saúde Uirá tem 30 anos, é Secretário Municipal de Saúde de Quixeramobim. É graduado em marketing e quer soluções inovadoras para acesso a medicamentos em seus município pelo SUS-CE. Tem necessidade de acessar informações em canais de transparência; de visualizar os medicamentos por nível de atenção que estejam disponíveis nos estabelecimentos em seu município.
> 
> PERSONA 3 - Diarista Fernanda tem 50 anos, é diarista em Fortaleza, onde trabalha de segunda à sábado, no horário comercial. Finalizou seus estudos até o Ensino Fundamental. Tem necessidade de saber onde ela pode encontrar o remédio que foi prescrito; saber quais documentos são necessários apresentar para conseguir o remédio prescrito; saber como usar e como armazenar o medicamento e saber qual a validade da receita para retirada do medicamento.

Entendido @RaniGub, Obrigada!

**Comment by raiannyqz** [comment]
Hoje aconteceria a inception com a DIPSA, mas houve contratempos, mudanças de horários que impossibilitou acontecer hoje. A reunião foi remarcada para segunda as 10:00hs

**Comment by RaniGub** [comment]
Tarefa concluída, aguardando o time da Central de Informações consolidar os dados para refinarmos a Board das Jornadas e AI.
