### ISSUE TITLE
Apoiar a elaboração das declarações da I Oficina de Design de Serviços

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#167]
## **Objetivo**

**Como** organizador  
**Quero** preencher a Formulário para cadastro de curso no Sagu (Matriz Curricular)
**Para** gerar a declaração aos participantes

## **Contexto**

É preciso informar a Matriz Curricular da Oficina de Design de Serviços para que o time Admin possa gerar as declarações aos participantes.

## **Escopo**
- [x] Alinhar com Helen sobre informações que constarão no selo do Mapa para emissão do certificado

## Observações
lista dos participantes e tipo de participação: https://docs.google.com/document/d/1Rci5oBCaP79_WZ-usH4lYTD53y7S9_e2lHNUs_7K8Wk/edit?usp=sharing

textos para selos: 
https://docs.google.com/document/d/1Tl1VWbllHiSkczhyCUG0-bUpZlwZiP0t7F-xJodATLI/edit?usp=sharing

**Comment by RaniGub** [comment]
Em conversa com a Helen, foi solicitado que seja criada uma oportunidade no Mapa da Saúde para que as informações dos participantes sejam coletadas. Helen informou que a solicitação já está na fila de tarefas.

**Comment by RaniGub** [comment]
@helenhilario vamos refinar quando você tiver disponibilidade ok?

**Comment by pauloamoreira** [comment]
@Clarisse1983 vamos enviar um link para os participantes da I Oficina de Design de Serviços para que acessem um cadastro no Mapa da Saúde, para sejam emitidos as declarações para participantes, facilitadores e organizadores. você pode providenciar um texto contextualizando esse email?

**Comment by ClarisCaval** [comment]
Olá, como está você? 

Temos uma boa notícia! Sua declaração de participação na 1ª Oficina de Design de Serviços Públicos, realizada nos dias 11 a 13 de agosto de 2021, está disponível no Mapa da Saúde!

Para acessá-la, será necessário responder um breve cadastro, acessível no link TAL (colocar aqui o link).

Novas oficinas ocorrerão em 2022. Fique de olho no Mapa da Saúde e tenha acesso a diversas oportunidades na área.

Atenciosamente,

**Comment by pauloamoreira** [comment]
.aguardando as últimas definições que o @RaniGub irá me passar para finalizar esta tarefa.

**Comment by RaniGub** [comment]
Os participantes, carga horária e tipo de participação de cada pessoa consta no documento do Escopo. @pauloamoreira informar para @helenhilario.

Tarefa encerrada.

Tarefa encerrada.

**Comment by RaniGub** [comment]
Essa tarefa será reaberta, falta a @helenhilario dar alguns encaminhamentos:
- Coletar assinatura do Uirá e Alice para o certificado;
- Devido o contexto dos selos, as categorias disponíveis nos formulários precisarão ser editadas com base na carga/horária. Serão 4 categorias disponíveis no arquivo do escopo;
- Explicar como se dará a validação das pessoas que se inscreverem na oportunidade. Pois até onde sabemos, qualquer pessoa com link pode fazer a inscrição mesmo sem ter participado da Oficina. É possível selecionar as pessoas que receberão a declaração manualmente após a inscrição?

**Comment by RaniGub** [comment]
Em pareamento com @helenhilario, foi informado ao @pauloamoreira que a coleta das assinaturas necessárias entrarão em sua fila de demandas. Dessa forma, o apoio do DesignLab encerra aqui. Apontamos que ainda é necessário a definição de quem enviará o e-mail para as pessoas por categoria.
