### ISSUE TITLE
Analisar o Projeto de Reestruturação de Interfaces Digitais

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#180]
## **Objetivo**

**Como** designer  
**Quero** analisar o escopo do Projeto de Reestruturação de Interfaces Digitais
**Para** dar um parecer acerca dos objetivos, força de trabalho e cronogramas

## **Contexto**

O escopo do Projeto de Reestruturação de Interfaces tem relação com o novo site da ESP e a criação do Design System da ESP.

## **Escopo**
- [x] Analisar Projeto
- [x] Propor EAP
- [x] Criar perfis de design

## Observações
EAP: https://gitmind.com/app/doc/28a7516920
Doc: https://docs.google.com/document/d/1ookvo2vaOoiR13x18lpNhVYHF52-h9UOZNEjW5UG_wA/edit#

**Comment by RaniGub** [comment]
Revisado.

**Comment by RaniGub** [comment]
Foi sugerido pelo Uirá a inserção da EAP e detalhamento dos perfis do time.

**Comment by RaniGub** [comment]
EAP inicial foi sugerida e @uira fará a validação.

**Comment by RaniGub** [comment]
Perfis dos designers adicionados, falta o time de gestão e desenvolvimento adicionar os demais.

**Comment by RaniGub** [comment]
Status de revisão pelo DesignLab: Inserida EAP, proposta mudanças no time original, inserido perfis dos profissionais, feitas mínimas adaptações textuais e no cronograma de atividades.
Necessita: Revisão pelo DevLab e validação pelo Uirá.

Tarefa encerrada.

**Comment by uira** [comment]
Finalizar e submeter esse projeto, com URGÊNCIA

**Comment by RaniGub** [comment]
@uira vamos falar sobre isso na próxima segunda? Já respondi os seus pontos, mas preciso validar o processo e perfil com o @wforte88 e @victorMagalhaesPacheco
