### ISSUE TITLE
Desenvolver Esquema Gráfico para Artigo do Felicilab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#191]
## **Objetivo**

**Como** designer
**Quero** desenvolver um Esquema Gráfico
**Para** facilitar o entendimento do fluxo de trabalho do Felicilab

## **Contexto**
Foi solicitado pelos avaliadores do artigo "O FeliciLab, a inovação disruptiva e a pandemia de Covid-19" a inserção de um Esquema Gráfico para facilitar o entendimento dos processos do Felicilab.

## **Escopo**

- [x] Alinha com Genilton
- [x] Desenvolver Esquema Gráfico

## **Outras Informações**
Artigo:
https://docs.google.com/document/d/1a2jIq3YTY_G5V40sqJgEHfMMsQfCB762/edit?rtpof=true&sd=true

Trecho do Artigo:
![Captura de Tela 2021-12-06 às 14.14.02.png](https://images.zenhubusercontent.com/6100319d73e73a075fefd717/1c1cba8d-579f-49c8-beb4-503bca3dcabf)

Referência da ilustração:
![photo4985505090265786850.jpg](https://images.zenhubusercontent.com/6100319d73e73a075fefd717/538df0f9-0f70-46db-adc8-b2a6c150c7ec)

**Comment by RaniGub** [comment]
@pauloamoreira alinhar com @geniltonfaheinajr essa semana para desenvolvimento após consolidação dos testes de usabilidade.

**Comment by pauloamoreira** [comment]
.ok, @RaniGub , já vou agendar com o @geniltonfaheinajr assim que finalizar os testes.

**Comment by pauloamoreira** [comment]
.em reunião com @geniltonfaheinajr ontem à tarde, ficou definido que irei reunir as imagens propostas (barra de alertas, hotsite corona, iSUS, e T/W) e aguardar ele me passar informações sobre a equipe multidisciplinar e sobre o fluxo de trabalho na época do artigo.

**Comment by pauloamoreira** [comment]
@geniltonfaheinajr também preciso de referências sobre a Central de Ventiladores Mecânicos e Equipamentos Respiratórios (CVMER) e o ResCovid, para avaliar o que pode ser feito para representar essas soluções.

**Comment by geniltonfaheinajr** [comment]
@pauloamoreira tudo ok com as informações?

**Comment by geniltonfaheinajr** [comment]
> @geniltonfaheinajr também preciso de referências sobre a Central de Ventiladores Mecânicos e Equipamentos Respiratórios (CVMER) e o ResCovid, para avaliar o que pode ser feito para representar essas soluções.

@pauloamoreira estão nesta pasta https://drive.google.com/drive/folders/1yUmigJym_vW5DLFJ79Z7z6HJTsaqGWTo?usp=sharing

**Comment by RaniGub** [comment]
@geniltonfaheinajr olhe o Fluxo
https://www.figma.com/file/bicnt4ngkrAF8bNJGNdIqg/Untitled?node-id=0%3A1

Ele está editável, sugiro que você alinhe com a @gabrieladamarques para saber se faz sentido e o que pode melhorar. 
![Captura de Tela 2021-12-14 às 10 15 10](https://user-images.githubusercontent.com/79097920/146005244-0e65ac41-d885-4560-b8bf-502063d7bddf.png)
