### ISSUE TITLE
Reavaliar Esquemas Gráficos de Inovação/Felicilab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#192]
## **Objetivo**

**Como** designer
**Quero** analisar os Esquemas Gráficos do Ciclo de Vida da Inovação e Processo Metodológico do Felicilab
**Para** atualizar seu conteúdo e representação

## **Contexto**
É preciso analisar os Esquemas Gráficos da apresentação, assim como propor melhorias nas representações.

## **Escopo**

- [x] Analisar conteúdo
- [X] Propor melhorias

## **Outras Informações**
https://docs.google.com/presentation/d/1yZN74_OFSqj_99aiJnEJk3VL8nrJeRSKREB8umfzU8Q/edit#slide=id.g88e545ab69_0_11

Apresentação modificada:
https://drive.google.com/file/d/1Wx4KNa-uIeQ6IUcjtQA3BxdyXAS7fR9z/view?usp=sharing

Apresentação interativa no figma:
https://www.figma.com/file/HpCrmetFZndLcqfYbsvd1j/ciclo-de-vida-da-inova%C3%A7%C3%A3o?node-id=0%3A1

Slides separados em arquivos abertos (drive)
https://drive.google.com/drive/folders/1LxVMoeWUbX4uLTdOUhjoOaUHvCMGjE5H

**Comment by caldy94** [comment]
Dei continuidade a essa tarefa e já fiz um esboço do ciclo. Esperando um feedback de @pauloamoreira 
![ciclo-inovação](https://user-images.githubusercontent.com/101121073/163865238-13d2d48d-4204-4d1f-8d26-410b3e91110d.jpg)

**Comment by pauloamoreira** [comment]
@caldy94 pode seguir no redesign dos outros 6 slides. analisaremos o conjunto assim que você terminar.

**Comment by caldy94** [comment]
Protótipo atualizado. Gostaria de um feedback do @pauloamoreira. Fiz os 5 primeiros slides em um só esquema (abaixo), os outros 2 não sei como encaixar.
![ciclo-inovação](https://user-images.githubusercontent.com/101121073/164308456-5a162e4b-f521-456b-9786-0469848509fd.jpg)

**Comment by pauloamoreira** [comment]
@caldy94 com já havia orientado, o teste dos diagramas em um único esquema gráfico deve ser feito após a conclusão dos diagramas iniciais, de modo a atender a escopo da tarefa antes de fazer experimentações fora desse escopo. o modelo mind map não atende as necessidades de uso em apresentações por ser de difícil manejo - dificultando a compreensão para leitores distantes do material. faça os diagramas seguindo a lógica formal do primeiro e só depois conclua o estudo de viabilidade de um mapa mental.

**Comment by caldy94** [comment]
Slides atualizados. Ainda não consegui encaixar os dois últimos, pois não vi sentido, mas quero  mostrar como está até agora. O link dos slides está aqui? https://drive.google.com/drive/u/0/folders/1LxVMoeWUbX4uLTdOUhjoOaUHvCMGjE5H

**Comment by RaniGub** [comment]
@pauloamoreira por gentileza, ontem a Caldy me apresentou algumas alterações e sugeri algumas coisas para ela, mas não consegui ver com atenção. Hoje pela manhã (26/04) após a daily tente ver isso com ela também.

**Comment by caldy94** [comment]
Fiz uma versão interativa no Figma: https://www.figma.com/file/HpCrmetFZndLcqfYbsvd1j/ciclo-de-vida-da-inova%C3%A7%C3%A3o?node-id=0%3A1

**Comment by caldy94** [comment]
Slides atualizados, com dois anexos finais: https://drive.google.com/file/d/1oC_1TDp6MT_wu1BZN1bYozO07faYkeID/view?usp=sharing

**Comment by caldy94** [comment]
Slides novamente atualizados, juntamente com o protótipo do figma. Esperando aprovação de @RaniGub

**Comment by RaniGub** [comment]
@caldy94 você pode me adicionar como editor ou ceder as propriedades da pasta para que eu possa mover para o drive do design?
