### ISSUE TITLE
Análise e Sistematização de Fluxo de Elaboração de Protocolos

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#193]
## **Objetivo**

**Como** Designer de Experiência
**Quero** Criar representação gráfica de Sistematização do Fluxo de Criação de Protocolos  .
**Para** Colaborar com o processo metodológico de criação de protocolos do projeto iNova Saúde.

## **Contexto**

Com o início da colaboração do Designlab no projeto iNova Saúde, o passo inicial é sistematizar o fluxo de elaboração de protocolos à partir da metodologia proposta, baseada na metodologia do projeto "Nascer no Ceará: Construção das Guias de Condutas Assistenciais para a Linha de Cuidado Materno-Infantil do Estado", dissertação de mestrado da professora Liduína Rocha. Por tanto, se faz necessário estudar a metodologia em questão e produzir o esquema correspondente, de modo a facilitar a padronização do processo de elaboração de protocolos.

## **Escopo**

- [x] Estudar a metodologia apresenta pela profa. Linduína Rocha para o trabalho no iNova Saúde
- [x] Realizar alinhamento com uirá porã para refinar o escopo da tarefa
- [x] Produzir proposta inicial de design da sistematização do fluxo 
- [x] Validar proposta final com stakeholders

## **Critérios de Aceitação**

- [x] Validação com Sheila e Liduína

**Dado que** desejo criar um protocolo de saúde 
**Quando** consulto a Sistematização do Fluxo de Elaboração de Protocolos para conhecer os passos necessários para a execução desta tarefa. 
**então** Consigo criar o Protocolo de Saúde desejado de forma proativa, seguindo os padrões estabelecidos.

## Observações
Apresentação da tese de mestrado da professora Liduína Rocha: https://docs.google.com/presentation/d/1RJwRfYFJ7YSctGLiS8YUCh7EdbOLO5sU/edit?usp=sharing&ouid=113412520935620449021&rtpof=true&sd=true

Board do Figma onde a sistematização será apresentada (em processo de construção):
https://www.figma.com/file/nrrGjg9QAQa2RnRDlQn30H/Sistematiza%C3%A7%C3%A3o-de-Fluxo-de-Elabora%C3%A7%C3%A3o-de-Protocolos?node-id=0%3A1

**Comment by RaniGub** [comment]
Solicitei um horário com a Profa. Liduína para alinhar a metodologia de elaboração, aguardando retorno.

**Comment by RaniGub** [comment]
Na reunião no dia 17/12/21 foi apresentada a v1 da metodologia híbrida para desenvolvimento das Guias. Estavam presentes a Profa. Liduína e Shiela (Educação), @gabrieladamarques (Gestão de Projetos) e eu representando o DesignLab. O feedback do fluxo proposto foi muito positivo e reforçamos que aconteça uma proposição de Arquitetura Base para os protocolos e linhas de cuidado, a fim de evitar retrabalhos na etapa de Interfaces (Construção das Guias).

Algumas sugestões foram propostas pelo @wforte88  e estão sendo adaptadas para posterior apresentação. A Gabriela irá colaborar para vislumbre inicial da EAP. Uma nova reunião foi marcada presencialmente para dia 07/01/22, às 9h30 na ESP.

**Comment by RaniGub** [comment]
Em 30/12/21, foi realizado um refinamento com a @gabrieladamarques da V1.1 do fluxo. A estruturação da EAP será norteada por ele e apresentado em seguida aos stakeholders.

**Comment by RaniGub** [comment]
Em reunião dia 07/01/22, foi apresentada a V1.1 do Fluxo de Elaboração das Guias para Sheila. Ela irá discutir com a Profa. Liduína e apresentar na reunião do grupo dia 14/01/22.

**Comment by RaniGub** [comment]
Hoje (10/01/21) @pauloamoreira foi atualizado dos acordos realizados na AI e sobre o conteúdo da reunião do dia 14/01/21. Foi sugerido que a Profa. Lidúina faça a última validação antes da apresentação.

**Comment by pauloamoreira** [comment]
.entrei em contato com a profa. liduína rocha e aguardo confirmação de disponibilidade para reunião.

**Comment by RaniGub** [comment]
Foi informado no grupo do Whatsapp do iNova que o projeto passa por readequações devido às priorizações da pandemia. Então foi sugerido pelo Uirá que as atividades relacionadas a ele sejam suspensas até que se tenha definição sobre o andamento.

**Comment by RaniGub** [comment]
Dia 18/01/2022 @pauloamoreira realizou validação do Fluxo com a Profa. Liduína. Damos a tarefa por encerrada e aguardamos as novas definições sobre o projeto iNova.
