### ISSUE TITLE
2. Apoiar a Construção da Política Estadual de Transplante (itens 2.1 a 2.3)

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#195]
## **Objetivo**

**Como** designer  
**Quero** apoiar a construção da Política Estadual de Transplante
**Para** nortear da elaboração do Plano Estadual de Doação e Transplante do Ceará (2022-2023)

## **Contexto**

A Secretaria Executiva de Políticas de Saúde - SEPOS/SESA, solicitou à Superintendência da ESP/CE, por meio do ofício 10/2022, apoio do DesignLab/Felicilab para facilitação na construção da Política Estadual de Transplante. O pedido partiu da experiência na I Oficina de Design de Serviços Públicos, realizada com a Sepos em Ago/2021. Foi definido que a Adins será a responsável pela condução do processo e o DesignLab entrará como apoio. 

## **Escopo**
- [x] 2.1. Refinar a demanda com Camila Mendes da Sepos
- [x] 2.2. Confirmar datas de realização
- [x] 2.3. Coletar informações complementares e documentos norteadores

## Observações
Épico: [Oficinas de Design para Políticas Públicas #225](https://github.com/EscolaDeSaudePublica/DesignLab/issues/225)
Stakeholder: Rosangela Cavalcante (Solicitar contato no privado) e Wilma (Adins)
Pessoa de Contato: Camila Mendes (Sepos)
![Captura de Tela 2022-02-15 às 09 18 38](https://user-images.githubusercontent.com/79097920/154060768-8c95dfd4-b8eb-4b8e-83e4-b28eb9c0d4d3.png)

**Comment by RaniGub** [comment]
Em conversa de Alice e Uirá com a Wilma da Adins, foi definido que a Adins será a responsável pela condução da Oficina, enquanto o DesignLab entrará com apoio.

**Comment by RaniGub** [comment]
@gabrieladamarques

**Comment by RaniGub** [comment]
@uira não esquece de alinhar com a Wilma.

**Comment by RaniGub** [comment]
@pauloamoreira verifique com a Wilma da Adins o que foi definido sobre essa demanda.

**Comment by pauloamoreira** [comment]
@RaniGub em conversa hoje, 11/01, com Emanuelle Costa, da Adins, fui informado que a oficina irá ocorrer, mas como parte da equipe está de férias, inclusive a Wilma Lins, o contato com o Felicilab será retomado na segunda quinzena de janeiro.

**Comment by RaniGub** [comment]
Tarefa temporariamente bloqueada. Aguardando posicionamento da Adins.

**Comment by uira** [comment]
Responder ao email do Nicolas, informando que será atendido pelo despacho do Ofício 010/2022 da SEPOS.

**Comment by pauloamoreira** [comment]
.em reunião com Camila Mendes (Sepos - Política de Transplantes), dia 14/02, foi apontada a data do primeiro encontro para a oficina dia 09/03 ou 10/03 e para o segundo encontro (caso seja necessário) dia 16/03 ou dia 17/03 - em todos os casos a oficina ocorrerá das 8h as 12h. aguardo @RaniGub e @uira  validarem as datas para confirmar com a Camila.

**Comment by RaniGub** [comment]
Nova prioridade: Alta.

**Comment by pauloamoreira** [comment]
.através de contato com Camila Mendes, dia 16/02/2022, as datas das oficinas foram reajustadas para os dias 16/03 e 23/03, de modo a não haver conflito com datas das oficinas para as Pessoas com Deficiência.
