### ISSUE TITLE
Fluxo de Dados dos painéis do IntegraSUS

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#198]
## **Objetivo**

**Como** designer  
**Quero** participar das reuniões do comitê de governança
**Para** propor um fluxo para visualização das jornadas dos Dados do IntegraSUS

## **Contexto**

É preciso a revisão de alguns painéis que apresentam inconsistências de dados no IntegraSUS. Para isso, foi criado um Comitê de Governança para discutir as dimensões estratégicas e operacionais das ações a serem tomadas. A ESP-CE, através do DesignLab, apoiará o desenvolvimento do Diagnóstico Situacional através de um fluxo que permitirá a elaboração de um modelo para revisão de painéis. Além disso, outras ações de design estão previstas para acontecer no decorrer da colaboração.

## **Escopo**
- Diagnóstico situacional (Iniciado pela SESA sem participação do DesignLab
- [ ] AI dos painéis do IntegraSUS
- [ ] Fluxo de criação e revisão de painéis
- [ ] Fluxo de desativação de painéis
- [ ] Modelo para demandar a criação de painel 
- [ ] Modelo para demandar atualização de painel

## Observações
https://www.figma.com/file/1i1tx2AUTidrHKUsAimj75/Fluxo-de-Dados-IntegraSUS?node-id=0%3A1

**Comment by RaniGub** [comment]
AI parcial realizada até os Indicadores da Escola de Saúde Pública do Estado.

**Comment by RaniGub** [comment]
Tarefa temporariamente bloqueada, aguardando posicionamento da SESA.

**Comment by RaniGub** [comment]
E-mail de histórico e status de entregas enviado para a Alta Gestão.

**Comment by uira** [comment]
Foi enviado email reportando as atividades realizadas.

Essa tarefa será fechada.
