### ISSUE TITLE
Design de Interface e Experiência: Observatório de Educação Permanente

### ISSUE THREAD

**Issue by rodrigoplimafreire** [EscolaDeSaudePublica/DesignLab#20]
# Objetivo
**Eu como** usuário
**Quero** acessar o site do Observatório
**Para que** possa acompanhar o projeto e seus resultados

# Contexto
Foi preparado um espaço de interação entre os centros de estudos das unidades hospitalares para um projeto piloto. Estas informações é um ponto de entrada com o observatório.

A intenção que a Rede Estadual de Gestão das unidades de saúde seja um local de compartilhamento de ações realizadas ou que serão realizadas por todas as unidades do estado do Ceará.

# Definições

- [x] @Uirá: Previsão de entrar em produção na segunda semana de março, com previsão de conclusão de 2 semanas.

# Observações

-

**Comment by danielgula** [comment]
O MVP do site foi terminado com UX e foi feita a implementação de código do site nos servidores da nuvem.
Projeto pode ser acessado em:
https://observatorio.esp.ce.gov.br/
