### ISSUE TITLE
Arquitetura da Informação de funcionalidade | Mapa da Saúde | Integrações

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#205]
## **Objetivo**

**Como** designer
**Quero** propor a AI de funcionalidades do Mapa da Saúde
**Para** sugerir camadas de integração com outras Soluções Digitais

## **Contexto**
Devemos identificar as oportunidades de integração nas Soluções Digitais do SUS/CE para proporcionar a pessoa usuária o acesso a funções essenciais compartilhadas e melhoria na experiência.

## **Escopo**

- [x] 1 Mapa da Saúde

## **Outras Informações**

Board (em processo):
https://www.figma.com/file/3bVWg3Hy3luha6sjBx4QKs/Arquitetura-da-Informa%C3%A7%C3%A3o-de-funcionalidade-Integra%C3%A7%C3%B5es?node-id=0%3A1

**Comment by RaniGub** [comment]
Revisão realizada e alterações propostas.

**Comment by pauloamoreira** [comment]
board atualizada. aguardando a elaboração da board com funcionalidades do iSUS para elaborar a integração.

**Comment by pauloamoreira** [comment]
.board atualizado. aguardando validação do @RaniGub para finalizar a tarefa.

**Comment by RaniGub** [comment]
Uirá sinalizou que vamos tentar um encontro na Quinta-feira 03/02/21 no período da tarde.

**Comment by pauloamoreira** [comment]
@RaniGub e @uira board atualizado.
