### ISSUE TITLE
Arquitetura da Informação de funcionalidade | iSUS | Integrações

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#206]
## **Objetivo**

**Como** designer
**Quero** propor a AI de funcionalidades do iSUS
**Para** sugerir camadas de integração com outras Soluções Digitais

## **Contexto**
Devemos identificar as oportunidades de integração nas Soluções Digitais do SUS/CE para proporcionar a pessoa usuária o acesso a funções essenciais compartilhadas e melhoria na experiência.

## **Escopo**

- [x] 2 iSUS

## **Outras Informações**

Board (em processo):
https://www.figma.com/file/3bVWg3Hy3luha6sjBx4QKs/Arquitetura-da-Informa%C3%A7%C3%A3o-de-funcionalidade-Integra%C3%A7%C3%B5es?node-id=0%3A1

**Comment by RaniGub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DesignLab-606d8c0a23f88d0010676dd5/issues/EscolaDeSaudePublica/DesignLab/206?planning-poker) with ZenHub @MayaraMonte @pauloamoreira

**Comment by pauloamoreira** [comment]
.board atualizado. aguardando validação do @RaniGub para finalizar a tarefa

**Comment by pauloamoreira** [comment]
@RaniGub e @uira board atualizado.

**Comment by RaniGub** [comment]
@uira fico imaginando se ainda faz sentido continuarmos com essa tarefa... ai voltamos aquele papo de estarmos limitados às funcionalidades e não fazermos o processo de descobrir as potencialidades dos produtos.

Tanto para o caminho de entendermos quais passos a seguir com o que já se tem de tarefas e como integrá-las, quanto para traçar a projeção de entregas nos projeto... teremos o momento de pensar nas integrações com os times e priorizações através das inceptions.
