### ISSUE TITLE
Arquitetura da Informação de funcionalidade | QualiQuiz | Integrações

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#207]
## **Objetivo**

**Como** designer
**Quero** propor a AI de funcionalidades do Mapa da Saúde
**Para** sugerir camadas de integração com outras Soluções Digitais

## **Contexto**
Devemos identificar as oportunidades de integração nas Soluções Digitais do SUS/CE para proporcionar a pessoa usuária o acesso a funções essenciais compartilhadas e melhoria na experiência.

## **Escopo**

- [x] 3 QualiQuiz

## **Outras Informações**
https://www.figma.com/file/Wi3wC9PUbrgHnMCqSaMJpp/Arquitetura-da-Informa%C3%A7%C3%A3o-de-funcionalidade-%7C-QualiQuiz-%7C-Integra%C3%A7%C3%B5es-%23207?node-id=0%3A1

**Comment by RaniGub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DesignLab-606d8c0a23f88d0010676dd5/issues/EscolaDeSaudePublica/DesignLab/207?planning-poker) with ZenHub @MayaraMonte @pauloamoreira

**Comment by pauloamoreira** [comment]
arquitetura mapeada e board criado. aguardando pareamento com @RaniGub

**Comment by RaniGub** [comment]
Essa tarefa será rediscutida com o Uirá considerando nossa nova compreensão sobre os produtos.
