### ISSUE TITLE
Criar apresentação institucional do Mapa da Saúde

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/DesignLab#208]
## **Objetivo**

**Como** gestor no NIT/FeliciLab
**Quero** uma apresentação institucional do Mapa da Saúde
**Para** prospectar parceiros e oportunidades

## **Contexto**
O time do Mapa da Saúde tem visualizado oportunidades de crescimento para o produto que se conectam com diversas demandas de outros projetos da Saúde no Ceará. É necessário elaborar uma apresentação sucinta, aos moldes da do iSUS, que demonstre o conceito do projeto, seus objetivos e potencial de geração de valor.

## **Escopo**

- [X] Definir conteúdo da apresentação
- [X] Redigir textos e itens imagéticos
- [X] Diagramar conteúdo no Google Apresentações

## **Critérios de Aceitação**

- [ ] Apresentação Mapa da Saúde
**Dado que** acesso a pasta do Mapa da Saúde no Google Drive
**Quando** clico no arquivo "Apresentação Institucional Mapa da Saúde"
**então** devo visualizar os slides com o conteúdo definido

## **Outras Informações**

Roteiro apresentação: https://docs.google.com/document/d/1xR94e1HlEBN4O4fzagkzi-G1hAF8ooXh9HlcZAQSVa0/edit?usp=sharing
Apresentação de referência: https://docs.google.com/presentation/d/1WOtN6tj8QX9jzbOJeAKakEi32z-a7vsm7dqk-hnIFfU/edit?usp=sharing
https://mapadasaude.dev.org.br/
Apresentação:
https://docs.google.com/presentation/d/1gC1XHAtxvVmw9u0E1DdOTRtsErGYMEg4I_4ETyCPpdA/edit#slide=id.p1

**Comment by RaniGub** [comment]
Tarefa transferida para o DesignLab.

**Comment by RaniGub** [comment]
@caldy94 aproximar @thaistoscano

**Comment by pauloamoreira** [comment]
.pareei com a @caldy94  e repassei os links das pastas no drive onde existem versão anteriores de apresentações do Mapa da Saúde e orientei que ela buscasse saber com a @Clarisse1983 se o texto de atualização que estava sendo produzido pelas Narrativas em nov de 2021 foi finalizado e onde está disponível. também compartilhei este link de um artigo sobre criação de slides: [https://guykawasaki.com/the-only-10-slides-you-need-in-your-pitch/](url)

**Comment by caldy94** [comment]
Roteiro para o slide está sendo produzido no link https://docs.google.com/document/d/1xR94e1HlEBN4O4fzagkzi-G1hAF8ooXh9HlcZAQSVa0/edit?usp=sharing  (que também se encontra acima)

**Comment by caldy94** [comment]
Modelo de slides disponibilizado:
https://docs.google.com/presentation/d/1gC1XHAtxvVmw9u0E1DdOTRtsErGYMEg4I_4ETyCPpdA/edit#slide=id.p1

**Comment by caldy94** [comment]
Slides atualizados

**Comment by RaniGub** [comment]
@thaistoscano você pode parear com a Caldy para validar o formato da apresentação? Obg.

**Comment by caldy94** [comment]
Apresentação está com o conteúdo pronto, ainda fiquei de parear a respeito dos GIFS de apresentação com a @thaistoscano. De resto acredito que esteja tudo sob conformes.

**Comment by caldy94** [comment]
@thaistoscano, slide da página 8 foi alterado, depois dê uma olhada, por favor.
