### ISSUE TITLE
Mapa Mental de Ações Integradas | Plano de Contingência à Pandemia da ESP-CE 2022

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#210]
## **Objetivo**

**Como** designer
**Quero** compreender as relações das ações do Plano de Contingência à Pandemia da ESP-CE
**Para** sugerir um Mapa Mental que será utilizado como mediação das ações para o Projeto

## **Contexto**
É preciso visualizar as ações propostas pelos setores da ESP-CE para nortear as discussões com a Superintedência.

## **Escopo**

- [x] Analisar o documento
- [x] Propor um Mapa de Mental relacionando os pontos essenciais
- [x] Identificar trajetórias de ações integradoras
- [x] Criar representação visual das ações integradas

## **Outras Informações**
[PLANO DE CONTINGÊNCIA COVID ESP 2022.pdf](https://github.com/EscolaDeSaudePublica/DesignLab/files/7905729/PLANO.DE.CONTINGENCIA.COVID.ESP.2022.pdf)

Proposta de Mapa Mental (simulação):
https://www.figma.com/file/YxFzwPizxzUvNs99sX83zT/Mapa-Mental-do-Plano-de-Conting%C3%AAncia-%C3%A0-Pandemia-da-ESP-CE-%23210?node-id=0%3A1

**Comment by RaniGub** [comment]
Data de encaixe na sprint: 21/01/2021

**Comment by pauloamoreira** [comment]
@uira segue proposta de mapa mental para o plano de contingência: https://www.figma.com/file/YxFzwPizxzUvNs99sX83zT/Mapa-Mental-do-Plano-de-Conting%C3%AAncia-%C3%A0-Pandemia-da-ESP-CE-%23210?node-id=0%3A1

**Comment by pauloamoreira** [comment]
A partir de feedback do @uira, ampliamos o escopo da tarefa e voltamos a trabalhar nela.

**Comment by pauloamoreira** [comment]
@uira segue proposta para Diagrama de Integração entre Ações, para sua análise: https://www.figma.com/file/VPHxEFLmE6t0A2prm8wZN0/Diagrama-de-Integra%C3%A7%C3%A3o-entre-A%C3%A7%C3%B5es?node-id=0%3A1

**Comment by pauloamoreira** [comment]
@uira segue fluxo (atualizado em 26/01) referente ao diagrama da integração de ações, para sua análise: https://www.figma.com/file/vwfB39lthoTNwordlZC8iv/FLUXO-DE-INTEGRA%C3%87%C3%83O-DAS-A%C3%87%C3%95ES?node-id=0%3A1

**Comment by pauloamoreira** [comment]
@uira atualizei o Diagrama: https://www.figma.com/file/VPHxEFLmE6t0A2prm8wZN0/Diagrama-de-Integra%C3%A7%C3%A3o-entre-A%C3%A7%C3%B5es?node-id=0%3A1

**Comment by RaniGub** [comment]
Aguardando revisão.
