### ISSUE TITLE
Diagrama de integração entre as ações | Plano de Contingência à Pandemia da ESP-CE 2022

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#211]
## **Objetivo**

**Como** designer
**Quero** compreender as relações das ações do Plano de Contingência à Pandemia da ESP-CE
**Para** sugerir um Diagrama de integração entre as ações 

## **Contexto**
É preciso visualizar as ações propostas pelos setores da ESP-CE para nortear as discussões com a Superintedência.

## **Escopo**

- [x] Diagrama de integração entre as ações
- [x] Adequação em mandala

## **Outras Informações**
[PLANO DE CONTINGÊNCIA COVID ESP 2022.pdf](https://github.com/EscolaDeSaudePublica/DesignLab/files/7905729/PLANO.DE.CONTINGENCIA.COVID.ESP.2022.pdf)

Proposta de Diagrama de Integração entre Ações:
https://www.figma.com/file/VPHxEFLmE6t0A2prm8wZN0/Diagrama-de-Integra%C3%A7%C3%A3o-entre-A%C3%A7%C3%B5es?node-id=0%3A1

**Comment by RaniGub** [comment]
Aguardando revisão.

**Comment by RaniGub** [comment]
Expectativa de pontos atualizada: 8

**Comment by pauloamoreira** [comment]
Diagrama atualizado com a inclusão das ações da Comunicação.

**Comment by uira** [comment]
Ficou ótimo, vamos enviar para a ADINS e aguardar a oportunidade para apresentar ao Superintendente.

@pauloamoreira poderia marcar uma apresentação ao Marcus, da ADINS?
