### ISSUE TITLE
Fluxo de integração entre as ações | Plano de Contingência à Pandemia da ESP-CE 2022

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#212]
## **Objetivo**

**Como** designer
**Quero** compreender as relações das ações do Plano de Contingência à Pandemia da ESP-CE
**Para** sugerir um Fluxo de integração entre as ações 

## **Contexto**
É preciso visualizar as ações propostas pelos setores da ESP-CE para nortear as discussões com a Superintedência.

## **Escopo**

- [x] Fluxo de integração entre as ações
- [x] Adaptação do Fluxo tendo a inovação como segunda etapa
- [ ] Mapeamento dos meios para gerar a ação das áreas do Plano

## **Outras Informações**
[PLANO DE CONTINGÊNCIA COVID ESP 2022.pdf](https://github.com/EscolaDeSaudePublica/DesignLab/files/7905729/PLANO.DE.CONTINGENCIA.COVID.ESP.2022.pdf)

Fluxo de Integração das Ações (simulação):
https://www.figma.com/file/VPHxEFLmE6t0A2prm8wZN0/Diagrama-de-Integra%C3%A7%C3%A3o-entre-A%C3%A7%C3%B5es?node-id=0%3A1
https://www.figma.com/file/YxFzwPizxzUvNs99sX83zT/Mapa-Mental-do-Plano-de-Conting%C3%AAncia-%C3%A0-Pandemia-da-ESP-CE-%23210?node-id=0%3A1
https://www.figma.com/file/vwfB39lthoTNwordlZC8iv/FLUXO-DE-INTEGRA%C3%87%C3%83O-DAS-A%C3%87%C3%95ES

**Comment by RaniGub** [comment]
Aguardando revisão.

**Comment by RaniGub** [comment]
Expectativa de pontos atualizada: 8

**Comment by pauloamoreira** [comment]
Realizei, no dia 09/02/2022, pareamentos para mapeamento do fluxo-meio das áreas: Educação e Extensão (com @Fabriciomartins  e Luciana Rocha) e Comunicação (com Ariane Cajazeiras). permaneço no aguardo de disponibilidade de agenda de @uira (Inovação e Pesquisa) e Batista (Tecnologia) para finalizar os mapeamentos. Board Atualizado.

**Comment by RaniGub** [comment]
A tarefa será encerrada e retomada quando o cenário for pertinente. Ficaram como pendências a Inteligência e Tecnologia.

**Comment by RaniGub** [comment]
A tarefa será encerrada e retomada quando o cenário for pertinente. Ficaram como pendências a Inteligência e Tecnologia.
