### ISSUE TITLE
Proposta de Integrações V1.0 | Arquitetura de Funcionalidades das Soluções Digitais

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#219]
## **Objetivo**

**Como** designer
**Quero** propor a AI de funcionalidades do Mapa da Saúde
**Para** sugerir camadas de integração entre Mapa da Saúde e iSUS

## **Contexto**
Devemos identificar as oportunidades de integração nas Soluções Digitais do SUS/CE para proporcionar a pessoa usuária o acesso a funções essenciais compartilhadas e melhoria na experiência.

## **Escopo**

- [ ] Proposta de integração V1.0 | Mapa da Saúde e iSUS

## **Outras Informações**

Board (em processo):
https://www.figma.com/file/3bVWg3Hy3luha6sjBx4QKs/Arquitetura-da-Informa%C3%A7%C3%A3o-de-funcionalidade-Integra%C3%A7%C3%B5es?node-id=0%3A1

**Comment by uira** [comment]
@RaniGub conclua com o @pauloamoreira e marque um momento de pareamento com os BAs
