### ISSUE TITLE
1. Apoiar a Construção da Política Estadual de Prevenção e Proteção às mulheres, crianças e adolescentes (itens 1.1 a 1.3)

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#224]
## **Objetivo**

**Como** designer  
**Quero** apoiar a construção da Política Estadual  de Prevenção e Proteção às mulheres, crianças e adolescentes
**Para** nortear a elaboração do Plano Estadual de Prevenção e Proteção às mulheres, crianças e adolescente do Ceará (2022-2023)

A Secretaria Executiva de Políticas de Saúde - SEPOS/SESA, solicitou à Superintendência da ESP/CE, por meio do ofício 10/2022, apoio do DesignLab/Felicilab para facilitação na construção da Política Estadual de Prevenção e Proteção às mulheres, crianças e adolescentes. O pedido partiu da experiência na I Oficina de Design de Serviços Públicos, realizada com a Sepos em Ago/2021. Foi definido que a Adins será a responsável pela condução do processo e o DesignLab entrará como apoio. 

## **Escopo**
- [x] 1.1 Refinar a demanda com Marley Carvalho da Sepos
- [x] 1.2 Confirmar datas de realização
- [x] 1.3  Coletar informações complementares e documentos norteadores

## Observações
Épico: [Oficinas de Design para Políticas Públicas #225](https://github.com/EscolaDeSaudePublica/DesignLab/issues/225)
Pessoa de Contato: Marley Carvalho da Sepos.
![Captura de Tela 2022-02-15 às 09 18 38](https://user-images.githubusercontent.com/79097920/154060768-8c95dfd4-b8eb-4b8e-83e4-b28eb9c0d4d3.png)

**Comment by RaniGub** [comment]
No prioridade: Alta.
