### ISSUE TITLE
Reunião de Briefing | Curso de Letramento Digital para ACSs

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#267]
## **Objetivo**

**Como** designer
**Quero** compreender a demanda do curso de Letramento Digital para ACSs
**Para** informar os detalhes da demanda à Gestão

## **Contexto**

É preciso levantar os requisitos da demanda do curso de Letramento Digital para ACSs para que a Gestão delibere a possibilidade de execução e esforço necessário.
 
## **Escopo**

- [x] Reunião de Briefing (10/03, 9h)

## Observações
Quem participa? @pauloamoreira

**Comment by pauloamoreira** [comment]
data da reunião atualizada para 10/03.

**Comment by pauloamoreira** [comment]
.reunião realizada. o desenvolvimento dessa tarefa ocorrerá na #271
