### ISSUE TITLE
Proposta/estimativa para criação de publicação eletrônica com Linhas de Cuidado em Saúde do Trabalhador 

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#269]
## **Objetivo**

**Como** design
**Quero** apoiar a criação de Linhas de Cuidado em Saúde do Trabalhador 
**Para** informar os Profissionais de Saúde sobre autocuidados.

## **Contexto**
- A GEDUC recebeu da SESA uma demanda de 06 Linhas de Cuidado em Saúde do Trabalhador, visando, inicialmente, a elaboração/publicação de um e-book (ou publicação eletrônica) que será disponibilizado nas plataformas SESA, com chancela da ESP, e ações formativas conectadas com esse material.
- Ao DesignLab foi solicitado o apoio para refinamento da demanda, construção do fluxo e criação e implementação do projeto design. 

## **Escopo**

- [x] reunião de apresentação da proposta com Sheila Fontelene e Ananda (GEDUC) - 09/03, as 10h.
- [x] 1ª reunião de alinhamento - 14/03, as 14h, no Cevit - ESP.
- [ ] 2ª reunião de alinhamento - 22/03, as 14h, na Coordenadoria de Vigilância Epidemiológica e Prevenção em Saúde (COVEP).
- [ ] apresentação de proposta/estimativa de atendimento da demanda

## **Critérios de Aceitação**

- [ ] proposta/estimativa para produção de Linhas de Cuidado em Saúde do Trabalhador, que pode ou não incorporar publicação eletrônica
**Dado que** sou Gestor do Projeto  
**Quando** desejo analisar a proposta de produção e estimativa da criação de 06 Linhas de Cuidado em Saúde do Trabalhador
**então** visualizo as informações apresentadas e realizo a tomada de decisão.

## Observações
Links de apoio e informações adicionais

**Comment by pauloamoreira** [comment]
em reunião com Sheila Fontenele e Ananda (GEDUC), acertamos que irei, após parear com @RaniGub sobre essa demanda, enviar até sexta (11/03) briefing para levantamento de requisitos. Paralelamente, Sheila Fontenele informou que o projeto está sendo escrito e irá trazer novas informações para refinar a demanda.

**Comment by RaniGub** [comment]
Deliberação do Uirá:
- Participar da próxima reunião SE os stakeholders da Sesa estiverem presentes.

Obs.: Produzimos inovação com suporte de metodologias de design. Não produzimos artefatos que não estão conectados ao processo de inovação.

**Comment by RaniGub** [comment]
Aguardando relato da reunião pelo @pauloamoreira para conversamos com o @uira e definir se faz sentido continuarmos participando ou não das reuniões.

**Comment by pauloamoreira** [comment]
@uira @RaniGub Relato da Reunião do dia 14.03.2023 > estavam presentes: Ananda Coelho - GEDUC/ESPCE, Sheila Fontenele - GEDUC/ESPCE, Patrícia Elibabth - GEDUC-ESPCE, Paulo Amoreira - NIT/ESPCE, Mara CEREST/SESA,  Ângela COVAT/SESA e Vivian Gomes COVAT/SESA. Na reunião, Mara CEREST/SESA esclareceu que a proposta vai além da criação de protocolos clínicos e produção de um e-book, se configurando com a demanda de criação de Linhas de Cuidado em Saúde do Trabalhador (atualizei o nome e o escopo da tarefa nessa perspectiva). Perguntei se a escolha pela produção de um e-book havia sido feita a partir de um Diagnóstico Situacional e outros estudos, ao que Mara apontou que não havia ainda um diagnóstico e que a solução e-book havia sido uma sugestão da supervisão do CEGES e que esse diagnóstico era desejável e necessário e que estavam abertos a outras soluções, caso estas se mostrassem mais compatíveis com os objetivos propostos. Foram citadas diversas fontes de informação e materiais de apoio que seria, posteriormente, disponibilizados. a coordenadora do projeto na ESP, Sheila Oliveira apresentou um orçamento que havia solicitado a Patrícia, do financeiro da ESP. no entanto, esse orçamento ainda não consta do valor do trabalho a ser realizado pela DITEC/NIT, nem está alinhando com o perfil de conteudista que será viável para o projeto, além de ter sido elaborado a partir de uma expectativa de entrega diferente do que a Mara apresentou - originalmente, a proposta era apenas a criação de Protocolos e passou a ser a criação de Linhas de Cuidado. Mara também esclareceu que a expectativa é da entrega de 6 Linhas de Cuidado em Saúde do Trabalhador, sendo as três linhas que deveriam ser entregues em 2022:  1- Transtornos mentais relacionados ao trabalho, 2- LER/DORT e 3 – Dermatoses. As demais linhas serão entregues em 2023. No entanto, após considerações diversas sobre a viabilidade operacional, foi considerado que em 2022 fossem entregues 2 e em 2023 as outras 4. Apresentei a necessidade de que o trabalho realizado pelo Felicilab/Designlab envolva entregas que seguem processos de design, que podem ou não incluir artefatos, e que, como laboratório de inovação, estávamos disponíveis para oferecer esse serviço mais expandido para o projeto. Mara afirmou que há interesse nesse encaminhamento, no entanto, a coordenadora Sheila ainda não sinaliza que estamos sendo considerados nessa perspectiva, reafirmando a demanda de confecção de um e-book. a gerente do projeto Ananda compartilhou uma pasta com materiais diversos (ainda sem os materiais citados na reunião do dia 14) e uma nova reunião foi marcada para o dia 22/03, na COVEP, onde serão dados passos adicionais no alinhamento. solicitei novamente que fosse compartilhado conosco o processo relacionado a esse projeto, mas até agora não acessamos esse documento.

**Comment by RaniGub** [comment]
A Ananda, Gerente de Projetos das Linhas de Cuidado de Saúde do Trabalhador, informou que o orçamento disponível para as entregas das 3 linhas de cuidado para este ano são limitados e serão dedicas a contratação de conteudista. 

O grupo de planejamento, composto também pela Sheila Fontenele da educação, compreende que o Design é um processo fim, concretizado na operacionalização de artefatos, mesmo após a exposição das ideias do @pauloamoreira. Desta forma, encerro a nossa participação no processo. Uirá já está ciente.
