### ISSUE TITLE
Apoiar realização de capacitação para Agentes Comunitários de Saúde - ACS

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#271]
## **Objetivo**

**Como** designer
**Quero** apoiar a formatação de uma estratégia educacional
**Para** colaborar com uma ação formativa direcionada aos Agentes Comunitários de Saúde - ACS

## **Contexto**
- Em reunião com o Conselho Estadual de Saúde COSEMS CE, Associação dos Municípios do Ceará - APRECE, Federação  e Associação dos Agentes Comunitários de Saúde ACS e Agentes Comunitários de Edemias ACEs, os ACSs e ACEs encaminharam ofício para a ESP, solicitando Curso de Informática Básica em EaD para 14.600 ACSs e ACEs, visando o uso do aplicativo de gerenciamento de informações (e-SUS Território AB) utilizado pelos ACSs e ACEs. Os dados coletados pelo app são destinados à página de informações e indicadores do Departamento de Atenção Primária Ceará.
- DIDES / DEDUC E DITEC estão se propondo a apresentar a proposta de uma ação formativa que tenha como foco o uso do App e-SUS Território AB, mas que também possibilite a inclusão digital dos ACSs e ACEs.

## **Escopo**
- [x] Reuniões de alinhamento DIDES / DEDUC E DITEC
- [x] Coleta de informações adicionais
- [x] Análise de informações
- [x] Reunião de alinhamento de proposta de colaboração do DesignLab ao Projeto Piloto 16.05.2022
- [x] Inclusão de sugestões e aperfeiçoamentos no Projeto Piloto
- [x] Validação da proposta de aperfeiçoamento no Projeto Piloto pela DITEC
- [x] Validação da proposta de aperfeiçoamento no Projeto Piloto pela DIDES
- [x] Produção de relato para atualização para Ditec

## **Fora de Escopo**
- A documentação do App se resume a um manual em PDF.
- Os ACSs e ACEs tem perfil heterogêneo
- Não é possível acessar o App para verificar a Jornada de Usuário
- Testes de Usabilidade ainda não foram aplicados
- Em Fortaleza (capital) os ACSs e ACEs não utilizam o App
- Os ACSs e ACEs do interior utilizam o App em um tablet. 
- Os ACSs e ACEs de Fortaleza não usam o App, ainda utilizam os formulários em papel, para posterior lançamento das informações em um sistema, através de computador desktop.
- em 14/03 será iniciado um curso técnico nacional de Agente de Saúde. É necessário analisar se módulos previstos nessa formação pode ser considerados.
- Fonte do recurso/valor disponível e cronograma ainda não estão disponíveis.

## **Critérios de Aceitação**
- [ ] DesignLab colabora com formação para os ACSs e ACEs.
**Dado que** o DesignLab colaborou com a formação dos ACSs e ACEs
**Quando** a formação é realizada  
**então** a participação do DesignLab gera valor para os ACSs e ACEs. 

## Observações
Manual App e-SUS Território [https://app.zenhub.com/files/235795051/d86696d0-4f36-4d06-9ffa-5773939fae49/download](https://app.zenhub.com/files/235795051/d86696d0-4f36-4d06-9ffa-5773939fae49/download)

1ª versão da Proposta de Projeto (ainda sem inclusões do felicilab): 
[Proposta de projeto.pdf](https://github.com/EscolaDeSaudePublica/DesignLab/files/8224239/Proposta.de.projeto.pdf)

**Comment by pauloamoreira** [comment]
Reunião de alinhamento inicial realizada em 10/03.

**Comment by uira** [comment]
@pauloamoreira Paulo, quero muito conversar contigo sobre isso. Você está na ESP? Consegue colar aqui?

**Comment by RaniGub** [comment]
Participar da próxima reunião, se não cair em um horário da Oficina e alinhar com a Flavianne a compreensão que nosso apoio faz sentido na perspectiva que o Letramento Digital do ACS tem desdobramento em várias camadas que transpassam a simples proposta de criar um curso EAD para eles.

Não compreendemos como um curso EAD mediado por uma plataforma digital irá solucionar um problema de pessoas que não sabem operar uma plataforma digital. Devemos compreender a história do usuário e saber os desdobramentos com base nessa análise.

**Comment by RaniGub** [comment]
A participação do Paulo se dará inicialmente no apoio do desenvolvimento do Projeto caso seja entendido que o DesignLab participará do processo.

**Comment by RaniGub** [comment]
Aguardando posicionamento formal sobre a deliberativa da formatação do Curso com o apoio do Designlab. Pelo cenário exposto na reunião, já parece existir um desenho de um curso em processo de formatação. Uma pessoa chamada Vanessa (Gerência de Educação Profissional em Saúde) ficou de entrar em contato quando tiverem novas informações. 

Acreditamos que o design deva participar desde o processo de planejamento e não somente após as decisões já terem sido tomadas.

Enquanto isso, vamos atualizando a evolução do processo por essa tarefa.

![Captura de Tela 2022-03-15 às 08 59 11](https://user-images.githubusercontent.com/79097920/158373262-535af4ec-a1dc-41b2-be16-5a24b31dc0a6.png)

@uira

**Comment by RaniGub** [comment]
Repassei para o @pauloamoreira um alinhamento que tinha realizado com a Vanessa sobre nossa colaboração nesse início de processo. Acordamos que será marcada uma reunião para apresentação do processo no dia 28 ou 29/03. 
A ideia é que caso surja alguma dúvida durante a elaboração desse fluxo metodológico, a Vanessa seja consultada como referência.

**Comment by pauloamoreira** [comment]
.após conversa com @RaniGub, entendemos que é importante rodar uma Árvore de Problemas + Inception dessa demanda, de modo a refinar o problema e obter clareza sobre as entregas que podem ser realizadas. nesse sentido, entrei em contato com a Vanessa Araújo (Gerência de Educação Profissional em Saúde) para propor esse encaminhamento e ela me informou que a Mara Pinheiro irá entrar em contato comigo para tratar desse assunto.

**Comment by pauloamoreira** [comment]
.em conversa com Mara Pinheiro, em 28/03, apresentei nossa proposta para um momento para rodar uma Árvore de Problemas + Inception. ela disse que iria alinhar com a Vanessa Araújo, pois estão no momento de consolidar um grupo que irá seguir no processo de construção coletiva e que a nossa atividade já poderia ser aplicada nesse grupo. ficou de retomar o contato após esse alinhamento.

**Comment by pauloamoreira** [comment]
.reunião online com Vanessa Araújo e Mara Pinheiro marcada para o dia 29/03, para alinhamento.

**Comment by pauloamoreira** [comment]
.em reunião realizada, no dia 29/03, com a presença de Vanessa Araújo, Mara Pinheiro e outras pessoas da Gerência de Educação Profissional em Saúde e o Clayton da EaD.  Apresentei as ferramentas Árvores de Problemas e Inception, considerando os resultados esperados nesses dois processos. Vanessa apontou preocupação com o fato de que, por se tratar de ferramenta digital, poderia oferecer obstáculos para os Agentes que não tivessem habilidade com essas ferramentas, também destacou que o corpo total de beneficiados é de 14 mil agentes, organizados em cerca de 180 grupos. mas que iremos rodas as ferramentas em um grupo reduzido, formado por: Representante da federação dos ACS e ACE, Representantes das associações  dos ACS e ACE, e representes da APRECE e COSEMS, Técnicos da GEPRO. desta forma, iremos progredir nas tratativas para criar a agenda dos encontros para essa atividade.

**Comment by RaniGub** [comment]
@pauloamoreira essa atividade agora pode ser desdobrada em mais de uma issue, considerando também a realização da Inception. Vamos atualizar o escopo e dar encaminhamento para o que já foi concluído.

**Comment by pauloamoreira** [comment]
em reunião do Estratégico, no dia 08.04.2022, foi decidido que Flavianne Soares (DITEC) irá marcar reunião com a Gerência de Educação Profissional em Saúde para alinhar datas para os passos seguintes.

**Comment by RaniGub** [comment]
Estamos aguardando posicionamento acerca da reunião para dar continuidade da tarefa.

**Comment by RaniGub** [comment]
Retorno da Flaviane: A reunião ainda não foi priorizada. Aguardaremos atualizações.

**Comment by pauloamoreira** [comment]
dia 16.05.2022 foi realizada reunião na DITEC com a presença da DIDES, Gerência de Educação Profissional em Saúde, EaD, DITEC e Felicilab/Designlab, para alinhamento de expectativas e responsabilidades em relação à colaboração entre as áreas na elaboração do projeto piloto para a capacitação de ACS e ACE. Na ocasião, ficou firmando que o projeto que está sendo elaborado pela DIDES/Gerência de Educação Profissional em Saúde seria compartilhado, para receber contribuições da DITEC/Felicilab. Também ficou acertado que não será realizada a aplicação da Árvore de Problemas, para elaboração de diagnóstico situacional, já que a Gerência de Educação já iniciou a aplicação de um formulário eletrônico para levantamento de dados junto aos ACSs e ACEs. Desta forma, nesse projeto piloto, a participação da DITEC/Felicilab será na colaboração na escrita do projeto e, quando os recursos forem captados, elaboração de conteúdos específicos, e contribuições associadas a este processo.

**Comment by pauloamoreira** [comment]
recebi o acesso ao documento e já comecei a inclusão de contribuições e sugestões de aperfeiçoamentos. aguardo agora a validação de @RaniGub .

**Comment by RaniGub** [comment]
Paulo participou de uma reunião dia 27/06 com a Vanessa Araújo, Leni Nobre, Mara, Alex e outros envolvidos no Projeto. Um relato está sendo concluído para disponibilização à Ditec e Coordenção do Felicilab.

**Comment by pauloamoreira** [comment]
Relato da reunião enviado para @RaniGub. aguardando deliberações.

**Comment by RaniGub** [comment]
Relato repassado para o estratégico.

**Comment by pauloamoreira** [comment]
A partir de retorno de @RaniGub , as informações solicitadas foram encaminhadas para Vanessa Araújo - Gerências de Educação Profissional, e agora permanecemos no aguardo de retorno.
