### ISSUE TITLE
Preparar apresentação do Novo Site da ESP | Projeto

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#274]
## **Objetivo**

**Como** designer  
**Quero** preparar a apresentação das etapas para desenvolvimento do Novo Site da ESP
**Para** contextualizar a Superintendência

## **Contexto**
Devemos analisar os pontos essenciais abordados no projeto para apresentação para Superintendência.

## **Escopo**

- [x] Criar apresentação

## Observações
https://docs.google.com/document/d/1ookvo2vaOoiR13x18lpNhVYHF52-h9UOZNEjW5UG_wA/edit#

https://docs.google.com/presentation/d/1ajIpY4otU_ZOLcicO9AGVVfk4glR_ElNWbVqtatakcQ/edit?usp=sharing

**Comment by RaniGub** [comment]
Definir prioridade no Tático.

**Comment by caldy94** [comment]
Apresentação finalizada, aguardando feedback do @RaniGub

**Comment by RaniGub** [comment]
@caldy94 nesta terça (29/03) terei reunião com a Gaby para pontuar algumas coisas. Lhe indico quando a atualização for realizada.

**Comment by RaniGub** [comment]
@caldy94 me lembre amanhã da gente conversar, o projeto foi fechado e precisa de mínimas atualizações do time de projeto.

**Comment by caldy94** [comment]
@RaniGub tudo bem, vamos falar após a daily, qualquer coisa to presencial

**Comment by caldy94** [comment]
Slides atualizados. Link? https://docs.google.com/presentation/d/1ajIpY4otU_ZOLcicO9AGVVfk4glR_ElNWbVqtatakcQ/edit#slide=id.g120e2b30ff0_0_0

**Comment by RaniGub** [comment]
Link de apresentação compartilhado com @gabrieladamarques e @uira
