### ISSUE TITLE
Análise da Board: Histórias e Jornadas | Reunião HackLab 6

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#280]
## **Objetivo**

**Como** designer  
**Quero** discutir sobre informações disponibilizadas pelo HackLab
**Para** sugerir melhorias no processo de Redesign do Mapas

## **Contexto**

A reunião semanal com o HackLab tem o objetivo de contribuir com o processo de Redesign da Plataforma Mapas.

## **Escopo**

- [x] Discutir sobre pontos observados na pré-análise 6
- [x] Pactuar próximos pontos a serem analisados

## Observações
Ata de acompanhamento das reuniões:
https://docs.google.com/document/d/15T7RVk5T56SHwBMnRJNKd6sgclfj7e5RNQ2YED-VmDU/edit?usp=sharing

**Comment by RaniGub** [comment]
Escopo atualizado. @pauloamoreira pactuei com a Luiza que é importante no final de cada reunião pactuarmos o que será feito na pré-análise da semana seguinte e que a board com esse acordo deve dispor das informações até o final da manhã de toda quarta-feira.

**Comment by pauloamoreira** [comment]
.ok, @RaniGub .
