### ISSUE TITLE
Estudo de metodologia de priorização complementar a GUT (BASICO)

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#283]
## **Objetivo**

**Como** designer
**Quero** estudar a viabilidade de uma adaptação da metodologia BASICO/GUT  
**Para** auxiliar na dinâmica de priorização dos problemas na Oficina de Serviços da ESP

## **Escopo**

- [x] estudar possibilidades já existentes
- [x] estudar a GUT já utilizada pela oficina
- [x] propor adaptações
- [x] testar

## Observações
https://docs.google.com/spreadsheets/d/1kAEApWi00vJyfvwl6SvCcaL6d5k4re7WBnh-Wkqh0Fc/edit#gid=65199659

**Comment by MayaraMonte** [comment]
Terá continuidade da #285
