### ISSUE TITLE
Proposta metodológica para compreensão de tarefas e priorizações para os times de produtos

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#285]
## **Objetivo**

**Como** designer  
**Quero** propor um fluxo metodológico
**Para** ter melhor visão das integrações de tarefas dos times de produto e suas priorizações

## **Contexto**
O Designlab fará uma proposta de metodologia para relacionamento entre as atuais tarefas dos times de produtos com objetivo de apoiar a compreensão do que deve ser priorizado com base nas Histórias dos Usuários e a EAP originalmente traçada nos projetos.

## **Escopo**

- [x] Ensaiar metodologia
- [x] Revisão por Pares (Rani)
- [x] Apresentar o Fluxo para o Grupo Tático em 28/03

## Observações
Ferramentas estudadas: https://www.figma.com/file/6i7Yjhfr9fbIKcSSHPDWjI/An%C3%A1lise-de-ferramentas-de-prioriza%C3%A7%C3%A3o?node-id=0%3A1

**Comment by RaniGub** [comment]
@elpadrejorge

**Comment by elpadrejorge** [comment]
Com base na conversa em que tivemos na reunião do tático de hoje, 28/03, alguns ajustes precisam ser feitos no fluxo metodológico para que o board fique disponível para o time do tático até amanhã.

**Comment by RaniGub** [comment]
Hoje o processo foi atualizado, amanhã iremos disponibilizar para o time tático após refinamento.
