### ISSUE TITLE
Organização das gravações de Fev e Mar/2022 | DesignLab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#288]
## **Objetivo**

**Como** gestor do DesignLab
**Quero** organizar todos as gravações no drive
**Para** disponibilizar para as pessoas que participaram dos processos do Lab

## **Contexto**
Nas últimas semanas ocorreram uma série de encontros importantes que devem estar disponíveis e para as pessoas que não conseguiram participar de todos. Dentre eles tem-se a imersão no Redesign do Mapas, as Oficinas de Construção de Políticas Públicas e a experimentação da nova versão da Inception de Projetos e Produtos. 

## **Escopo**
- [x] Renomear arquivos do drive
- [x] Dispor de um documento organizado com títulos, data e links para acesso
- [x] Inserir conteúdos das oficinas - Paulo (considerar informações sensíveis)

## Observações
Inserir link do documento aqui

https://drive.google.com/drive/folders/1V2YBtpQgS3RpUFME_gEXPRBfTpN1tf0I?usp=sharing

**Comment by caldy94** [comment]
Tarefa concluída! @RaniGub, checar se tudo está correto, por favor.

**Comment by RaniGub** [comment]
Ok Caldy, obg. Paulo você pode atualizar a memória das Oficinas nesse documento. Vamos pensar numa organização que faça sentido para todes, considerando as informações sensíveis como você levantou .

**Comment by pauloamoreira** [comment]
.será necessário aguardar o @RaniGub (que criou a pasta) voltar de férias para acessarmos as pastas do drive com privilégios de edição, para finalizarmos essa tarefa.

**Comment by RaniGub** [comment]
Pasta compartilhada com @pauloamoreira
