### ISSUE TITLE
Redesign do fluxo de metodologia de trabalho Felicilab

### ISSUE THREAD

**Issue by MayaraMonte** [EscolaDeSaudePublica/DesignLab#291]
## **Objetivo**

**Como** designer  
**Quero** redesenhar o fluxo de trabalho do FeliciLab  
**Para** tornar o trabalho cíclico 

## **Contexto**

- O desenho utilizado para compor a dinâmica de entendimento do fluxo de trabalho do FeliciLab que foi apresentado no MVP 1 do onboarding foi apresentado de forma linear, precisamos dispor de uma visualização cíclica para que o processo de desenvolvimento possa ser apresentado para contextualizar as pessoas que estão chegando ou validar com as pessoas que já estão no laboratório e ainda não entendem de que forma trabalhamos.

## **Escopo**

- [x] Analisar o fluxo original 
- [ ] Propor melhoria do fluxo 

## **Critérios de Aceitação**

- [x] titulo  
**Dado que** o nosso fluxo de trabalho acontece de uma forma ciclica
**Quando** apresentamos esse fluxo de modo linear 
**então** não fica claro o seu funcionamento

## Observações
https://www.figma.com/file/17Pe21H4iKHG4KgVq8OBQM/Metodologia-de-trabalho-Felicilab?node-id=0%3A1

**Comment by MayaraMonte** [comment]
Atividade finalizada, aguardando revisão

**Comment by caldy94** [comment]
Trabalho finalizado, aguardando aprovação. imagem no link: https://www.figma.com/file/17Pe21H4iKHG4KgVq8OBQM/Metodologia-de-trabalho-Felicilab?node-id=0%3A1

**Comment by RaniGub** [comment]
@pauloamoreira e @elpadrejorge por gentileza, alinhem essa proposta quando possível. Tanto na camada de fluxo quanto estética.

**Comment by pauloamoreira** [comment]
.em reunião com @MayaraMonte e @caldy94 foram sugeridos aperfeiçoamentos. no aguardo de nova versão.

**Comment by caldy94** [comment]
Tarefa conclúida, aguardando pareamento. Link atualizado: https://www.figma.com/file/17Pe21H4iKHG4KgVq8OBQM/Metodologia-de-trabalho-Felicilab?node-id=0%3A1

**Comment by caldy94** [comment]
Tarefa atualizada. https://www.figma.com/file/17Pe21H4iKHG4KgVq8OBQM/Metodologia-de-trabalho-Felicilab?node-id=0%3A1

**Comment by caldy94** [comment]
Outra atualização após pareamento com @pauloamoreira.

**Comment by caldy94** [comment]
Tarefa atualizada e finalizada.

**Comment by MayaraMonte** [comment]
Tarefa ainda não finalizada, o conteúdo está pendente de validação com a @gabrieladamarques

**Comment by pauloamoreira** [comment]
@MayaraMonte você já conseguiu parear com a @gabrieladamarques sobre essa tarefa?

**Comment by RaniGub** [comment]
Gente não é necessário pareamento com a Gabi para esse fluxo. Foi inicialmente desenhado pelo Uirá com ajuda do Dan. Depois refinei com o Uirá. É importante observar se no modelo atual estão previstas as inceptions da forma que estamos fazendo. Sugestão:
1 - Atualizar a versão original
2 - Espelhar atualizações na versão cíclica

@pauloamoreira por favor, alinhe nessa terça de manhã com a Caldy (26/04)

**Comment by caldy94** [comment]
Ciclo atualizado com base nas mudanças propostas pelo @pauloamoreira https://www.figma.com/file/17Pe21H4iKHG4KgVq8OBQM/Metodologia-de-trabalho-Felicilab?node-id=0%3A1

**Comment by RaniGub** [comment]
@caldy94 conversei com o @pauloamoreira para conversar sobre essa tarefa com você assim que possível.

**Comment by caldy94** [comment]
Ciclo editado, aguardo revisão do @RaniGub

**Comment by caldy94** [comment]
Esboçando o fluxo de acordo com as mudanças feitas por @RaniGub e outras pessoas. Ainda farei revisões.

![image](https://user-images.githubusercontent.com/101121073/170776833-98356ed5-7a44-4e23-b918-089fb19a8290.png)

**Comment by caldy94** [comment]
Atualizado por enquanto
![Uploading ciclo-metodologia-esboço.jpg…]()

**Comment by caldy94** [comment]
Atualizado por enquanto

![ciclo-metodologia-esboço](https://user-images.githubusercontent.com/101121073/171158914-523af536-98a5-4ed5-bfdc-1ed5cde679ef.jpg)

**Comment by RaniGub** [comment]
Bom dia @caldy94, por gentileza, coloque o arquivo aberto (.ai) no drive do design e disponibilize o link aqui. Obg.

**Comment by caldy94** [comment]
@RaniGub ,O arquivo está no computador 24 na ESP, quando estiver aí na próxima semana, envio
