### ISSUE TITLE
Apoiar a Transcrição/revisão de histórias das tarefas da Central de Informações

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#295]
## **Objetivo**

**Como** designer
**Quero** mediar a transcrição das histórias da Central de Informações no Figma
**Para** Realizar o match das histórias do GitHub com as histórias mapeadas na Inception.

## **Contexto**

Para clarificar a EAP original do Projeto Mapas e Soluções e dar apoio à tomada de decisão de quais passos devem ser tomadas pelos times do Felicilab, será realizada uma "engenharia reversa" através de uma inception ao longo do mês de abril/22. Os momentos visam a criação e organização de histórias para planejamento dos times. Nesse contexto, se faz necessário transcrever todas as histórias das tarefas do board do Github para o board do Figma, onde serão feitos os vínculos com a EAP e o norteamento de prioridades.

## **Escopo**

- [x] Transcrever as histórias da Central de Informações

## Observações
https://www.figma.com/file/ab0B64s5aAxB79NLyhZuX0/Inception-Pr%C3%A9-Oficina-ESP-2022

**Comment by elpadrejorge** [comment]
Todas as histórias foram transcritas. O modelo do designlab foi disponibilizado para o restante dos times realizarem suas transcrições e foram criadas boards para cada time com cards modelo.

**Comment by RaniGub** [comment]
Escopo de tarefa editado, será criada uma tarefa para cada transcrição/revisão.

**Comment by caldy94** [comment]
Tarefa atualizada no link acima!

**Comment by elpadrejorge** [comment]
Board da Central de Informações transcrito.

Link no figma

https://www.figma.com/file/iAsGWDwzboG64K2j6H28UE/Transcri%C3%A7%C3%A3o-das-issues-do-board-do-GitHub-da-Central-de-Informa%C3%A7%C3%B5es-27.04.2022?node-id=0%3A1

**Comment by elpadrejorge** [comment]
@pauloamoreira @caldy94 @RaniGub Transferi todos os boards para a pasta Inceptions, dentro do time DesignLab no Figma, para tira-las dos meus rascunhos.

**Comment by RaniGub** [comment]
Escopo da tarefa editado.
