### ISSUE TITLE
Transcrição das issues do board do GitHub das Narrativas

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#297]
@caldy94 commented on [Fri Apr 22 2022](https://github.com/EscolaDeSaudePublica/isus-app/issues/723)

### **Objetivo**
Como designer
Quero transcrever issues pendentes do board das narrativas
Para melhor organizar o ambiente de trabalho

### **Contexto**
Existem issues desatualizadas e/ou não feitas presentes nos boards de cada equipe

### **Escopo**
 Analisar issues pendentes
 Encontrar tarefas incompletas ou sem escopo
 Verificar se existem tarefas já realizadas e não marcadas como feitas.

### **Mais informações:**
https://www.figma.com/file/ez1nxBhlidk7LEQuApFQdq/Transcri%C3%A7%C3%A3o-das-issues-do-board-do-GitHub---NARRATIVAS?node-id=0%3A1

---

@caldy94 commented on [Fri Apr 22 2022](https://github.com/EscolaDeSaudePublica/isus-app/issues/723#issuecomment-1106501830)

Pareamento marcado com @Clarisse1983 na segunda feira, dia 25, às 15:00h.

---

@caldy94 commented on [Fri Apr 22 2022](https://github.com/EscolaDeSaudePublica/isus-app/issues/723#issuecomment-1106733162)

Board passada para figma, falta apenas revisão de @Clarisse1983

**Comment by RaniGub** [comment]
Mesma tarefa #723 do repositório do iSUS. Foi movida e apagada de lá.

**Comment by RaniGub** [comment]
@caldy94 alinhe com o Paulo essa atividade. Conversei com ele hoje. Dê prioridade a ela.

**Comment by pauloamoreira** [comment]
.o progresso dessa tarefa deve ser acompanhado na issue #300
