### ISSUE TITLE
Transcrição/revisão de histórias das tarefas do iSUS

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#298]
## **Objetivo**

**Como designer
**Quero mediar a transcrição das histórias do iSUS no Figma
**Para Realizar o match das histórias do GitHub com as histórias mapeadas na Inception.

## **Contexto**

Para clarificar a EAP original do Projeto Mapas e Soluções e dar apoio à tomada de decisão de quais passos devem ser tomadas pelos times do Felicilab, será realizada uma "engenharia reversa" através de uma inception ao longo do mês de abril/22. Os momentos visam a criação e organização de histórias para planejamento dos times. Nesse contexto, se faz necessário transcrever todas as histórias das tarefas do board do Github para o board do Figma, onde serão feitos os vínculos com a EAP e o norteamento de prioridades.

## **Escopo**

- [ ] Transcrever as histórias do iSUS

## Observações
https://www.figma.com/file/ab0B64s5aAxB79NLyhZuX0/Inception-Pr%C3%A9-Oficina-ESP-2022

**Comment by pauloamoreira** [comment]
Uma reunião com @Laysacunha para o dia 28.04.2022, que tinha como propósito a colaboramos na transcrição das tarefas para o figma, não pode ser realizada. Permanecemos no aguardo da indicação de novo dia e horário para darmos prosseguimento a essa análise e transcrição.

**Comment by RaniGub** [comment]
Aguardando feedback da Laysa para momento oportuno.

**Comment by pauloamoreira** [comment]
@RaniGub essa tarefa passará a ser executada pelo @elpadrejorge e pela @caldy94 ?
