### ISSUE TITLE
Apoiar a Transcrição/revisão de histórias das tarefas do Mapa

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#299]
## **Objetivo**

**Como** designer
**Quero** mediar a transcrição das histórias do Mapa da Saúde no Figma
**Para** Realizar o match das histórias do GitHub com as histórias mapeadas na Inception.

## **Contexto**

Para clarificar a EAP original do Projeto Mapas e Soluções e dar apoio à tomada de decisão de quais passos devem ser tomadas pelos times do Felicilab, será realizada uma "engenharia reversa" através de uma inception ao longo do mês de abril/22. Os momentos visam a criação e organização de histórias para planejamento dos times. Nesse contexto, se faz necessário transcrever todas as histórias das tarefas do board do Github para o board do Figma, onde serão feitos os vínculos com a EAP e o norteamento de prioridades.

## **Escopo**

- [x] Transcrever as histórias do Mapa

## Observações
https://www.figma.com/file/ab0B64s5aAxB79NLyhZuX0/Inception-Pr%C3%A9-Oficina-ESP-2022

**Comment by elpadrejorge** [comment]
Issues organizadas, etiquetadas e já alocadas no board do figma. Aguardando revisão. @RaniGub @pauloamoreira
