### ISSUE TITLE
#DesignSprint para Criação de Fluxo e Telas do Sistema de Seleções/Editais

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/DesignLab#3]

**Comment by victorMagalhaesPacheco** [comment]
Fluxo seleções.
https://drive.google.com/file/d/1e23cq0XdOAV_ufCYDWLJQGRAdvjroY1I/view?usp=sharing

**Comment by drmarcos** [comment]
Migrado para o Trello: https://trello.com/c/PtvCQ3c7
