### ISSUE TITLE
Apoiar a Transcrição/revisão de histórias do time de Narrativas

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#300]
## **Objetivo**

**Como designer
**Quero mediar a transcrição das histórias do time de Narrativas no Figma
**Para Realizar o match das histórias do GitHub com as histórias mapeadas na Inception.

## **Contexto**

Para clarificar a EAP original do Projeto Mapas e Soluções e dar apoio à tomada de decisão de quais passos devem ser tomadas pelos times do Felicilab, será realizada uma "engenharia reversa" através de uma inception ao longo do mês de abril/22. Os momentos visam a criação e organização de histórias para planejamento dos times. Nesse contexto, se faz necessário transcrever todas as histórias das tarefas do board do Github para o board do Figma, onde serão feitos os vínculos com a EAP e o norteamento de prioridades.

## **Escopo**

- [x] Transcrever as histórias das Narrativas

## Observações
https://www.figma.com/file/ab0B64s5aAxB79NLyhZuX0/Inception-Pr%C3%A9-Oficina-ESP-2022

**Comment by caldy94** [comment]
Tarefa concluída.

**Comment by pauloamoreira** [comment]
O escopo dessa tarefa correspondia, originalmente, a tarefa #723, do repositório iSUS-App, mas foi fechada lá e copiada para o repositório do DesignLab, com a atribuição de #297. O progresso dessa atividade, no entanto, deve ser acompanhado aqui.
