### ISSUE TITLE
Artigo sobre oficinas Design de Serviços para Construção de Políticas Públicas

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#304]
## **Objetivo**

**Como** designer do DesignLab
**Quero** escrever um artigo  
**Para** divulgar o processo e os resultados das oficinas de Design de Serviços para Construção de Políticas Públicas.

## **Contexto**
- Foi solicitado, por Erica Pinho (Narrativas), ao designer do DesignLab que facilitou as oficinas de aplicação de Árvores de Problemas em encontros de construção das Políticas Públicas de Saúde de Pessoa com Deficiência; Prevenção e Proteção de Mulheres, Crianças e Adolescentes Vítimas de Violência e Transplantes ([#225](https://github.com/EscolaDeSaudePublica/DesignLab/issues/225)); que produzisse um artigo curto (2.300 caracteres) com o relato dessa experiência, para publicação em jornal.

## **Escopo**

- [x] Elaborar memorial e reunião de materiais
- [x] Escrever primeira versão do artigo
- [x] Realizar revisão ortográfica
- [x] Submeter texto à análise de Stakeholders
- [x] Realizar aperfeiçoamentos e finalizações na versão final do artigo
- [x] Disponibilizar texto

## **Critérios de Aceitação**

- [x] Relato de Experiência Publicizado  
**Dado que** sou leitor do jornal onde o artigo será publicado  
**Quando** ler o jornal em questão  
**então** terei acesso ao relato da experiência das oficinas de design de serviços para Construção de Políticas Públicas realizadas pelo Felicilab/ESP.

## Observações
Links para o texto: https://docs.google.com/document/d/1WbmWdUws0Cf42zhYUeUGPWndAAQErln3efOacpcgV1Y/edit?usp=sharing

**Comment by RaniGub** [comment]
Oi @pauloamoreira, aqui já foi né?

**Comment by pauloamoreira** [comment]
@RaniGub  sim. pode fechar.
