### ISSUE TITLE
Criar sumário para a Board da Inception no Figma

### ISSUE THREAD

**Issue by caldy94** [EscolaDeSaudePublica/DesignLab#315]
## **Objetivo**

**Como** usuário 
**Quero** criar um sumário interativo na Board da Inception
**Para** que eu me localize dentro da estrutura, conseguindo acompanhar o processo de inception.

## **Contexto**

- A Board da Inception no Figma encontra-se organizada de forma não linear e com muitos detalhes.

## **Escopo**

- [ ] Organizar as etapas em ordem
- [ ] Criar elementos clicáveis para interação, levando o usuário na etapa que desejar.

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

## Observações
Links de apoio e informações adicionais

**Comment by RaniGub** [comment]
Tarefa encerrada, não há necessidade do esforço do time de Design nesse momento.
