### ISSUE TITLE
Criar Board de relacionamento entre a projeção de entregas da inception e a EAP do Mapa e Soluções

### ISSUE THREAD

**Issue by caldy94** [EscolaDeSaudePublica/DesignLab#316]
## **Objetivo**

**Como** designer  
**Quero** criar a board que mostre o relacionamento entre a projeção de entregas da inception e a EAP do Mapa e Soluções
**Para** tornar possível visualizar quais tarefas do mapa já foram realizadas.

## **Contexto**

Considerando a tabela da EAP na Inception Mãe, é necessário transcrever em novo board considerando informações da EAP do projeto Mapa.

## **Escopo**

- [x] organizar board para o time de projetos

## Observações
Link 1:  https://gitmind.com/app/doc/dd0a319ec96d8265b704771a75892688
Link 2:  https://www.figma.com/file/mCtw92iwGlKJkG5mrbH8XY/Relacionamento-entre-a-proje%C3%A7%C3%A3o-de-entregas-da-inception-e-a-EAP-do-Mapa-e-Solu%C3%A7%C3%B5es?node-id=0%3A1

**Comment by RaniGub** [comment]
@caldy94 você pode atualizar o escopo dos passos dessa tarefa?

**Comment by caldy94** [comment]
A board está criada, mas gostaria que o grupo validasse o que cada entrega oferece (marcar os quadrados de azul), porque eu sozinha não consigo fazer essa avaliação. @RaniGub, @pauloamoreira, @elpadrejorge

**Comment by RaniGub** [comment]
Revisado, indicações realizadas.

**Comment by caldy94** [comment]
Board refeita, aguardo algum feedback de @RaniGub

**Comment by RaniGub** [comment]
@caldy94 quando diminuímos o tamanho do esquema... as bolinhas com a numeração da tarefa não diminuíram proporcionalmente e acabaram sumindo. Você pode diminuir manualmente o tamanho delas para voltarem a aparecer? Obrigado.

**Comment by caldy94** [comment]
Oi Rani, os números das bolinhas sumiram, quando fui mexer já estava assim...

**Comment by caldy94** [comment]
Consegui enumerar, esperando feedback do Rani
