### ISSUE TITLE
15. Estruturar o formato da Mandala de Governança

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#321]
## **Objetivo**

**Como** designer de experiência
**Quero** estruturar o formato da Mandala de Governança
**Para** integrar o processo de estruturação de informações

## **Contexto**

- Por ocasião da proximidade da realização das oficinas de Design de Serviços na ESP/CE, se faz necessário realizar pré-oficinas para a aplicação de Árvores de Problemas nas áreas: **Educação e Extensão, Desenvolvimento Educacional, Inteligência em Saúde, Pesquisa em Saúde, Governança em Gestão e Inovação e Tecnologia**, de modo a coletar informações que irão colaborar para as atividades previstas na oficina.

## **Escopo**

- [ ] 15. Estruturar o formato da Mandala de Governança

## Observações
board do figma em processo de construção: https://www.figma.com/file/WqnQDigTVM6tME4PRSdReP/Planejamento-Pr%C3%A9-oficina-e-Oficina---maio-2022?node-id=4%3A413

**Comment by pauloamoreira** [comment]
@RaniGub em virtude da decisão de que a Mandala de Governança não fará parte das pré-oficinas, convém encerrar essa tarefa (não é mais pertinente).

**Comment by RaniGub** [comment]
Paulo, discutimos isso na sexta passada e achamos pertinente voltar com a compreensão se é ou não necessário em nosso próximo encontro.
