### ISSUE TITLE
Criar landing page do Felicilab

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/DesignLab#33]
Criar uma página única para conter informações básicas sobre o Felicilab.

- [ ] fazer layout visual
- [ ] codificar no WP
- [ ] inserir conteúdos de texto

**Comment by uira** [comment]
@danielgula Fazer layout oficial, troca por escolher layou base do Divi 

https://www.elegantthemes.com/layouts/

**Comment by wforte88** [comment]
Demanda tratada na tarefa https://github.com/EscolaDeSaudePublica/isus-app/issues/440
