### ISSUE TITLE
PRODUÇÃO GRÁFICA | Oficina de Design de Serviços

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/DesignLab#339]
## Objetivo

Como pessoa produtora da Oficina de Design ESP
Quero acompanhar a produção gráfica 
Para garantir que o momento seja realizado considerando todos os pontos

## Contexto

Para o evento serão necessários  materiais gráficos como banners, adesivos, e kits de brindes.  

## Escopo
- [x] Elaboração da arte para aplicação nos brindes e outros materiais (Felicilab/ASCOM);
- [x] Banner e adesivos (elaboração, orçamento e produção);
- [x] Kits de brindes (definição de itens, orçamento, produção);

**Comment by marameida** [comment]
Plalnilha de orçamentos e custos:
https://docs.google.com/spreadsheets/d/1sh7vz-NmG8WpDKReqPassJ4zY5J5UAub/edit#gid=2113195094

**Comment by RaniGub** [comment]
@marameida chegue no Uirá para saber se já tem alguma deliberação sobre esses materiais. Ia pedir para você especificar melhor o tópico 3 e tirar uma dúvida sobre o 1.

**Comment by marameida** [comment]
Sim. Reforçado com @uira e Nicolas sobre os próximos encaminhamentos necessários. Conversado com @elpadrejorge sobre deliberação de artes (para kits, banner e adesivos) junto a ASCOM.

**Comment by marameida** [comment]
Gostaria de alinhar com o time sobre a solicitação desse material e confecção das blusas, visto que o pedido deve ser feito com antecedência.
https://docs.google.com/spreadsheets/d/1sh7vz-NmG8WpDKReqPassJ4zY5J5UAub/edit#gid=2113195094

**Comment by marameida** [comment]
Socitado ao @elpadrejorge material para impressão com identificação visual da oficina (banner, adesivos e logo personalizada para itens dos kits).

**Comment by RaniGub** [comment]
@marameida orçar kit simples (caneta e bloco de anotações) e verificar com Uirá a possibilidade. Solicitar a arte do banner para o @elpadrejorge

**Comment by elpadrejorge** [comment]
Artes para banner, cartaz, crachá e bloco de notas criadas. Banner e cartaz já foram refinados e aprovados na última reunião da Oficina. Resta aprovação do bloco e  crachá.

**Comment by marameida** [comment]
Solicitado à Selma itens e quantitativos dos materiais para Oficina de Design. Reforçaremos o pedido com a nova proposta de logo (Felicilab/"Design que salva vidas")

**Comment by RaniGub** [comment]
@elpadrejorge apresentou a arte da camiseta que foi compartilhada no grupo da oficina e validado. A solução cromáticas dos crachás (áreas) será trabalhada na tarde desta terça-feira 14/06/22.

**Comment by marameida** [comment]
Reforçado com Selma sobre material a ser produzido. Ainda no aguardo por retorno.

**Comment by marameida** [comment]
Enviadas para Lucinha, seguindo orientação da Selma,  logos e descrição dos itens para cotação com gráfica.

**Comment by marameida** [comment]
Logos finais enviadas para Lucinha. A mesma confirmou que já encaminhou para gráfica. Solicitada também a abertura de processo via DITEC, conforme pedido do setor.

**Comment by marameida** [comment]
Material sendo produzido. No aguardo por recebimento.

**Comment by marameida** [comment]
Acompanhamento de processos junto DITEC e Lucinha (material gráfico).

**Comment by RaniGub** [comment]
@marameida informou que as blusas serão entregues hoje. Acerca dos kits, Lucinha ficou de avisar assim que chegassem.

**Comment by marameida** [comment]
Atividades contempladas.
