### ISSUE TITLE
LOGÍSTICA DE ORGANIZAÇÃO | Oficina de Design de Serviços

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/DesignLab#340]
## Objetivo

Como pessoa produtora da Oficina de Design ESP
Quero acompanhar a logística de organização
Para garantir que o momento seja realizado considerando todos os pontos

## Contexto

A Logística de Organização do Evento incluirá levantamento de materiais, frequências, coffee break, mapeamento do local, etc)

Para o evento serão necessários materiais gráficos como banners, adesivos, e kits de brindes.  

## Escopo
- [x] Lista de materiais necessários analógico para chegagem antes da oficina (elaboração de check-lists);
- [x] Elaboração e impressão de frequências;
- [x] Solicitação de cofee break (pré-oficinas e oficina final);
- [x] Fechamento com local (contato, visita, ofício)
- [x] Lista de Inscritos
- [ ] Frequência iSUS

**Comment by marameida** [comment]
Plalnilha de orçamentos e custos:
https://docs.google.com/spreadsheets/d/1sh7vz-NmG8WpDKReqPassJ4zY5J5UAub/edit#gid=2113195094

**Comment by marameida** [comment]
Ofício de formalização do espaço :
https://docs.google.com/document/d/1URp_zUPw5oERAAmkfY4rxKlvsZ85PMOmxsWpp47CtTE/edit

**Comment by RaniGub** [comment]
Bom dia @marameida, quais destas tarefas já podemos dar baixa?

**Comment by marameida** [comment]
Atualizado check list no escopo.

**Comment by marameida** [comment]
Ofício enviado para BECE.
https://docs.google.com/document/d/1QnEs-LowWltHN7mLcQhulvjUo9VAI-o_wccwBG75s2I/edit

**Comment by marameida** [comment]
Coffe Break solcitado novamente. Redirecionado recurso. No aguardo por liberação.

**Comment by RaniGub** [comment]
Experiência e telas para frequência no iSUS disponibilizada na issue #761. Pareamento com Ericson realizada em 15/06/2022.

**Comment by marameida** [comment]
Analisando possibilidade de parceria com empresa de produtos nutricionais para disponilização de kits para sorteios.

**Comment by marameida** [comment]
Check-list para evento:
https://docs.google.com/spreadsheets/d/17wQK1RaFrTgY5-9ZU9uclhcI98YheufsaRQXY4l0KgU/edit#gid=0

**Comment by marameida** [comment]
Lista de inscritos até o momento:
https://drive.google.com/drive/u/0/folders/1LLtElpa0p02jyr570oaCBZBtRSioH_tJ[https://app.zenhub.com/files/235795051/e2209d98-c321-4358-a759-4ac29bbfa0c7/download]

(https://app.zenhub.com/files/235795051/e2209d98-c321-4358-a759-4ac29bbfa0c7/download)

**Comment by marameida** [comment]
Acompanhamento de processos junto DITEC e Lucinha (coffee break).

**Comment by marameida** [comment]
Check-list atualizado:
https://docs.google.com/spreadsheets/d/17wQK1RaFrTgY5-9ZU9uclhcI98YheufsaRQXY4l0KgU/edit#gid=0

**Comment by marameida** [comment]
Frequencia foi feita com assinaturas presenciais e transferida para planilha em google drive.
https://docs.google.com/spreadsheets/d/1LWbwHcFf0_-w1XI99a2q2WhfLR1cvLqFTs0-NiPEIb0/edit#gid=561097855

**Comment by marameida** [comment]
Atividades encerradas.
