### ISSUE TITLE
COMUNICAÇÃO/DIVULGAÇÃO | Oficina de Design de Serviços

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/DesignLab#341]
## Objetivo

Como pessoa produtora da Oficina de Design ESP
Quero acompanhar a comunicação/divulgação
Para garantir que o momento seja realizado considerando todos os pontos

## Contexto

Para o evento serão necessários formulário de inscrição, grupos de comunicação, convites e demais informes.

## Escopo
- [x] Formulário de pré-inscrição (elaboração, validação, divulgação);
- [x] Informar as pessoas selecionadas sobre o início das oficinas;
- [x] Grupos de Comunicação Whatsapp (pós deferimento do mapeamento de intenção preenchido pelos colaboradores como oportunidade no Mapas;
- [x] Formulário de avaliação;

**Comment by marameida** [comment]
Formulário de pré-inscrição - Já validado pelo setor de Narrativas (será disponibilizado como oportunidade no Mapas:
https://docs.google.com/document/d/1qOC4ZrlFTAQriA95Ad5WDp1VuEiplYT3CNNchwL-W5I/edit

**Comment by marameida** [comment]
Formulário de avaliação - necessário refinar com Paulo
https://docs.google.com/forms/d/1MN6LIvpir2YsbUKy3yNWW1SUYhkN3mjdJy_PLmwJWH0/edit

**Comment by marameida** [comment]
Formulário de pré-inscrição cadastrado no Mapas. Por gentileza testem e me dêem "ok" para eu divulgar. 
https://mapa.sus.ce.gov.br/oportunidade/283/#/tab=main-content

**Comment by marameida** [comment]
Lista de Contatos/frequência para divulgação:
https://docs.google.com/spreadsheets/d/18VhP1rhvofh0hgnjVYz7-YjLwMBpRtXKuCq3RJVpudU/edit#gid=0

**Comment by RaniGub** [comment]
Bom dia @marameida, como tá o status dessas tarefas?

**Comment by marameida** [comment]
Oi @RaniGub disparada divulgação de link e vídeo para pré-inscrições. Alinhado com ASCOM e com pessoas estratégicas de cada setor.

**Comment by marameida** [comment]
Organizadas evidências das pré-oficinas (fotos e vídeos) em drive do Design:
https://drive.google.com/drive/u/0/folders/1ZlK4GA5I5MqrPy_mIdJpLF-LQ7GAyajM

**Comment by marameida** [comment]
Enviado email convite de incrição para contatos que participaram das pré-oficinas.

**Comment by marameida** [comment]
ASCOM estará divulgando as pré-inscrições hoje por email, intranet e grupos gerais.

**Comment by marameida** [comment]
Até o momento 36 inscrições.

**Comment by marameida** [comment]
Iniciada Edição do Formulário de Avaliação da Oficina:
https://docs.google.com/forms/d/1fDKAN4Bxvgzlvk7FT7WI2CiTPpcf6OXjkgoznZ3CjKc/edit
@pauloamoreira

**Comment by RaniGub** [comment]
@marameida fale com o @elpadrejorge para atualizar o banner do formulário de feeedback

**Comment by RaniGub** [comment]
Aguardar o fim das inscrições para criar o gurpo de whatsapp. Já li o formulário e acho as perguntas adequadas. @marameida você precisa só adaptar as áreas e conversar com a @Clarisse1983 para validação final.

**Comment by marameida** [comment]
Atualizando Formulário de Avaliação:
https://docs.google.com/forms/d/1fDKAN4Bxvgzlvk7FT7WI2CiTPpcf6OXjkgoznZ3CjKc/edit

**Comment by marameida** [comment]
Até o momento: 49 inscrições para Oficina de Design de Serviços.

**Comment by marameida** [comment]
Relatório de respostas referentes às inscrições:
https://docs.google.com/spreadsheets/d/1x14JySvHUDuPCDNZUNw4l69OrY4iLXiE/edit#gid=1756361182

**Comment by marameida** [comment]
Divulgado percentuais de inscrições por setores, reforçando incremento das pré-inscrições.

**Comment by marameida** [comment]
Formulário de avaliação atualizado. vamos refinar fechamento @pauloamoreira
https://docs.google.com/forms/d/1fDKAN4Bxvgzlvk7FT7WI2CiTPpcf6OXjkgoznZ3CjKc/edit

**Comment by RaniGub** [comment]
@elpadrejorge é possível você fazer duas coisas para atender uma demanda da Oficina no iSUS?
1- Banner de 395 x 130px. Genérico.
2- Topo de 411 x 235px para home de frequência da oficina. Genérico.

**Comment by marameida** [comment]
Reforçado pré-inscrição com os setores. Entregue banner com QR CODE e anexado cartaz nos murais da escola. Solicitado reforço de divulgação com ASCOM. Até o momento 59 inscritos:

**Comment by RaniGub** [comment]
![Captura de Tela 2022-06-15 às 13 57 45](https://user-images.githubusercontent.com/79097920/173883693-18490699-600b-4708-b1a3-d977c3cc3c23.png)
@marameida podemos padronizar e tirar /ESP das opções

**Comment by marameida** [comment]
Inscrições fechadas temporariamente para definição de destino das vagas remanescentes. Elaborada lista de aguardo: https://docs.google.com/spreadsheets/d/119ncCff7QEzID5KGqqi2g7zIFoLNzmvqEOF942_Agic/edit#gid=0

**Comment by marameida** [comment]
Podemos criar o grupo de whatsapp com as pessoas já inscritas? @uira e @RaniGub?

**Comment by RaniGub** [comment]
@marameida como será a curadoria das pessoas que já se inscreveram? Aquelas que com certeza irão participar já poderiam ser incluídas no grupo. Mas é bom alinhar com o Uirá e Clarisse. Ai evitamos de criar expectativa em pessoas que talvez não estejam no grupo das que vão participar.  Vamos adicionando as demais depois.

**Comment by marameida** [comment]
Atividade contemplada. Formulário pós avaliação será disponibilizado em grupo posteriormente.
