### ISSUE TITLE
Acompanhar a integração da Oficina de Design de Serviços com o aplicativo ISUS

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/DesignLab#342]
## Objetivo

Como pessoa produtora da Oficina de Design ESP
Quero acompanhar a integração da oficina com o ISUS
Para garantir que a frequência dos participantes esteja vinculada ao aplicativo;

## Contexto
Deseja-se que o participante do evento possa confirmar sua frequencia através do aplicativo.

## Escopo
- [x] Resgatar formato utilizado em evento anterior;
- [x] Alinhar com equipe do ISUS a logística necessária;

**Comment by marameida** [comment]
Agendada reunião com equipe do ISUS para refinamento e encaminhamento desta demanda.
Segunda dia 13/06 às 9:15h
@RaniGub @elpadrejorge @Laysacunha

**Comment by RaniGub** [comment]
@marameida vou encerrar essa tarefa. O acompanhamento dela está na #340. Já disponibilizei a experiência e telas. Falta validar uma regra com o Uirá.
