### ISSUE TITLE
Desenhar o fluxo de relacionamentos entre a oportunidade criada no Mapa (cursos) e a integração com o Sagu

### ISSUE THREAD

**Issue by ricardopoppi** [EscolaDeSaudePublica/DesignLab#346]
Issue 1 - Fluxo de jornada da migração de inscritos no MAPA para cadastramento de pf no SAGU
- [x] Compreender a jornada para validação para cadastramento de pf no SAGU (Conversa com Ana Xenofonte e/ou pessoa gestora de curso.)
Campos obrigatórios: 

- Nome ✅ (obg. API)
- E-mail ✅
- Endereço ✅
- Sexo (obg. API)
- Estado civil 
- Categoria profissional 
- Tipo de vinculo 
- CPF ✅ (obg. API)
- RG ✅ 
- Data de nascimento ✅

Obs:  Check em verde são os campos obrigatórios na interface do SAGU e os "obg. API" exigidos apenas a nível de API

- [x] Validar com a área a retirada da obrigatoriedade do sexo e a adição de outro campo de interesse em comum entre MAPA e SAGU.
Obs: Nome e CPF foram considerados obrigatórios e retirar a obrigatoriedade de RG e SEXO, para que não sejam feitas migrações inconsistentes. Melhor gerar falta de dados do que inconsistencias.

Issue 2 - Fluxo de relacionamento entre as informações dos selecionados na oportunidades do Mapa e o Sagu para cadastramento de pf no SAGU
- [x] Desenhar o fluxo de relacionamentos entre a oportunidade criada no Mapa (cursos) e a integração com o Sagu. (https://github.com/EscolaDeSaudePublica/DesignLab/issues/346)

FLUXO: https://www.figma.com/file/Joo00AB0Y4sdYHq24oqPJr/Integra%C3%A7%C3%A3o-MAPA---SAGU?node-id=0%3A1

Issue 3 - Entrega proposta do botão no MAPA para migração de alunos a serem cadastrados como pf no SAGU

- [x] Desenhar proposta de tela/botão

PROTÓTIPO: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=3646%3A3658

## **Escopo Narrativas**

- [ ] Análise de narrativas

**Comment by matheuscpl** [comment]
@carolynemaciente Adicionei aqui o fluxo que desenhamos da integração 
https://www.figma.com/file/Joo00AB0Y4sdYHq24oqPJr/Integra%C3%A7%C3%A3o-MAPA---SAGU?node-id=0%3A1

**Comment by RaniGub** [comment]
@ericabpinho a experiência já foi disponibilizada, falta análise do time de narrativas.

**Comment by ericabpinho** [comment]
Foi realizada a análise de narrativas, sem indicações para alterações do texto. 
Contudo, tenho algumas dúvidas fora do escopo da issue, a respeito das categorias "status das inscrições". Essas categorias foram definidas ao longo do processo, ou anteriormente, pela própria secretaria escolar? 

Outra questão: essa etapa atual tem testes de usabilidade previstos? 
@victorMagalhaesPacheco @ricardopoppi

**Comment by ricardopoppi** [comment]
@ericabpinho obrigado pelo feedback. Sobre as categorias status das inscrições, como é uma funcionalidade que já está em produção algum tempo no mapa, sugiro que caso façamos algum ajuste seja um nova issue de análise ux com narrativas e depois se houver necessidade de alguma implementação de mudança uma nova issue para desenvolvimento que vamos atrelar a uma épica de melhorias e resolução de bugs
