### ISSUE TITLE
Ambiente Virtual da Oficina de Design de Serviços da ESP | Pós-Oficina

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#349]
## **Objetivo**

**Como** designer
**Quero** disponibilizar as informações no ambiente virtual
**Para** possibilitar a consulta pelos colaboradores da ESP

## **Contexto**
É preciso disponibilizar os achados da Oficina de Design de Serviços da ESP

## **Escopo - Sem marcação**

**Atualização de conteúdos**
   - Revisão geral (organização de conteúdos não mais necessários)
   - Revisar os objetivos disponibilizados no site (verificar apresentação e figma)

**Depoimentos**
   - Revisar a estratégia de exibição dos depoimentos
   - Atualizar depoimentos
   - Analisar depoimentos dos feedbacks

**Metodologia**
   - Disponibilizar metodologia da flecha (estudar formato apropriado com descrição das etapas)
- Estudar estratégia de exibição da metodologia conectada com os achados
- Disponibilizar clusters de todos os problemas (identificar os trabalhados na oficina)

**Personas**
- Disponibilização de espaço com as fichas e expectativas de entregas

## Observações
[Links de apoio e informações adicionais
](https://www.figma.com/file/5FFxEuc7eI7tQlfSc7xYQ7/Fluxo-de-Produtos?node-id=0%3A1)

**Comment by RaniGub** [comment]
Oi Jorge, por favor, você pode criar essas issues:

Metodologia
Disponibilizar metodologia da flecha (estudar formato apropriado com descrição das etapas)
Estudar estratégia de exibição da metodologia conectada com os achados
Disponibilizar clusters de todos os problemas (identificar os trabalhados na oficina)

**Comment by RaniGub** [comment]
Para visualização da previsão de entregas vamos criar uma seção nova.

**Comment by RaniGub** [comment]
Para finalização: definição de CA dos participantes para emissão de declaração pela secretaria acadêmica e divulgação na página. @RaniGub

**Comment by RaniGub** [comment]
Faltam duas coisas para finalizar o Épico:
1- Verificar com Daniel e TI sobre acesso com senha no período de defeso eleitoral
2- Aguardar envio pelo @ricardopoppi das expectativas de entrega das histórias mapeadas na oficina com a classificação do tipo: 1) Precisamos de um novo projeto para atender; 2) Será atendido no quarto trimestre de 2022; e, 3) Em desenvolvimento, entrega prevista para XX/2022

**Comment by RaniGub** [comment]
Encaminhamentos:
1 - Elon da Ascom validou o acesso ao site da oficina durante o Defeso. Estamos realizando as adaptações sugeridas e depois será feita uma nova avaliação para liberação do link.
2- Em conversa com o @ricardopoppi foi acordado que o time de design irá disponibilizar as legendas de categorização das entregas para que o time de produtos faça a relação. Tão logo isso esteja pronto, o link será disponibilizado.

**Comment by RaniGub** [comment]
@ricardopoppi criei um espaço para você arrastar as histórias para estimativa dos prazos de entrega. Legendas:
Verde - Em desenvolvimento (Temos certeza da data)
Amarela - Em análise de complexidade (A estimativa pode mudar)
Laranja - Aguardando definição de recurso (A ESP quer a entrega, mas não sabemos ao certo do recurso)
Vermelho - Precisamos de um novo projeto para atender (Não temos como fazer isso agora)

Coloquei uma observação: *O tempo estimado da entrega pode variar na medida em que avançamos no refinamento ou desenvolvimento da solução, pois novas camadas de complexidade não previstas anteriormente podem surgir.

Quando concluir sinalize pra gente pfv... ao lado do quadro deixei uma sugestão de apresentação no site para refinar com o @elpadrejorge

![Captura de tela 2022-09-09 143824](https://user-images.githubusercontent.com/79097920/189412664-011a6707-de7c-4cbc-b754-a71c816c0a7b.png)

**Comment by ricardopoppi** [comment]
@RaniGub @elpadrejorge finalizei a distribuição das histórias das oficina lá no board, usando esse espaço que foi criado.

Tudo que tem a ver com a parte de gestão dos alunos eu coloquei como previsão esse ano pois estamos refinando justamente agora para poder fazer uma entrega este ano para a residência. Tudo que tem relação com o portal do aluno, como perdemos os recursos do projeto do CETRED, programei para o próximo semestre.
Ficou na parte vermelha aquilo que nem começamos ainda/nem está no nosso radar, que aí não dá pra precisar nem pro próximo ano, pois depende de novas iniciativas/projetos.

Qq dúvida estou a disposição, se precisar melhorar algo, só me chamar

**Comment by RaniGub** [comment]
Épico finalizado.
