### ISSUE TITLE
 Coleta de depoimentos da Oficina de Design da ESP

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#353]
## **Objetivo**

**Como** designer
**Quero** colher os depoimentos das pessoas da produção da oficina de design da ESP
**Para** disponibilizar no ambiente virtual da oficina

## **Contexto**

- O site da Oficina foi eleito como o ambiente virtual que receberá todos os registros, achados e desdobramentos resultantes dos encontros das pré-oficinas e dos três dias de oficina. O site precisará conter todas as informações sobre as pessoas responsáveis pela sua produção. Estas informações precisam ser exibidas de forma otimizada e para isso foi pensado em exibir um depoimento de cada membro da produção na página principal, em sua última seção, com fotos, nomes, cargos e depoimento.

## **Escopo**
- Coleta de depoimentos
- [x] Verificar com Narrativas quais já existem
- [x] Depoimento Paulo
- [x] Depoimento Rani
- [x] Depoimento Uirá
- [x] Depoimento Jorge
- [x] Depoimento Matheus
- [x] Depoimento Poppi
- [x] Depoimento Nazka
- [x] Depoimento Gabriela Marques
- [x] Depoimento Washington
- [x] Depoimento Edmilson
- [x] Depoimento Samara
- [x] Depoimento Clarisse
- [x] Depoimento Érica
- [x] Depoimento Marcelo
- [x] Depoimento Alice

## **Critérios de Aceitação**

**Dado que** o visitante acesse ao site
**Quando** for visualizada a seção de depoimentos dos membros da produção da oficina
**então** estes depoimentos são exibidos de acordo com a melhor experiência possível em desktop e mobile

## Observações
https://sus.ce.gov.br/felicilab/?page_id=3644&preview=true

**Comment by RaniGub** [comment]
Oi @Clarisse1983 o Washington deu um depoimento ao @edmirandajr sobre a Oficina no grupo da narrativas. A gente queria um breve recorte do áudio para usar como depoimento nessa atividade.

**Comment by RaniGub** [comment]
Oi @Clarisse1983 vc pode alinhar com o @elpadrejorge os depoimentos que faltam?

**Comment by RaniGub** [comment]
Ficha Técnica (dos que faltavam ou que precisam ser alterados).

Érica Pinho - Cobertura e Divulgação
Gabriela Marques - Metodologia e Facilitação
Jorge Godoy - Metodologia, Facilitação e Ambiente Virtual
Ranielder Freitas - Coordenação Metodológica e Coordenação de Geral
Uirá Porã - Metodologia e Coordenação Geral
Nazka Fernandes - Metodologia e Facilitação
Gabriela Calderón - Produção
Paulo Amoreira - Metodologia e Facilitação
Matheus Campelo - Facilitação
Ricardo Poppi - Facilitação
Edmilson Miranda - Facilitação, Cobertura e Divulgação
Washington Forte - Metodologia e Facilitação
Colocar depoimento do Marcelo em algum lugar (Governança e Gestão(?))

**Comment by elpadrejorge** [comment]
As funções foram atualizadas na ficha técnica. Faltam depoimentos da Alice, Marcelo, Washington, Edmilson, Poppi e Matheus.

**Comment by RaniGub** [comment]
Bom dia gente, faltam alguns depoimentos para a gente finalizar essa tarefa.
- Matheus (consigo pegar hoje após a daily)
- Poppi (aguardar recuperação da covid)
- Edmilson (@edmirandajr)
- Marcelo (@Clarisse1983 por gentileza, é possível fazer uma montagem com base no depoimento do Marcelo?)
- Alice (@elpadrejorge vamos tentar coletar algo nesta terça 12/07)

**Comment by RaniGub** [comment]
Bom dia gente, faltam alguns depoimentos para a gente finalizar essa tarefa.
- Poppi
- Edmilson

**Comment by elpadrejorge** [comment]
Depoimentos inseridos no ambiente. Poppi já contactado. Edmilson está de viagem de volta à Portugal, mas informou que assim que puder envia.

**Comment by RaniGub** [comment]
Verificar depoimento do Washington

**Comment by elpadrejorge** [comment]
todos os depoimentos foram transcritos e já inseridos no ambiente virtual. Tarefa concluída.
