### ISSUE TITLE
Atualização de conteúdos Ambiente Virtual da Oficina

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#356]
## **Objetivo**

**Como** designer
**Quero** fazer uma revisão geral de conteúdos
**Para** atualizar com os acontecimentos do pós-oficina

## **Contexto**
É preciso disponibilizar os achados da Oficina de Design de Serviços da ESP

## **Escopo**

Etapa 1 - Pré-Oficinas

Refinamento:
- [x] Estudar solução para visualização da metodologia em mobil
- [x] Mudar título de "Metodologia" dos blocos para "Condução da Etapa 1"
-- [ ] Padrozinar no título - Passo 1 - Definição de áreas, Passo 2 - Estruturação de Problemas, Passo 3 - Priorização de Problemas, Passo 4 - Banco de Problemas, Passo 5 - Problemas Transverssais, Passo 6 - Problemas direcionados aos macroprocessos e aos objetivos estratégicos.
-- [ ] No passo 6, inserir uma nota do que é Cluster

- [x] Mudar "Materiais de Apoio" do bloco da Etapa 1 para "Achados da Etapa 1"
- [x] Mudar: Abaixo, reunimos os achados de cada pré-oficina em cards específicos onde será possível consultar o board do Figma sistematizado com a Árvore de Problemas e a Matriz GUT, além de baixá-los.
- Para: Abaixo, reunimos os achados de cada pré-oficina em cards específicos onde será possível consultar quadros sistematizados deproblemas e sua respectivas priorizações, além de baixá-los.

- [x] Mudar título do bloco "Oficina" para: Etapa 2 - Oficina
- [x] Mudar título de "Metodologia" dos blocos para "Condução da Etapa 2"
- [x] Mudar início do parágrafo: Na segunda metade da tarde... para: Ainda no segundo dia....
- [x] Mudar "é" do Terceiro dia para "será"

## Observações
**Atenção, após revisão é preciso da validação do Time de Narrativas**

**Comment by RaniGub** [comment]
Etapa 1 - Pré-Oficinas

Refinamento:
- [x] Estudar solução para visualização da metodologia em mobil
- [x] Mudar título de "Metodologia" dos blocos para "Condução da Etapa 1"
-- [ ] Padrozinar no título - Passo 1 - Definição de áreas, Passo 2 - Estruturação de Problemas, Passo 3 - Priorização de Problemas, Passo 4 - Banco de Problemas, Passo 5 - Problemas Transverssais, Passo 6 - Problemas direcionados aos macroprocessos e aos objetivos estratégicos.
-- [ ] No passo 6, inserir uma nota do que é Cluster

- [x] Mudar "Materiais de Apoio" do bloco da Etapa 1 para "Achados da Etapa 1"
- [x] Mudar: Abaixo, reunimos os achados de cada pré-oficina em cards específicos onde será possível consultar o board do Figma sistematizado com a Árvore de Problemas e a Matriz GUT, além de baixá-los.
- Para: Abaixo, reunimos os achados de cada pré-oficina em cards específicos onde será possível consultar quadros sistematizados deproblemas e sua respectivas priorizações, além de baixá-los.

- [x] Mudar título do bloco "Oficina" para: Etapa 2 - Oficina
- [x] Mudar título de "Metodologia" dos blocos para "Condução da Etapa 2"
- [x] Mudar início do parágrafo: Na segunda metade da tarde... para: Ainda no segundo dia....
- [x] Mudar "é" do Terceiro dia para "será"

Etapa 3 - Pós-Oficina
- [ ] A fazer...

**Comment by elpadrejorge** [comment]
Alterações possíveis realizadas.
Reorganizei o escopo para checkboxs para reforçar o que pode ser resolvido.
