### ISSUE TITLE
Disponibilizar metodologia da flecha no ambiente virtual

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#357]
## **Objetivo**

**Como** designer
**Quero** Disponibilizar metodologia da flecha no ambiente virtual
**Para** possibilitar a consulta pelos colaboradores da ESP

## **Contexto**
A metodologia da oficina de design foi representada, em seus primeiros ensaios, com um formato de flecha. Esta representação facilita o entendimento de todo o processo da oficina.

## **Escopo**
- [x] estudar o melhor formato de imagem para ampliação
- [x] criar uma opção com a lupa na imagem para sugerir a ampliação em uma seção apenas visível para o mobile.

## Observações
Links de apoio e informações adicionais

**Comment by RaniGub** [comment]
@elpadrejorge acho que pode ser nosso MVP 1.1. O original tá na board.
![Captura de Tela 2022-07-13 às 14 22 02](https://user-images.githubusercontent.com/79097920/178794205-157d40a0-c240-4989-80d5-99cd057a3953.png)

**Comment by RaniGub** [comment]
Resolver bug de visualização e colocar conteúdo em duas colunas.

**Comment by RaniGub** [comment]
Ajeitar a disposição da coluna da imagem e jogar título pra cima.

**Comment by elpadrejorge** [comment]
Ajustes realizados.

**Comment by RaniGub** [comment]
Inverter colunas.

**Comment by RaniGub** [comment]
Foi!
