### ISSUE TITLE
Disponibilizar no ambiente virtual os clusters de todos os problemas | Parte 2

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#359]
## **Objetivo**

**Como** designer
**Quero** Disponibilizar no ambiente virtual os clusters de todos os problemas 
**Para** possibilitar a consulta pelos colaboradores da ESP

## **Contexto**
Com o fim do momento presencial da oficina, a etapa de pós-oficina possui entre suas entregas a disponibilização dos achados validados na oficina no ambiente virtual. 

## **Escopo**
- [x] criar na seção de achados da oficina um espaço para apresentar todos os 13 cluster encontrados e validados na oficina

**Comment by RaniGub** [comment]
Disponibilizar primeira visualização dos cards em tamanho padrão.

**Comment by RaniGub** [comment]
Criar visualização para detalhamento dos encaminhamentos.
