### ISSUE TITLE
Relacionar histórias semelhantes com a Inception mãe

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#360]
## **Objetivo**

**Como** designer de experiência
**Quero** relacionar histórias mapeadas na Inception Mãe com a jornada geral da Residência   
**Para** criar visualização desse relacionamento e facilitar processos seguintes.

## **Contexto**

- Por ocasião da realização das oficinas de Design de Serviços na ESP/CE (29 a 30 de julho de 2022), se faz necessário analisar e sistematizar os resultados obtidos, de modo a viabilizar o compartilhamento dos achados, gerar registro histórico do processo e viabilizar um melhor aproveitamento das informações no desenvolvimento das atividades seguintes.

## **Escopo**

- [x] Relacionar histórias semelhantes com a Inception mãe
- [x] Validar board do figma com líder do Design

## Observações
- Board da Oficina no figma em processo de construção:
https://www.figma.com/file/5FFxEuc7eI7tQlfSc7xYQ7/Fluxo-de-Produtos?node-id=0%3A1
- Apresentar ao time de produtos

**Comment by RaniGub** [comment]
Pareamento realizado:
- Seguir na exibição priorização pela GUT
- Indicar no cluster de Soluções não Integradas as priorizações da expectativa dos grupos
- Inserir legenda para histórias similares que se conectam e histórias que atendem a mais de um momento da jornada

**Comment by pauloamoreira** [comment]
.relacionamento finalizado. aguardando aprovação de @RaniGub

**Comment by RaniGub** [comment]
Sugestão de legendas para relacionamento feita.

**Comment by RaniGub** [comment]
Oi @pauloamoreira qnd vc puder fala comigo pra gente concluir a revisão dessa tarefa.

**Comment by RaniGub** [comment]
Tarefa finalizada. @ricardopoppi a sistematização está completa e pronta para ser entregue ao time de produtos.
