### ISSUE TITLE
Revisar post-it gerados nos grupos

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#361]
## **Objetivo**

**Como** designer de experiência
**Quero** revisar post-it gerados nos grupos
**Para** garantir o registro dos dados no figma

## **Contexto**

- Por ocasião da realização das oficinas de Design de Serviços na ESP/CE (29 a 30 de julho de 2022), se faz necessário analisar e sistematizar os resultados obtidos, de modo a viabilizar o compartilhamento dos achados, gerar registro histórico do processo e viabilizar um melhor aproveitamento das informações no desenvolvimento das atividades seguintes.

## **Escopo**

- [x] Revisar post-it no figma, estabelecendo relação de paridade com as fichas de personas.

## Observações
- Board da Oficina no figma em processo de construção:
https://www.figma.com/file/0NCBQdGdrnvop0vrV1nxSS/Board-Oficina-ESP?node-id=0%3A1

**Comment by RaniGub** [comment]
@pauloamoreira existe uma nova persona no cluster de Soluções não Integradas, o Francisco. Ele tem duas necessidades. Amanhã atualizo você.

**Comment by pauloamoreira** [comment]
revisão concluída. @elpadrejorge foram encontrados erros de revisão nas fichas das personas. caso estas fichas já tenham sido postadas no site, convém atualizar os arquivos a partir da versão atual, já revisada.
