### ISSUE TITLE
Mapear as ações potenciais | Publicações/Artigos

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#362]
## **Objetivo**

**Como** pesquisador  
**Quero** mapear as práticas do Time de Design
**Para** desenvolvimento de artigos científicos

## **Contexto**

Através das Metodologias Projetuais em Design, o Time de Design contribui no desenvolvimento das Soluções Digitais do SUS-CE, integrando teoria e prática do Design em suas ações. Visto o potencial de publicização da práxis transdisciplinar, é importante que se faça um mapeamento e sistematização dos acontecimentos para submissão de artigos em Periódicos de alto Fator de Impacto e/ou alta classificação no Qualis Capes.

## **Escopo**

- [x] Mapear as ações potenciais

## Observações
https://docs.google.com/document/d/1cs06jc2UdV41UbXw5twcqFVXSNPgqmPs0PoIowAgPZo/edit

**Comment by RaniGub** [comment]
@elpadrejorge você chegou a fazer algum esboço do artigo da oficina? Se sim vocêpode disponibilizar aqui? Vlw.

**Comment by elpadrejorge** [comment]
@RaniGub , está atualizado na tarefa #373
https://docs.google.com/document/d/1xJHOciNKCFtNAk_G__M_dYbXnNJKPTI_/edit?usp=sharing&ouid=101992110686901504915&rtpof=true&sd=true
