### ISSUE TITLE
Revisão geral de conteúdo | Ambiente Virtual Oficina ESP

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#364]
## **Objetivo**

**Como** designer
**Quero** fazer uma revisão geral de conteúdos
**Para** atualizar com os acontecimentos do pós-oficina

## **Contexto**
É preciso disponibilizar os achados da Oficina de Design de Serviços da ESP

## **Escopo**

- [x] Revisão geral (organização de conteúdos não mais necessários)
- [x] Revisar os objetivos disponibilizados no site (verificar apresentação e figma)

## Observações
**Atenção, após revisão é preciso da validação do Time de Narrativas**

**Comment by RaniGub** [comment]
Estudar estilos dos títulos

**Comment by RaniGub** [comment]
Revisar o target de todas as janelas.

**Comment by ClarisCaval** [comment]
Esta revisão já está prevista na issue:
https://app.zenhub.com/workspaces/narrativas-62a774cf9c38ab0010cac6cd/issues/escoladesaudepublica/narrativas/60
Vou concluir essa para nós, considerando que o escopo será resolvido na outra.

**Comment by edmirandajr** [comment]
> Revisar os objetivos disponibilizados no site (verificar apresentação e figma)

@elpadrejorge preciso consultar esse figma para fazer a revisão?

**Comment by edmirandajr** [comment]
conversei com Jorge hoje para entender o que procurar em minha revisão. Já percebemos algumas melhorias. Vou apontar tudo em um documento e linkar aqui

**Comment by edmirandajr** [comment]
Comecei a apontar melhorias nesse link, devo encerrar até quinta https://docs.google.com/document/d/1bd7QjlfpfWJxIwyirZ-2VWfXcOx_pjCRCmQL-Bj4b6g/edit

**Comment by edmirandajr** [comment]
Revisão concluída, aguardo indicação do @elpadrejorge para resolver qualquer dúvida sobre minhas sugestões.

A revisão está disponível nesse link https://docs.google.com/document/d/1bd7QjlfpfWJxIwyirZ-2VWfXcOx_pjCRCmQL-Bj4b6g/edit

**Comment by elpadrejorge** [comment]
Sugestões implementadas, na medida do possível. Peço ao @edmirandajr para validar se as alterações resolvem as questões levantadas.

**Comment by edmirandajr** [comment]
revisão concluída. disponível no link https://docs.google.com/document/d/1bd7QjlfpfWJxIwyirZ-2VWfXcOx_pjCRCmQL-Bj4b6g/edit?usp=sharing
