### ISSUE TITLE
Inserir os objetivos da Oficina de Design de Serviços da ESP no texto de abertura do Ambiente Virtual

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#366]
## **Objetivo**

**Como** narrativeira
**Quero** revisar o texto de abertura da oficina
**Para** que os objetivos da oficina de design de serviços estejam presentes de forma orgânica no texto de abertura.

## **Contexto**

- O texto de abertura da ODSESP presente no Ambiente Virtual da Oficina foi estruturado para um release e aproveitado com poucas adaptações para sua função de apresentação do ambiente. Porém, com o término da Oficina e a revisão do ambiente virtual, se fez necessário a reescrita/adaptação do texto para que sejam contemplados os objetivos da oficina em sua redação de forma orgânica.

Narrativas: Conteúdo textual
Design: Inserção no ambiente

## Observações
https://sus.ce.gov.br/felicilab/oficinadesignesp/

Texto de abertura atual
Oficina de Design de Serviços: Felicilab promoveu diagnóstico de problemas por áreas da ESP/CE, com uso de Design Thinking

A Oficina de Design de Serviços da ESP teve o objetivo de reunir pessoas de representatividade de todas as áreas da escola para, por meio de um processo colaborativo baseado no Design Thinking, reconhecer seus principais desafios e priorizá-los com a validação de todos os participantes.

Para que cada um destes desafios pudessem ser reconhecidos e acolhidos de forma consistente, o Felicilab propôs que cada área se encontrasse com o time do DesignLab em um momento isolado, onde poderiam ser percebidos os principais problemas da área e priorizá-los de forma mais específica. A este momento chamamos de Pré-Oficina. A proposta foi de que cada área (Governança e Gestão, Educação e Extensão, Desenvolvimento Educacional, Inteligência em Saúde, Pesquisa em Saúde e Inovação e Tecnologia)  tivesse seu momento de Pré-Oficina entre os dias 18 de maio e 6 de junho de 2022. 

Após a finalização das pré-oficinas, o time do DesignLab se debruçou sobre os achados de cada encontro para viabilizar a Oficina de Design de Serviços da ESP, que contou com a participação de todas as áreas, nos dias 28, 29 e 30 de junho, das 13h30 às 17 horas, na Biblioteca Estadual do Ceará, a BECE.

Nestes dias de oficina, cada participante teve a oportunidade de conhecer os principais desafios de outras áreas e relacionar, de forma colaborativa, quais destes são transversais às suas áreas. Desta forma, o time do DesignLab contribuiu para que a ESP reconheça e valide cada um de seus problemas de forma colaborativa e priorizada. 

Por fim, cada participante pode, por meio de ferramentas metodológicas do Design Thinking, reconhecer as principais soluções possíveis para os problemas encontrados e direcionar novas entregas para cada um dos responsáveis. 

Objetivos da Oficina
- Compreensão e categorização de causas, problemas e consequências das Áreas da ESP.
- Desenvolvimento da compreensão colaborativa dos problemas transversais
- Priorização dos problemas.
- Compreensão e refinamento de problemas das Áreas e de como eles se relacionam.
- Registro de memória de processos e resultados.
- Informações de apoio à conexão dos problemas com os objetivos estratégicos da ESP.
- Informações de apoio para relacionamento de problemas com as competências das áreas.

**Comment by ClarisCaval** [comment]
Bom dia, pessoas. Segue a nova proposta de texto;
https://docs.google.com/document/d/1IoaBzRogOLyLX23YwZvlRtzORnhRJ6n4-K14FTISYrg/edit
Qualquer dúvida, tô por aqui.

**Comment by elpadrejorge** [comment]
Texto adicionado ao site.

**Comment by elpadrejorge** [comment]
Texto adicionado ao site.
