### ISSUE TITLE
Emissão de declarações da Oficina de Design

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#369]
## **Objetivo**

**Como** organizador da oficina de design
**Quero** gerenciar as informações das pessoas inscritas
**Para** emitir declarações de participação

## **Contexto**
É preciso fazer o relacionamento dos inscritos com a frequência das pessoas para emissão de declarações.

## **Escopo**

- [x] Criar espaço no site informando sobre as declarações. O espaço deve conter formulário de contato para aquelas pessoas que participaram e não se inscreveram pelo Mapa.
- [x] Alinhar com narrativas

Norteamento para texto na seção do site: Se você participou de pelo menos 2 dias da Oficina, sua declaração já está disponível para download no Mapa da Saúde. Acesse esse link, depois clique em "Loren Ipsun" de seu perfil e baixe a declaração [Verificar caminho]. Se você não conseguiu acessar sua declaração, preencha o formulário abaixo que a gente lhe ajuda. [Vinculamos o formulário ao e-mail do Felicilab?] (Compreender o caminho que leva até a declaração)

Fluxo de resposta para o formulário: 

Verificar se a solicitação atende aos critérios da Regra 1 dessa tarefa -> Sim -> Enviar link da oportunidade e solicitar que a pessoa informe que o preenchimento foi realizado -> Verificar inscrição e mudar status para selecionado -> Disponibilizar declaração (Verificar com Wanderley ou Thaís o procedimento) -> Informar a pessoa via e-mail

Caso contrário: Informar por e-mail que a pessoa não atingiu a presença mínima para emissão da declaração

Responsável: Jorge Dodói.
Apoio: Narrativas

## Observações
**REGRAS**
1 - As pessoas que se inscreveram no período de pré-inscrição e estiveram presentes na oficina em pelo menos 2 dias, devem receber declarações. O mesmo se aplica a quem não se inscreveu e esteve presente em pelo menos 2 dias.
2- Quem se inscreveu resgata a declaração pelo Mapa. Quem não se inscreveu e assinou a frequência, deve entrar em contato para a gente reabrir a oportunidade para ela informar os dados e gerarmos a declaração; 
3- Só vamos atender os casos que recebermos e-mail solicitando, ai fazemos a conferência na frequência; 
4- Toda a organização deve receber declaração.

Participante: 20h
Facilitador: 40h
Organização: 80h

**Comment by RaniGub** [comment]
@ericabpinho precisamos alinhar com vcs essa issue.

**Comment by ericabpinho** [comment]
@RaniGub, @Clarisse1983, @elpadrejorge: vou preparar uma proposta de texto. Chamo o Jorge para alinhar assim que a sugestão de texto estiver pronta.

**Comment by ericabpinho** [comment]
@RaniGub, @Clarisse1983, @elpadrejorge: 
Proposta do texto: https://docs.google.com/document/d/1vseISmYPcf3JiKvCWOGlOb49euVya_d6vs6M5XT0eBk/edit.

**Comment by elpadrejorge** [comment]
Após conversa com a Ana Xenofonte, foram traçadas três possibilidades de encaminhamentos para esta tarefa: 
1 - Que as declarações fossem geradas manualmente pela Secretaria
2 - Que, via código, a oportunidade da Inscrição da Oficina no Mapa da Saúde fosse desbloqueada e tivesse o selo aplicado e os nomes dos não inscritos adicionados. Consultei o @victorMagalhaesPacheco sobre esta possibilidade e ele diagnosticou o esforço como médio. (Esta opção parece ser a mais interessante, pelo meu ponto de vista, porém precisa ter sua viabilidade estudada e validada. Ana Xenofonte solicitou que estas declarações da Oficina pudessem servir de teste para a migração dos dados entre Mapa e Sagu.)
3 - Criar uma nova oportunidade onde todos os interessados na declaração precisarão se (re)inscrever para ter acesso.

Aguardo deliberarmos sobre o assunto para que os devidos encaminhamentos sejam tomados.

**Comment by RaniGub** [comment]
@elpadrejorge 

Encaminhamentos: 
1- Fornecer a lista dos participantes para Ana Xenofonte. Vamos simplificar e deixar somente 3 categorias dos envolvidos na Oficina como falamos anteriormente:
Participante: 20h
Facilitador(a): 40h
Organizador(a): 80h

2- Todos que estiveram presentes pelo menos 2 dias da Oficina recebem a declaração, independente se fizeram ou não a pré-inscrição. Vamos considerar a lista de presença;

3- Após a impressão das declaração, podemos resgatar com a Ana e as pessoas podem retirar diretamente conosco. Informamos no site e grupo no whastapp;

4- Não é preciso anexos à declaração.

**Comment by RaniGub** [comment]
Aguardando pareamento com a Ana Xenofonte. Dia 31/03/22 ela será novamente procurada para novo alinhamento.

**Comment by elpadrejorge** [comment]
Em conversa com a Ana, foi solicitado o envio de um memo para a expedição das declarações da oficina. Junto a ele deve ir a matriz da frequência dos participantes pelo Sagu. Como nada foi lançado no Sagu, irei parear com a @nazkafarias a inserção destes dados no Sagu, provavelmente hoje, 01/09.

**Comment by RaniGub** [comment]
A @nazkafarias e o Alexandre do time de projeto estão organizando a turma no Sagu para darmos procedimento a etapa de emissão.

**Comment by alesouza88** [comment]
Já solicitamos ao Time Técnico o envio do memorando para a Secretaria Acadêmica abrir o curso no Sagu, junto com o "FORMULÁRIO PARA CADASTRO DE CURSO NO SAGU". Segue abaixo a minuta de solicitação:
Link do formulário: https://docs.google.com/document/d/1zONiXuv26NUEXCVGl1GKy2GhaqIRd3-OIH-uAoWScEE/edit 

![image](https://user-images.githubusercontent.com/87095371/188448816-0cec378f-7b08-447e-90f5-5f85707dae99.png)


Os passos seguintes, depois de aberto o curso no Sagu, será abrir a turma e inserir a lista de participantes, após isso será solicitação a emissão das declarações. A Nazka está me apoiando nessa atividade, pois ela já tem familiaridade com o sistema.

**Comment by RaniGub** [comment]
@alesouza88 teste

**Comment by alesouza88** [comment]
> alesouza88 reacted with rocket emoji

TOPPPPPP

**Comment by RaniGub** [comment]
Em alinhamento com o @alesouza88 os cadastros no Sagu estão sendo realizados. O próximo passo será a emissão das declarações pela Secretaria Acadêmica

**Comment by RaniGub** [comment]
@nazkafarias informou que falta somente as informações de três pessoas. Alinhamos que o prazo será até dia 16/09/2022 para que as pessoas enviem essas informações.

**Comment by RaniGub** [comment]
@nazkafarias concluiu o doc. Será encaminhado para a secretaria acadêmica.

**Comment by alesouza88** [comment]
OI lindezass, @nazkafarias já me enviou a documentação preenchida e só tive o  trabalho de enviar para DITEC para formalizar o pedido de certificação à Secretaria Acadêmica.

Coloquei toda a documentação na pasta drive, intitulada de OFICINA DE DESIGN ESP, localizada no endereço : (https://drive.google.com/drive/folders/1OSnTQ5VUFw_L7BN3sxyBzHJYnenap6vL?usp=sharing) 


Segue abaixo e-mail enviado à DITEC
![image](https://user-images.githubusercontent.com/87095371/190453961-5e2865c6-9fc7-42a6-b3df-cf9d32d81783.png)

**Comment by RaniGub** [comment]
Obrigado @alesouza88 e @nazkafarias

**Comment by elpadrejorge** [comment]
As declarações ficaram prontas e já foram entregues para os participantes do Felicilab que estavam presentes. Estão guardadas no armário da recepção. @nazkafarias informou que as outras declarações já foram emitidas e estão à disposição na secretaria acadêmica. Iremos divulgar no grupo do whatsapp e também no site.
