### ISSUE TITLE
Compreensão de cenário para o Projeto de Fortalecimento da Capacidade de detecção e Respostas às Emergências em Saúde Publica

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#371]
## **Objetivo**

**Como** designer
**Quero** estudar possibilidades de participação no Projeto
**Para** ter contexto na Reunião da Proepi/Sevig e Inception

## **Contexto**

Estamos participando da prospecção de um novo projeto com a Coordenadoria de Vigilância Epidemiológica da SESA. É preciso compreender o cenário de oportunidades nesse projeto.

## **Escopo**

- [x] Explorar o App Guardiões da Saúde
- [x] Participação em Reunião de Alinhamento de Expectativas em 10.08.2022
- [x] Esboçar possibilidades para o projeto

## Observações
Ideias iniciais
1- Plataforma para divulgação das ações
2- Módulo de integração com do GDS com iSUS
3- QualiQuiz para avaliação das formações
4- Estratégias de comunicação para engajamento

Slides
[4a16d156-86cc-483d-b796-7b59b9186e3b.pdf](https://github.com/EscolaDeSaudePublica/DesignLab/files/9181151/4a16d156-86cc-483d-b796-7b59b9186e3b.pdf)

Telas App GDS
https://www.figma.com/file/NojXgCWZChd3vEnCkQsgu3/telas-App-Guardi%C3%B5es-da-Sa%C3%BAde?node-id=0%3A1

Fluxo
https://www.figma.com/file/74YFhLjKBxT55cAIZT8GKo/Fluxo-do-Projeto-da-Vigil%C3%A2ncia?node-id=0%3A1

Documento de acompanhamento
https://docs.google.com/document/d/16TkkmiBL2fK3SvkVpGdjXUjYZqocQfeiFnIgudH3d6s/edit?usp=sharing

**Comment by RaniGub** [comment]
Link do primeiro encontro disponibilizado.

**Comment by pauloamoreira** [comment]
.foi realizada, dia 10.08.2022, reunião de Mapeamento de Expectativas com Sarah Mendes (SESA) e equipe, DEDUC, DITEC e Felicilab, para alinhamento das demandas. A partir das informações recebidas, será reformulada a formalização da demanda na ESP. Será agendada uma inception para coleta dos dados necessários para execução das entregas da DITEC/Felicilab.

**Comment by pauloamoreira** [comment]
.após reunião da equipe do Felicilab no dia 17.08.2022, ficou definido que a proposta inicial será apresentado, para informe de pendências e encaminhamentos, ao Comitê de Governança da ESP dia 18.08.2022.

**Comment by pauloamoreira** [comment]
Fluxo do projeto atualizado no figma.

**Comment by RaniGub** [comment]
Inception marcada para 26/06, 14h
