### ISSUE TITLE
Site Felicilab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#374]
## **Objetivo**

**Como** designer
**Quero** construir um novo site para o Felicilab  
**Para** reunir as informações institucionais do laboratório

## **Contexto**

- Com o movimento da Prestação de Contas do Felicilab, se evidenciou a necessidade de um redesign do site, com nova identidade visual que transmita os valores da marca e seu portfolio e que agrege as entregas do laboratório de forma clara e consistente. Para além disso, o site precisa evidenciar a autonomia do laboratório em captação de recursos extra-Sesa e sua governança colaborativa e inovadora.

## **Escopo Time de Design**

ETAPA 1
- Reunir-se com o time de Narrativas e estruturar os conteúdos do site
- Elaborar a arquitetura do site
- Definir as jornadas dos usuários do site
- Definir de que forma cada conteúdo desenvolvido será exibido no site (Desenvolver wireframe dos modelos das páginas)
- Pesquisar e definir soluções visuais para a hierarquia de textos e informações
- Implementar soluções visuais para a hierarquia de textos e informações
- Definir paleta de cores harmônica às cores do Felicilab e suas aplicações 

ETAPA 2
- Estruturar o tema/template divi do site
- Produzir as páginas do site
- Instalar e configurar plugins de firewall, otimização SEO, proteção AntiSpam e otimização PageSpeed
- Cadastrar no Google Empresas

ETAPA 3
- Teste de usabilidade
- Refinamento

## **Escopo Time de Narrativas**
- Produzir textos para cada área do site (Tarefas desdobradas na board de narrativas)

## Observações
Board de apoio
https://www.figma.com/file/ahyV3xaWLuEpkxl7UmMjZy/Jornadas-e-Arquitetura-da-Informa%C3%A7%C3%A3o-V2?node-id=0%3A1

Pasta - Textos site Felicilab
https://drive.google.com/drive/folders/1diz4_TCJpBVU0hfM-IoskUQ5xTTNSpgy?usp=sharing

Pasta - Prestação de contas (contém textos para páginas do site)
https://drive.google.com/drive/folders/1NWi_0_85UcJTNjq2Tk5sM3uS_6cux-Lc?usp=sharing

MVP 2
- Estudar que tipo e onde as ilustrações serão exibidas no site

**Comment by RaniGub** [comment]
@elpadrejorge vc pode disponibilizar o endereço do estudo no WP?

**Comment by RaniGub** [comment]
Bom dia @ericabpinho e @edmirandajr tudo de boa? Minha proposta é que esse épico seja espelhado na board de narrativas e o escopo ser desdobrado e atualizado por vocês. Daí o @elpadrejorge consegue acompanhar os desdobramentos e se aproximar quando for necessário. Editei um espaço no Escopo para Narrativas.  

Para Jorge:
- Dei uma rápida atualizada no escopo, fiquei na dúvida sobre o Analytics, em que fase ele entra? Após a indexação?
- @pauloamoreira pfv, faça um pareamento com o Jorge para compreensão do wireframe.

**Comment by edmirandajr** [comment]
@RaniGub temos nas pastas abaixo textos para o site. No entanto, ainda precisamos decidir se mantemos em pastas separadas ou reunimos todos numa pasta só para evitar confusão. @ericabpinho @Clarisse1983 

Pasta - Textos site Felicilab
https://drive.google.com/drive/folders/1diz4_TCJpBVU0hfM-IoskUQ5xTTNSpgy?usp=sharing

Pasta - Prestação de contas (contém textos para páginas do site)
https://drive.google.com/drive/folders/1NWi_0_85UcJTNjq2Tk5sM3uS_6cux-Lc?usp=sharing

**Comment by pauloamoreira** [comment]
> Bom dia @ericabpinho e @edmirandajr tudo de boa? Minha proposta é que esse épico seja espelhado na board de narrativas e o escopo ser desdobrado e atualizado por vocês. Daí o @elpadrejorge consegue acompanhar os desdobramentos e se aproximar quando for necessário. Editei um espaço no Escopo para Narrativas.
> 
> Para Jorge:
> 
> * Dei uma rápida atualizada no escopo, fiquei na dúvida sobre o Analytics, em que fase ele entra? Após a indexação?
> * @pauloamoreira pfv, faça um pareamento com o Jorge para compreensão do wireframe.

@elpadrejorge podemos parear dia 19.08, as 15h?

**Comment by RaniGub** [comment]
Após pareamento com a @Clarisse1983, compreendemos que os perfis devem contemplar as pessoas do Felicilab, enquanto as da Ditec devem aparecer no modelo de governança na seção do Felicilab. Considerar uma versão para o site e atualizar as informações.

**Comment by elpadrejorge** [comment]
Em conversa com o time de Soluções (@fwandson @Wanderley97 e João Paulo), foi solicitado a criação de um ambiente de homologação para o novo site do Felicilab. Foi aberto o chamado 20220906586890 e estamos no aguardo.

**Comment by RaniGub** [comment]
Em alinhamento com o @fwandson o prazo para criação do ambiente de homologação do site do Felicilab é 16/09/2022.

**Comment by RaniGub** [comment]
@elpadrejorge segunda pela manhã (12/09/22) você consegue fazer um exercício de projeção do que falta para o MVP 1 do novo site? Entendo que existe um bloco transversal de coisas que dependem da narrativas, mas para a gente ter um contexto geral e rodar duas ou três sprints do site até o lançamento.

**Comment by RaniGub** [comment]
Wandson informou que irá disponibilizar hoje pela tarde a homologação.

**Comment by RaniGub** [comment]
Wandson informou que devido a uma demanda emergencial teve que repriorizar a criação dos ambientes. Informei que a falta deles está bloqueando algumas atividades nossa e pedi a avaliação para priorização.

**Comment by RaniGub** [comment]
As modificações que serão feitas no site serão para: 
1) Dar destaques a alguns números, fazer uma costura com os benefícios do uso do produto e mostrar oq o ele faz além do que é apresentado/Ver potencialidades @ericabpinho você pode alinhar com o @pauloamoreira que estava fazendo um exercício de potencialidades do Mapa e iSUS. Ele vai te dar algumas informações de relevância.

2) Mudanças na home. Dar prioridade a narrativa do que é o Felicilab, como trabalhamos.... mesclado com conteúdos das soluções e outros conteúdos que a narrativas der prioridade.

**Comment by RaniGub** [comment]
O site está no ar, mas apresenta ainda alguns erros que serão mapeados e sanados durante os próximos dias.

**Comment by RaniGub** [comment]
![print](https://user-images.githubusercontent.com/79097920/205915510-c32b0960-1a84-4c91-975e-d3e59b4cff6b.png)
Gente bom dia, estava conversando com o Jorge pra tentar compreender uma função melhor para essa seção no rodapé do site. Acho que os narrativeiros conseguem dar um norte pra gente. @edmirandajr @Clarisse1983

**Comment by edmirandajr** [comment]
@RaniGub acho que poderia ser um link direto para a seção "bora inovar?" com um fotão bem bonito de algum felicilaber fazendo um gesto de chamamento.

**Comment by RaniGub** [comment]
Site concluído e publicado. Compreendemos que algumas melhorias serão implementadas no decorrer do tempo.
