### ISSUE TITLE
Elaborar a arquitetura e definir as jornadas dos usuários do site do Felicilab

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#376]
## **Objetivo**

**Como** designer
**Quero** elaborar a arquitetura e as jornadas do site do Felicilab  
**Para** reunir as informações institucionais do laboratório com uma experiência consistente

## **Contexto**

- Com o movimento da Prestação de Contas do Felicilab, se evidenciou a necessidade de um redesign do site, com nova identidade visual que transmita os valores da marca e seu portfolio e que agrege as entregas do laboratório de forma clara e consistente. Para além disso, o site precisa evidenciar a autonomia do laboratório em captação de recursos extra-Sesa e sua governança colaborativa e inovadora.

## **Escopo**

- [x] Elaborar a arquitetura do site
- [x] Definir as jornadas dos usuários do site

## Observações
Links de apoio e informações adicionais

**Comment by RaniGub** [comment]
Bom dia @elpadrejorge. Você pode disponibilizar o link das jornadas?
