### ISSUE TITLE
Pesquisar e definir soluções visuais para a hierarquia de textos e informações

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#379]
## **Objetivo**

**Como** designer
**Quero** pesquisar e definir soluções visuais para a hierarquia de textos e informações do site do Felicilab
**Para** consolidar escolhas visuais consistentes com a marca do laboratório

## **Contexto**

- Com o movimento da Prestação de Contas do Felicilab, se evidenciou a necessidade de um redesign do site, com nova identidade visual que transmita os valores da marca e seu portfolio e que agrege as entregas do laboratório de forma clara e consistente. Para além disso, o site precisa evidenciar a autonomia do laboratório em captação de recursos extra-Sesa e sua governança colaborativa e inovadora.

## **Escopo**

- [x] Pesquisar e definir soluções visuais para a hierarquia de textos e informações

**Comment by RaniGub** [comment]
@elpadrejorge disponibilizar arquivo no cloud.
