### ISSUE TITLE
Adaptação de fluxo de inception para demanda de projeto com a SEVIG/SESA

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#384]
## **Objetivo**

**Como** designer de experiência
**Quero** adaptar o fluxo atual de realização de Inception  
**Para** adequá-lo a aplicação em projeto de parceria entre a Secretaria Executiva de Vigilância Sanitária e a ESP. 

## **Contexto**

- Por ocasião do agendamento de aplicação de Inception para compreensão e levantamento de requisitos de projeto de parceria entre a SEVIG/SES e a ESP, que ocorrerá, com duração diferenciada, no dia 26/08, se faz necessário analisar o modelo atual de fluxo de Inception para adaptá-lo, de modo a atender a finalidade programada.

## **Escopo**

- [x] analisar o modelo atual de fluxo de Inception
- [x] criar um modelo adaptado para a demanda emergente
- [x] validar modelo com líder do designlab

## Observações
- figma com o modelo adaptado (EM PROCESSO): https://www.figma.com/file/8GNW4TbAYbaeNzwsBXJiOn/Inceptions-customizada-para-SEVIG---EM-PROCESSO?node-id=0%3A1

**Comment by RaniGub** [comment]
Finalizado.
