### ISSUE TITLE
Inception SEVIG

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#387]
## **Objetivo**

**Como** designer de experiência
**Quero** realizar uma inception
**Para** levantar os requisitos da demanda da Sevig

## **Contexto**

- Por ocasião do agendamento de aplicação de Inception para compreensão e levantamento de requisitos de projeto de parceria entre a SEVIG/SES e a ESP, que ocorrerá, com duração diferenciada, no dia 26/08, se faz necessário analisar o modelo atual de fluxo de Inception para adaptá-lo, de modo a atender a finalidade programada.

## **Escopo**

- [x] Realizar inception

**Comment by pauloamoreira** [comment]
.Inception reagendada para a manhã do dia 29/08.
