### ISSUE TITLE
Alinhamento dos resultados da Inception

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#390]
## **Objetivo**

**Como** designer
**Quero** alinhar os resultados da Inception da Sevig com o time de narrativas
**Para** dispor do norteamento para o componente de inovação e tecnologia no projeto

## **Contexto**

- Foi realizada em 30/08/2022 a Inception com a Sevig. É preciso que essas informações sejam sistematizadas para que façamos um pareamento com os demais times para que a projeção de entregas esteja alinhada com as expectativas dos stakeholders.

## **Escopo**

- [x] Alinhar a projeção de entregas com o time de narrativas
- [x] Alinhar a projeção de entregas com o time de projetos

## Observações
https://www.figma.com/file/DFGckqKPixyaiqRV7TIEON/Fluxo-do-Projeto-da-Vigil%C3%A2ncia?node-id=0%3A1

**Comment by RaniGub** [comment]
@gabrieladamarques @Clarisse1983 só marcando vcs na tarefa pra deixar no horizonte de acontecimentos.

**Comment by RaniGub** [comment]
Primeiro pareamento com times de projeto realizada. É preciso de mais um encontro para visualização das entregas, incluindo o time de narrativas.

**Comment by pauloamoreira** [comment]
Primeiro pareamento com o time de narrativas realizada dia 08.09. Daremos continuidade dia 09.09.

**Comment by pauloamoreira** [comment]
Segundo pareamento com o time de narrativas realizado. Aguardando agora pareamento final com o time de projetos - @gabrieladamarques e @nazkafarias

**Comment by pauloamoreira** [comment]
Segundo pareamento com o time de projetos realizado.

**Comment by pauloamoreira** [comment]
Tarefa finalizada.
