### ISSUE TITLE
Despacho e relatório de atividades das Oficinas para Construção de Políticas Públicas

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#391]
## **Objetivo**

**Como** designer
**Quero** atualizar o despacho e o relatório de atividades das Oficinas de Políticas Públicas
**Para** apresentar em reunião com a Sesa

## **Contexto**

O Designlab está trabalhando na atualização dessas informações para apresentação em reunião com a Secretária Executiva de Políticas de Saúde, Mônica Souza, no dia 31/08/2022.

## **Escopo**

- [x] Atualizar relatório de atividades
- [x] Responder observações da Flavianne

**Comment by pauloamoreira** [comment]
.em conversa com @gabrieladamarques ela me informou que o despacho já foi protocolado, então não será alterado, mas o relatório de atividades já foi atualizado e compartilhado com a diretoria de inovação e tecnologia.

**Comment by RaniGub** [comment]
Tarefa reaberta, @pauloamoreira está trabalhando no novo tópico.

**Comment by pauloamoreira** [comment]
@RaniGub já incluí quase todas as informações solicitadas pela flavianne. vou finalizar no início da tarde. no entanto, é possível que os links das gravações de cada oficina estejam disponíveis apenas na sua conta. você tem como verificar essa informação?

**Comment by pauloamoreira** [comment]
@RaniGub as informações disponíveis foram inseridas no relatório.

**Comment by RaniGub** [comment]
Relatório concluído.

**Comment by pauloamoreira** [comment]
.tarefa reaberta para atender solicitação do Grupo Estratégico, por conta de demanda da SEPOS, referente a acréscimos no documento de prestação de contas. farei alinhamento sobre isso com a @nazkafarias dia 27.10.2022.

**Comment by pauloamoreira** [comment]
.enviei respostas dos itens da lista de solicitações de acréscimos ao relatório enviada por Mônica Souza Lima - atual Secretária Executiva de Políticas de Saúde - SEPOS para @nazkafarias.
