### ISSUE TITLE
Desenvolver seção dos Times do site do Felibilab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#396]
## **Objetivo**

**Como** designer
**Quero** desenvolver a seção dos Times do site do Felicilab
**Para** dispor das informações dos times

## **Contexto**

- Com o movimento da Prestação de Contas do Felicilab, se evidenciou a necessidade de um redesign do site, com nova identidade visual que transmita os valores da marca e seu portfolio e que agrege as entregas do laboratório de forma clara e consistente. Para além disso, o site precisa evidenciar a autonomia do laboratório em captação de recursos extra-Sesa e sua governança colaborativa e inovadora.

## **Escopo**

- [x] Desenvolver seção dos Times interface
- [x] Conversão de informações dos times do Felicilab

**Comment by RaniGub** [comment]
Jorge, vamos tentar ver amanhã pela manhã no presencial (16/09/22).

**Comment by edmirandajr** [comment]
Segue texto para validação: https://docs.google.com/document/d/10Gw_e0ZzdJa2LpR5G_ptpxGmLE-UtmnnPXtopOz6K5k/edit

@elpadrejorge @ericabpinho

**Comment by edmirandajr** [comment]
texto validado pelo Time de Narrativas
https://docs.google.com/document/d/10Gw_e0ZzdJa2LpR5G_ptpxGmLE-UtmnnPXtopOz6K5k/edit?usp=sharing

@elpadrejorge

**Comment by elpadrejorge** [comment]
Após pareamento com o time de Narrativas, ficou definido que temos 5 times no Felicilab: design, narrativas, desenvolvimento, produtos e projetos. No aguardo da definição do texto do time de produtos.

**Comment by RaniGub** [comment]
Alinha com o Jorge a experiência do MVP1 da seção.

**Comment by elpadrejorge** [comment]
Com base em refinamento de experiência com o @RaniGub , ficou definido que a página de Times será dividida em subpáginas para cada time, onde cada um será carregado com um menu de ícones para cada time.

**Comment by elpadrejorge** [comment]
Seções atualizadas e já inseridas no menu.

**Comment by elpadrejorge** [comment]
A área de times do Felicilab foi atualizada com base nos últimos alinhamentos sobre a divisão dos times da ESP, NIT e Felicilab.
