### ISSUE TITLE
Prospecção de recursos com UFC

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#398]
## **Objetivo**

**Como** designer  
**Quero** contextualizar a participação do Felicilab em um componente de inovação em um projeto da UFC
**Para** prospectar recursos financeiros

## **Contexto**

Em uma oportunidade de projeto multicêntrico com a Faculdade de Farmácia, Odontologia e Enfermagem - Universidade Federal do Ceará e outras universidades nacionais e internacionais, precisamos contextualizar o que é o Felicilab, suas ações e no que poderíamos contribuir em um componente de inovação.

## **Escopo Design**

- [x] Organizar os pontos de contribuição que dizem respeito ao tópico no projeto

## **Escopo Narrativas**

- [x] Organizar informações sobre o Felicilab e indicadores

## Observações
Links de apoio e informações adicionais
link para documento com texto criado pelo time de Narrativas https://docs.google.com/document/d/18-dNk8X_qGYnBc4E81QsO2fY1qoI5Wb75M2Ff8xdvvU/edit?usp=sharing

**Comment by RaniGub** [comment]
@ericabpinho @edmirandajr criei a issue para que vocês possam marcar a entrega, obrigado gente.

**Comment by edmirandajr** [comment]
obrigado @RaniGub
