### ISSUE TITLE
instalar e configurar plugins  | Site Felicilab

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#406]
## **Objetivo**

**Como** designer
**Quero** instalar e configurar plugins 
**Para** para garantir o bom funcionamento e segurança do novo site do Felicilab  

## **Contexto**

- O site do Felicilab está em seu processo final de desenvolvimento. Até o fim do defeso eleitoral, o seu novo design precisa estar no ar. Neste processo, alguns plugins precisam ser instalados para garantir o seu bom funcionamento e a segurança.

## **Escopo**

AMBIENTE DE HOMOLOGAÇÃO
- [x]  Instalar e configurar os plugins necessários (Wordfence, WPRocket, Instagram Feed, SMTP, GLPD, AntiSpam, Analytics) (TRATAMENTO COM O JORGE)

AMBIENTE DE PRODUÇÃO
- [x]  Instalar e configurar os plugins necessários (Wordfence, WPRocket, Instagram Feed, SMTP, GLPD, AntiSpam, Analytics) (INSTALAÇÃO WANDSON E CONFIGURAÇÃO JORGE)

AMBIENTE DE NARRATIVAS
- [x]  reformulação da linha do tempo pelo time de narrativas

**Comment by RaniGub** [comment]
No momento @elpadrejorge está fazendo a configuração dos plug-ins de menu na homologação.

**Comment by RaniGub** [comment]
Falta a implementação do Analytics e GLPD. @elpadrejorge você pode ver a conta que está a chave com o @danielgula? Além disso é legal já ver sobre o plug-in da timeline.

**Comment by RaniGub** [comment]
@elpadrejorge falei com o @danielgula sexta e ele disse que é só vc chamar ele pra falar sobre a timeline. Sobre o Analytics, ele falou que o Uirá que tem o acesso.

**Comment by elpadrejorge** [comment]
Bati um papo com o @danielgula sobre o plugin da linha do tempo. Precisamos agora alinhar com o @edmirandajr e a @Clarisse1983 qual a forma mais interessante de contar essa história que está sendo contada no plugin. Na mesma conversa, o Daniel informou que o acesso ao Analytics está em uma conta do @uira . Fico no aguardo para parearmos estas duas questões.

**Comment by elpadrejorge** [comment]
Foi instalado o EEEW Optimize Photos e o Resmush para otimizar imagens no site. Todas as imagens foram otimizadas e as próximas que forem inseridas já o serão automaticamente. O Askimet já foi validado em meu email da esp (jorge.godoy@esp.ce.gov.br). WP Rocket foi instalado e configurado para otimizar o cache e entregar melhores indicadores para o Page Speed Test, principalmente pelas funções de minificação de CSS e JS, além do carregamento tardio. O plugin de cookies foi instalado e fico no aguardo dos desdobramentos do Analytics com o @uira e da reformulação da linha do tempo pelo time de narrativas @edmirandajr @Clarisse1983  para encerrar esta tarefa.

**Comment by edmirandajr** [comment]
@Clarisse1983 trouxe essa issue "reformulação da linha do tempo pelo time de narrativas" para nossa board pra gente discutir na próxima planning
