### ISSUE TITLE
Criar as páginas dos conteúdos que já possuem modelos definidos | Site Felicilab

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#408]
## **Objetivo**

**Como** designer
**Quero** Criar as páginas dos conteúdos que já possuem modelos definidos
**Para** apresentar com o novo layout as soluções do felicilab

## **Contexto**

- O site do Felicilab está em seu processo final de desenvolvimento. Até o fim do defeso eleitoral, o seu novo design precisa estar no ar. Neste processo, foi criado um layout específico para a apresentação das soluções do felicilab. Após a criação do ambiente de homologação, o mesmo layout deve ser aplicado a todas as soluções do felicilab.

## **Escopo**
- [x] Criar páginas na homologação
- [x] Migrar conteúdos para as páginas

**Comment by RaniGub** [comment]
@elpadrejorge criar essa tarefa espelhada para os perfis.

**Comment by elpadrejorge** [comment]
O site já foi migrado para o ambiente de produção em 18/11. A página de Integração ao Time será reformulada pelo time de narrativas.
