### ISSUE TITLE
Precisamos melhorar a área de tutorial do Mapa (design) e também criar uma ou mais apresentações de treinamento do Mapa.

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/DesignLab#41]
Ex: https://docs.google.com/presentation/d/1aQZZ6MjDGf5WchKvCIHrRX2czdr_0aTWC9vtcYNtv18/edit?usp=sharing
https://mapa.sus.ce.gov.br/como-usar/

**Comment by RaniGub** [comment]
Essa tarefa será encerrada e a ação está prevista para ser desenvolvida na reformulação do Mapa da Saúde, incluída no épico "Plataforma de Qualificação da Força de Trabalho do SUS-CE #80".
