### ISSUE TITLE
Pesquisa do referencial teórico contemporâneo

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#413]
## **Objetivo**

**Como** designer
**Quero** refinar as vertentes do produto da Oficina de Design
**Para** dar conhecimento as pessoas sobre os processos envolvidos e aos objetivos

## **Contexto**

É necessário organizar um espaço dedicado às Oficinas para Construção de Políticas Públicas para refinar as vertentes do processo e dos resultados e, para facilitar a prospecção de novos projetos.

## **Escopo**

- Pesquisa do referencial teórico contemporâneo
- Visão síntese dos conceitos essenciais do referencial teórico contemporâneo

## Observações
Board no figma: https://www.figma.com/file/XhKWsyB7btbsW1M8NzwGeL/Pesquisa-do-referencial-te%C3%B3rico-contempor%C3%A2neo-%23413?node-id=0%3A1

**Comment by pauloamoreira** [comment]
.tarefa finalizada
