### ISSUE TITLE
O que são políticas públicas?

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#416]
## **Objetivo**

**Como** designer
**Quero** refinar as vertentes do produto da Oficina de Design
**Para** dar conhecimento as pessoas sobre os processos envolvidos e aos objetivos

## **Contexto**

É necessário organizar um espaço dedicado às Oficinas para Construção de Políticas Públicas para refinar as vertentes do processo e dos resultados e, para facilitar a prospecção de novos projetos.

## **Escopo**

- Pesquisa sobre o conceito de políticas

## Observações
Board no figma: https://www.figma.com/file/QAu2qmV2LK7q91IKtriAMH/Pesquisa-do-referencial-te%C3%B3rico-balisar-%23414?node-id=0%3A1

**Comment by pauloamoreira** [comment]
.tarefa finalizada.
