### ISSUE TITLE
Adaptação logo Dente-de-Leão para o NIT

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#417]
## **Objetivo**

**Como** designer  
**Quero** adaptar o logo Dente-de-Leão 
**Para** o NIT dispor de um logo

## **Contexto**

- Adaptação de logo para o NIT resultante de estudos do logo do Felicilab.

## **Escopo**

- [x] Adaptar tipografia para "Núcleo de Inovação e Tecnologia da Escola de Saúde Pública do Ceará"
- [x] Dispor de variação com contração "NIT"
- [x] Alinhar com Jorge
- [x] Dispor variações de aplicação em arquivos separados
- [x] Enviar ao e-mail do NIT

## Observações
Links de apoio e informações adicionais

**Comment by RaniGub** [comment]
@alesouza88

**Comment by alesouza88** [comment]
Demanda solicitada pela Clarissa através da Central de Chamados da ESP (OTRS)

Identificação do chamado: ESPCE#20220913586920 — Enviar logo do dente de leão com nome NIT
Link da solicitação: https://centraldesuporte.esp.ce.gov.br/otrs/index.pl?Action=AgentTicketZoom;TicketID=7784;ArticleID=27399#27369

![image](https://user-images.githubusercontent.com/87095371/190187988-dd922683-e62c-4192-8642-8c8731dec097.png)

**Comment by alesouza88** [comment]
@Rani ou @pauloamoreira, se possível depois só atualiza o escopo em relação à "Enviar para a Talita do NIT", pois conforme consta na solicitação, eles pedem para enviar ao e-mail do NIT: nit@esp.ce.gov.br.

**Comment by pauloamoreira** [comment]
.adaptação realizada. marcarei pareamento com @elpadrejorge para finalização.
![marca NIT -2022_vertical_COR_Padrão_fundobranco](https://user-images.githubusercontent.com/79201419/190192863-1a551338-e41a-47b2-a041-71a6687fa479.png)

![marca NIT -2022_horizontal_COR_Padrão_fundobranco](https://user-images.githubusercontent.com/79201419/190192908-c0448eed-8bf7-47bd-8fdd-2715e49f3a2c.png)

**Comment by pauloamoreira** [comment]
.após pareamento com @elpadrejorge, arquivos foram enviado para o email do NIT.

**Comment by RaniGub** [comment]
Adaptação concluída.
