### ISSUE TITLE
Disponibilização do cronograma de entregas | Ambiente Virtual da Oficina

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#419]
## **Objetivo**

**Como** designer
**Quero** disponibilizar o cronograma de entregas da oficina no ambiente virtual
**Para** deixar os participantes informados

## **Contexto**

- É preciso disponibilizar os achados da Oficina de Design de Serviços da ESP

## **Escopo**

- [x] Disponibilizar as informações fornecidas pelo time de produtos no ambiente virtual

## Observações
Links de apoio e informações adicionais

**Comment by elpadrejorge** [comment]
Em conversa com a @ericabpinho e o @edmirandajr , foi acordado que o título das entregas será história/necessidades. Alteração realizada.
