### ISSUE TITLE
Definir arquitetura para a Central

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/DesignLab#42]

**Comment by RaniGub** [comment]
Durante a Oficina de DSP foi realizada a Inception da Central de Informações. Alguns pontos precisam ser concluídos para que a AI seja implementada. Será criado um Épico onde a tarefa do presente card estará inclusa. Mais informações:
https://www.figma.com/file/Avf3SQNDfeglilqOoXXVEY/Agenda-de-Prioridades-2021-2022-SEPOS?node-id=373%3A3749
