### ISSUE TITLE
Informar da disponibilização das declarações | Ambiente Virtual da Oficina

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#420]
## **Objetivo**

**Como** designer
**Quero** informar sobre a disponibilização das declarações da Oficina
**Para** que os participantes possam programar a retirada

## **Contexto**

- É preciso disponibilizar os achados da Oficina de Design de Serviços da ESP

## **Escopo**

- [x] Criar um texto no ambiente virtual informando sobre a disponibilização dos certificados
- [x] Validar texto com a narrativas

## Observações
Links de apoio e informações adicionais

**Comment by RaniGub** [comment]
Aguardar posicionamento da Secretaria Acadêmica para disponibilizarmos as informações no site.

**Comment by RaniGub** [comment]
OFICINAS - DECLARAÇÃO DE PARTICIPAÇÃO
Se você participou de pelo menos 2 dias dos encontros na Biblioteca Estadual (BECE), você poderá buscar sua declaração de participação, em breve, no Felicilab. As declarações ficarão prontas ao longo do mês de outubro! Fique atento/a ao grupo da Oficina! Logo que as declarações ficarem prontas, avisaremos por lá!

@elpadrejorge já validado pela narrativas.

**Comment by elpadrejorge** [comment]
Texto atualizado e já disponível no link https://sus.ce.gov.br/felicilab/oficinadesignesp/
