### ISSUE TITLE
Esquema de como trabalhamos | Site do Felicilab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#421]
## **Objetivo**

**Como** designer
**Quero** criar um esquema gráfico 
**Para** disponibilizar a forma que o Felicilab trabalha no site do Felicilab

## **Contexto**

- Frente aos complexos esquemas que temos, é preciso dispor de um que comunique o fluxo de forma resumida

## **Escopo**

- [ ] Criar esquema

## Observações
Links de apoio e informações adicionais

**Comment by RaniGub** [comment]
Finalizado. Também informado na tarefa #94 das narrativas.

https://www.figma.com/file/95nbqM2JbGAOXPR0wTXs66/Metodologia-Felicilab-Set-2022

**Comment by edmirandajr** [comment]
fiz modificações no texto, com base em revisão de Paulo, segue link para documento cópia do original: https://docs.google.com/document/d/1cyfIrdNMj8UbwvU3l8N_5Kh2hbxq0JLbindjlPC0NH8/edit?usp=sharing

**Comment by RaniGub** [comment]
Acompanhar na issue #456
