### ISSUE TITLE
Atualização de Conteúdo | site Felicilab | Modelo de Governança Colaborativa

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#424]
**Como** designer
**Quero** atualizar o novo site do Felicilab com conteúdos desenvolvidos pelas narrativas
**Para** lançá-lo  até o fim do defeso eleitoral

## **Contexto**

O novo site do Felicilab está em sua fase final de desenvolvimento. Com isso, novas seções foram pensadas e o conteúdo de cada uma delas está em desenvolvimento pelo time de narrativas. Assim que cada conteúdo for entregue, a seção do site precisa ser atualizada e disponibilizada.

## **Escopo**

Modelo de Governança ( @edmirandajr )

Este modelo de governança está estruturado no figma e está bem desatualizado com as mudanças que tivemos. Entendemos que a atualização dele irá demandar um esforço de muitas pessoas. Para a V1, podemos colocar um texto resumido com um esquema gráfico simples de complemento.
Obs: usar resumo do texto "modelo de governança", +apresentação dos times, do guia do colaborador (link https://docs.google.com/document/d/18yo0c3Rmk4m-OkJpgONjabZjDBgkFwGzWYNzp_AvqyY/edit#heading=h.4aew84y14hw1). Acrescentar parágrafo contando como o Felicilab surgiu e, em seguida, a Ditec (resumo do artigo "por que nos chamamos").
Obs: - os pilares são colaboração, transparência e código aberto. Governança colaborativa x tripé - possibilidade de todos os entes envolvidos no processo terem igual peso de colaboração. Essa polifonia constitui o que a gente faz e um elemento muito caro ao nosso modelo de governança colaborativa. Tripé da inovação - múltiplo olhar até que algo seja desenvolvido. há ainda a noção apresentada pelo enap “O conceito de governança colaborativa surge com base em três fundamentações: a complexidade dos problemas públicos, a sociedade em rede e a ideia do estado em rede”, o link é esse:
https://www.enap.gov.br/pt/acontece/noticias/colaboracao-e-essencial-na-nova-governanca-publica

**Comment by RaniGub** [comment]
Tarefa substituida pela #455
