### ISSUE TITLE
Atualização de Conteúdo | site Felicilab | Métodos

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#426]
## **Objetivo**

**Como** designer
**Quero** atualizar o novo site do Felicilab com conteúdos desenvolvidos pelas narrativas
**Para** lançá-lo  até o fim do defeso eleitoral

## **Contexto**

O novo site do Felicilab está em sua fase final de desenvolvimento. Com isso, novas seções foram pensadas e o conteúdo de cada uma delas está em desenvolvimento pelo time de narrativas. Assim que cada conteúdo for entregue, a seção do site precisa ser atualizada e disponibilizada.

## **Escopo**

Métodos ( @ericabpinho )
Metodologias ágeis (ver no guia do colaborador, mas resumir consideravelmente). Breve história da board integrada. SCRUM/papeis. Cerimônias. Modelo híbrido/assíncrono - nossa construção (até o momento).
Ver o texto/modelo do Rani.

**Comment by edmirandajr** [comment]
atualizar o texto da metodologia integrada (site) adicionando as referências de métodos ágeis. Esse texto irá tanto para o guia quanto para o site @Clarisse1983

**Comment by ClarisCaval** [comment]
Concluí o texto. Aqui, para avaliação: 
https://docs.google.com/document/d/1mUDXs3IYS7D9iZlvnhK2mqi885GjpKO9F8g_FxYMZ7M/edit#

**Comment by ClarisCaval** [comment]
@elpadrejorge, a ideia é atualizar a seção do 'Como trabalhamos' a partir desse conteúdo. Quando puder, me chama para conversar?

**Comment by edmirandajr** [comment]
@edmirandajr vai ler e comentar sobre o texto. Importante observar como tornar o texto menos robusto para uma leitura mais adaptada a linguagem de um site

**Comment by edmirandajr** [comment]
fiz uma cópia para trabalhar numa nova versão https://docs.google.com/document/d/1cyfIrdNMj8UbwvU3l8N_5Kh2hbxq0JLbindjlPC0NH8/edit?usp=sharing
