### ISSUE TITLE
 Atualização de Conteúdo | site Felicilab | Imprensa

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#428]
## **Objetivo**

**Como** designer
**Quero** atualizar o novo site do Felicilab com conteúdos desenvolvidos pelas narrativas
**Para** lançá-lo  até o fim do defeso eleitoral

## **Contexto**

O novo site do Felicilab está em sua fase final de desenvolvimento. Com isso, novas seções foram pensadas e o conteúdo de cada uma delas está em desenvolvimento pelo time de narrativas. Assim que cada conteúdo for entregue, a seção do site precisa ser atualizada e disponibilizada.

## **Escopo**

Imprensa ( @edmirandajr )
Materiais disponíveis para jornalistas: release, indicadores, apresentação resumida (link https://docs.google.com/presentation/d/1CSHT-2CG2lQ8zQ4eZIeWAGG04jb19eQtUD2B4aLdN_A/edit#slide=id.g152eca28911_1_235). Logomarca, fotos de divulgação. Link para a linha do tempo. Link para o site da oficina.

**Comment by edmirandajr** [comment]
Segue link para documento com sugestão de texto: https://docs.google.com/document/d/10zfQTFs4x88Qo2Qcj9Txq79k-LsbeHAoid7x5mFJSzk/edit?usp=sharing @elpadrejorge @ericabpinho

**Comment by edmirandajr** [comment]
O texto foi validado pelo Time de Narrativas
https://docs.google.com/document/d/10zfQTFs4x88Qo2Qcj9Txq79k-LsbeHAoid7x5mFJSzk/edit?usp=sharing

@elpadrejorge
