### ISSUE TITLE
Atualização de Conteúdo | site Felicilab | Falaram de nós

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#429]
## **Objetivo**

**Como** designer
**Quero** atualizar o novo site do Felicilab com conteúdos desenvolvidos pelas narrativas
**Para** lançá-lo  até o fim do defeso eleitoral

## **Contexto**

O novo site do Felicilab está em sua fase final de desenvolvimento. Com isso, novas seções foram pensadas e o conteúdo de cada uma delas está em desenvolvimento pelo time de narrativas. Assim que cada conteúdo for entregue, a seção do site precisa ser atualizada e disponibilizada.

## **Escopo**

Falaram de nós ( @edmirandajr )
Matérias em sites, jornais, artigos.

**Comment by edmirandajr** [comment]
texto para validação: https://docs.google.com/document/d/1Oy306ZkX77k4Wyx0ic9bUKeOJ9mlfEFVBFH5QK9FiOU/edit?usp=sharing

@elpadrejorge @ericabpinho
