### ISSUE TITLE
Plug-in de menu | Site Felicilab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#432]
## **Objetivo**

**Como** designer
**Quero** instalar e configurar um plug-in de menu
**Para** disponibilizar experiência adequada de navegação

## **Contexto**

- O site do Felicilab está em seu processo final de desenvolvimento. Até o fim do defeso eleitoral, o seu novo design precisa estar no ar. Neste processo, alguns plugins precisam ser instalados para garantir o seu bom funcionamento e a segurança.

## **Escopo**

- [x]  Instalar menu no ambiente de homologação
- [x] Configurar menu

**Comment by elpadrejorge** [comment]
Menu instalado e configurado. Falta refinar com o @RaniGub

**Comment by RaniGub** [comment]
Vamos refinar com o Junim na semana que vem, amanhã verifico o que podemos melhorar (se conseguimos).

**Comment by RaniGub** [comment]
Plug-in inserido e validado no ambiente de homologação. Resta apenas um pequeno refinamento da paleta do botão "Bora Inovar" pelo time de design. O alinhamento será atendido em outra tarefa. Será atendido na revisão final do site.
