### ISSUE TITLE
Projeto Gráico da Revista Felicilab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#433]
## **Objetivo**

**Como** designer
**Quero** criar o projeto gráfico da Revista Felicilab
**Para** reunir as informações institucionais do laboratório

## **Contexto**

- Com o movimento da Prestação de Contas do Felicilab, se evidenciou a necessidade de artefato impresso com informações institucionais do Laboratório. O conteúdo deve evidenciar de forma resumida: indicadores, metodologias etc.

## **Escopo Time de Design**
- [x] Projeto Gráfico da Revista

**Comment by RaniGub** [comment]
@elpadrejorge vc pode atualizar como tá o processo?

**Comment by elpadrejorge** [comment]
O grid modular já foi feito e validado com o @edmirandajr , assim como os estilos de parágrafo e caractere. O texto está sendo finalizado pelas narrativas. Em pareamento feito próximo do meio dia de hj (28/9) com o @edmirandajr , alinhamos as imagens com os filtros para ilustrar a revista e inicio agora a tarde a produção da capa e contracapa da revista.
