### ISSUE TITLE
Rever páginas que ficaram off no Defeso Eleitoral

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#439]
## **Objetivo**

**Como** designer
**Quero** rever páginas do SUS.CE em off
**Para** reativa-las após o defeso

## **Contexto**

- Com o fim do Defeso Eleitoral, as páginas do SUS.CE precisam voltar a ser visualizadas.

## **Escopo**

- [x] Rever páginas em rascunho

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

## Observações
Links de apoio e informações adicionais

**Comment by elpadrejorge** [comment]
Páginas já estão no ar.
