### ISSUE TITLE
Refinar campos "Especialidade" e "Área de atuação" dentro da arquitetura e atribuir base.

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/DesignLab#44]
Objetivo:
Ter mapeadas as especialidades e áreas de atuação do Mapas

Contexto:
A equipe do mapas está criando taxonomias para poder construir as oportunidades, eventos e projetos dentro da plataforma. Contudo isso deve ser mapeado para não impactar na experiência do usuário no cadastro de outros produtos.

Escopo: 

- [ ] Alinhamento com PM do Mapas
- [ ] Alinhamento com o PM do id Saude
- [ ] Alinhamento com o PM do iSUS
- [ ] Atualização dos dados na arquitetura do MIRO

Critério de Aceite:
Dado que o usuário altere seus dados de especialidade e área de atuação em qualquer produto do Felicilab
Quando ele acessa os campos de cadastro ou edição
A experiência do usuário é a mesma

**Comment by RaniGub** [comment]
Essa tarefa foi atualizada e será encerrada. Integra agora o card 'Fluxo de Cadastro do Trabalhador da Saúde #78'.
