### ISSUE TITLE
Folder de apresentação do Felicilab

### ISSUE THREAD

**Issue by elpadrejorge** [EscolaDeSaudePublica/DesignLab#445]
## **Objetivo**

**Como** designer
**Quero** desenvolver um folder de apresentação do Felicilab  
**Para** disponibilizar um impresso que apoie as apresentações do laboratório a visitantes e cargos estratégicos

## **Contexto**

- Com o fim do defeso eleitoral e o novo contexto do Felicilab, surgiu a necessidade de elaborar um impresso que apoie a apresentação do laboratório, contendo as principais informações do lab e seus indicadores.

## **Escopo**

- [x] Definir o conteúdo que será inserido no Folder
- [x] Definir o layout do folder
- [x] Diagramar o conteúdo
- [x] Refinar o andamento com narrativas e design
- [x] Revisar e fechar arquivo para impressão

## Observações
Links de apoio e informações adicionais

**Comment by elpadrejorge** [comment]
Em reunião com @Clarisse1983, @uira e @edmirandajr, ficou definido o conteúdo a ser produzido e inserido no folder. Após a constatação do tamanho do conteúdo previsto, foi informado que o tamanho do folder na estrutura A3 não seria suficiente. @uira solicitou que o layout fosse pensado no tamanho A2, ciente da necessidade da impressão offset e do tempo de produção da gráfica de ao menos 2 semanas, além do mínimo de impressões de 1000 unidades. Hoje (18/10), inicio os testes de prototipagem do layout do folder.

**Comment by elpadrejorge** [comment]
A diagramação da parte da frente já foi finalizada. Restam alguns conteúdos para a finalização da diagramação do verso, que já foram alinhadas com o time de narrativas. Foi impresso um mockup, ontem (26/10), para validar as dobras e o tamanho de fontes.

**Comment by elpadrejorge** [comment]
O folder do Felicilab foi impresso em seu mvp1 na gráfica digital Original. Foram feitas 10 unidades, a 16,50 cada. Ficou a recomendação do @uira de utilizar uma gramatura menor para a produção, para que as dobras fiquem mais baixas. Neste sábado, @Clarisse1983 e @uira fizeram correções e melhorias com base neste mvp1 que já foram realizadas. Porém, @uira ainda evidenciou que gostaria de realizar mais algumas alterações.

**Comment by RaniGub** [comment]
Versão 1 concluída.
