### ISSUE TITLE
Artigo | Design na Construção de Políticas Públicas

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#446]
## **Objetivo**

**Como** design de experiência  
**Quero** escrever artigo científico sobre o design de serviços aplicado à construção de políticas públicas  
**Para** compartilhar conhecimento e documentar as experiências vivenciadas pelo time de design do Felicilab.

## **Contexto**
- O artigo vai apresentar os primeiros passos para construção de políticas públicas com o uso do Design de Serviços na construção de Políticas Públicas da SEPOS, citando com quais coordenadorias foram realizadas as oficinas, com destaque para uma delas.

## **Escopo**
- [x] criação de sumário
- [x] validação do sumário com líder do Time de Design
- [x] análise dos referenciais teóricos levantados

## Observações
Observações de @RaniGub sobre o sumário enviado.
1) finalizar o mvp1 do artigo apresenta ao Jorge e depois para a Claris.
Guia de submissão: http://www.pgdesign.ufrgs.br/arquivos/template2019_3.docx

O artigo vai apresentar os primeiros passos para construção de políticas públicas com o uso do design, você não deve se preocupar em abordar com detalhes todas as oficinas. Deve citar com quais coordenadorias foram realizadas e se aprofundar no discurso de uma que achar que foi mais rica em detalhes.

- Introdução - Definições gerais de como as políticas funcionam hoje e como deveriam funcionar (centradas no usuário/transformação digital e governança colaborativa), citar algum caso conhecido (brasil ou fora) do uso do design para construção de políticas com enlaces do Design, justificativa, questões norteadoras ou hipóteses.
- Objetivo geral e específicos (passos que você atingiu o objetivo geral)
- Políticas Públicas no Contexto do SUS/CE
- Como são criadas as Políticas Públicas na SESA (Acho que aqui vai servir de conteúdo para o item anterior)
- Transformação Digital, Governança Digital e Governança Colaborativa (Criar título)
- Design de Serviços aplicado nas Políticas Públicas em Saúde
- Metodologia (Definição do tipo de estudo.... Passos para realização das oficinas)
- Contribuição do design para construção de políticas públicas (Resultados e discussão)
- Conclusão
- Desdobramentos

Links de apoio e informações adicionais
Texto em processo de elaboração: https://docs.google.com/document/d/1qEc3n50dxduUeLDTGnS4vMiaFxqTWWkqnO23uJ84Ik8/edit?usp=sharing

**Comment by RaniGub** [comment]
@pauloamoreira conclui a primeira parte da revisão, quarta voltamos a conversar sobre ele. Vou iniciar o desenho do processo metodológico com referências.

**Comment by RaniGub** [comment]
Revisão 2 concluída, comentários adicionados.

**Comment by pauloamoreira** [comment]
.aperfeiçoamentos inseridos. aguardando novo pareamento com @RaniGub .

**Comment by RaniGub** [comment]
Faltam a introdução e o capítulo da metodologia. Após isso, passarão pelas contribuições da Clarisse e Uirá.
