### ISSUE TITLE
Desenhar campos de informação no Mapa da Saúde

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/DesignLab#45]
Verificar com a equipe do Mapas os seguintes grupos de informação:
- [ ] Nome Completo (Sincronização com id Saúde)
- [ ] Área de Atuação
- [ ] Especialidade

**Comment by RaniGub** [comment]
Essa tarefa foi atualizada e será encerrada. Integra agora o card 'Fluxo de Cadastro do Trabalhador da Saúde #78'.
