### ISSUE TITLE
criação dos ambientes de publicação Oficina ESP x Planos de Ação do Planejamento Estratégico

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#459]
## **Objetivo**

**Como** designer de experiência
**Quero** criar boards para visualização pública online dos relacionamentos entre os achados da Oficina ESP e os Planos de Ação do Planejamento Estratégico  
**Para** dar transparência ao resultado do processo 

## **Contexto**

- O ocasião da criação de um board com a visão do relacionamento entre os achados nas Oficinas ESP e os planos de ação do Planejamento Estratégico da ESP, se faz necessário disponibilizar os resultados em plataforma online de acesso público, para garantir a transparência e controle social.

## **Escopo**

- formatar os boards criados em boards individuais - um para cada objetivo estratégico
- aperfeiçoar a disposição dos elementos para facilitar a compreensão.
- validar com líder do Time de Design
- disponibilizar arquivos para publicação pública online

## Observações
Boards do processo original: https://www.figma.com/file/0QO3AjlxZqUNnHQbCXXKht/Match-Clusters-(Felicilab)-e-Planos-de-A%C3%A7%C3%A3o-(ADINS)?node-id=121%3A6301&t=8mQ6VYNnJ0VTGF6Y-1
Board de relacionamento com objetivo estratégico GOVERNANÇA E GESTÃO: encurtador.com.br/kswOP
Board de relacionamento com objetivo estratégico RESULTADOS PARA A SOCIEDADE E CLIENTES:
encurtador.com.br/doyLU
Board de relacionamento com objetivo estratégico SUSTENTABILIDADE FINANCEIRA:  encurtador.com.br/GNVZ6
Board de relacionamento com objetivo estratégico APRENDIZADO E CRESCIMENTO: encurtador.com.br/gNOQ5
Board de relacionamento com objetivo estratégico TECNOLOGIA E PROCESSOS: encurtador.com.br/nAIU6

**Comment by pauloamoreira** [comment]
.tarefa finalizada.

**Comment by pauloamoreira** [comment]
.aguardando análise do @RaniGub .

**Comment by pauloamoreira** [comment]
.aperfeiçoamentos solicitados por @RaniGub realizados. boards atualizados.

**Comment by RaniGub** [comment]
Revisado e entregue.
