### ISSUE TITLE
Rever com a Infra o processo de limpeza dos snapshots no sus.ce

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/DesignLab#46]
Uma vez que faremos uma grande quantidade de snapshots dentro da máquina do sus.ce.gv.br, solicitamos à infra que possamos encontrar uma forma da equipe do Felicilab realizar a limpeza de versões anteriores.

**Comment by wforte88** [comment]
@danielgula Recordo que alinhamos com o Wandson a existência de até cinco snapshots. Podemos fechar essa tarefa?

**Comment by danielgula** [comment]
Sim, acredito que podemos! Até porque o importante é gerar os primeiros modelos em homologação dos próximos projetos e testar isso para avaliar se o processo atende.
