### ISSUE TITLE
Artigo | Design na Construção de Políticas Públicas - Introdução

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#461]
## **Objetivo**

**Como** design de experiência  
**Quero** escrever artigo científico sobre o design de serviços aplicado à construção de políticas públicas  
**Para** compartilhar conhecimento e documentar as experiências vivenciadas pelo time de design do Felicilab.

## **Contexto**
- O artigo vai apresentar os primeiros passos para construção de políticas públicas com o uso do Design de Serviços na construção de Políticas Públicas da SEPOS, citando com quais coordenadorias foram realizadas as oficinas, com destaque para uma delas.

## **Escopo**
- [x] Introdução
- [x] Revisão Introdução

## Observações
Links de apoio e informações adicionais
Texto em processo de elaboração: https://docs.google.com/document/d/1qEc3n50dxduUeLDTGnS4vMiaFxqTWWkqnO23uJ84Ik8/edit?usp=sharing

**Comment by RaniGub** [comment]
@Clarisse1983 é esse o artigo.

**Comment by ClarisCaval** [comment]
Eu li e fiz alguns comentários. Se vcs concordarem, posso dar um gás nessas alterações propostas. Me digam o que acham. Bjs.

**Comment by RaniGub** [comment]
@Clarisse1983 já li seus comentários, concordo demais. Resumi bem o capítulo de metodologia e já está no ponto.

**Comment by ClarisCaval** [comment]
Aeeee, finalizei hj minhas contribuições no artigo. Precisa agora ver se faz sentido o que coloquei lá e revisar as referências <3
