### ISSUE TITLE
Organização dos boards do Miro (NIT)

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/DesignLab#47]
Os boards do Miro com a conta do NIT devem ser reorganizados para a seguinte estrutura:

NIT - boards táticos do NIT
Design Lab - boards do Designlab
WIP Boards - demais boards de rascunhos, versões antigas

**Comment by RaniGub** [comment]
O desenvolvimento das boards está sendo migrado para o Figma e organizado por projetos/produtos. Ainda há necessidade dessa organização?

**Comment by wforte88** [comment]
Verificar possibilidade de migrar tudo para o Figma. Não temos perspectiva de contratação do Miro.

**Comment by danielgula** [comment]
Totalmente possível! Acredito que com a oficina de Design de Serviços e outras iniciativas de design o Figma atenderá aos objetivos. Como tem muita coisa antiga por lá podemos ver uma tarefa para seleção/migração do que está lá.

**Comment by RaniGub** [comment]
@danielgula podemos ver se há realmente a necessidade disso, pois vai demandar um esforço de trabalho que poderia estar sendo empregado em um card prioritário. Essa demanda é de média para baixa prioridade.
