### ISSUE TITLE
Discovery Identidade FeliciLab

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/DesignLab#54]
### Objetivo
**Como** designer
**Quero** ter mais informações sobre a identidade do FeliciLab
**Para** compreender melhor o posicionamento da marca

### Contexto
A marca do FeliciLab foi criada após o primeiro inception do laboratório. Contudo, não houve um trabalho de consolidação da identidade, que hoje flutua no imaginário dos integrantes do grupo a partir de diversas referências. Esta tarefa busca coletar dados para descobrir as nuances em torno da imagem do FeliciLab.

### Escopo
- [x] Recuperar dados de inceptions e planejamentos estratégicos anteriores
- [x] Realizar pesquisa de percepção da persona FeliciLab com os integrantes do laboratório
- [x] Consolidar dados coletados para análise

### Observações
[Onboarding](https://docs.google.com/presentation/d/1AWur41KchbAGgtTJI75qWolGYabde3DByWLFI41s9eU/edit?usp=sharing)
[Editorial Site FeliciLab](https://docs.google.com/document/d/1IGCe-kQh5ZpBSmG_licV1UHkyv0HbsWnd0r_KkWnjno/edit?usp=sharing)
[Inception NIT/FeliciLab](https://miro.com/app/board/o9J_knQYK4M=/?moveToWidget=3074457354889070026&cot=14)
[Artigo (Relato de experiência)](https://docs.google.com/document/d/1WcI7Vh4V5yNLkqldgRffTvDqWUOH0PX8zjxilrp1qW0/edit?usp=sharing)

**Comment by sigachiconeto** [comment]
Verificamos que 60% dos integrantes responderam o questionário. Consolidamos percentual vinculado à data de entrada no FeliciLab. Visualizamos as 22 respostas. Prototipamos, com sucesso, a organização dos resultados em uma nuvem de palavras usando a ferramenta Tag Cloud. Identificamos a possibilidade de organizar as personalidades por idade e gênero.

Para a próxima reunião será necessário organizar as respostas das personalidades:
– Transformar termos em palavras.
– Usar uma única classe gramatical
– Convergir sinônimos em uma única palavra, preferindo a linguagem simples.
– Submeter os resultados à Tag Cloud.
– Retornar às personalidades e identificar aquela que mais de aproxima dos adjetivos mais citados.

A convergência será resumida em uma ou duas personalidades com nome, idade e cinco atributos chave.Podemos utilizar duas opções para aprendizado e escuta ativa junto ao comitê.

Com a definição e validação da celebridade, a seguir, haverá a criação da Brand Persona do Felicilab, adequando e ampliando as características como, por exemplo, é cearense, a profissão, formação, estado civil etc, semelhante a uma buyer persona.

Com a Brand Persona definida, documentada e validada junto ao comitê, o PubliciLab e o DesignLab poderão partir para a criação da marca gráfica e tom de voz.

**Comment by pauloamoreira** [comment]
Dados consolidados disponíveis no Miro: https://miro.com/app/board/o9J_lR2-1ZQ=/?moveToWidget=3074457355193707940&cot=14
