### ISSUE TITLE
Pesquisa de similares - Bookmark OS

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/DesignLab#56]
## **Objetivo**

**Como** Designer  
**Quero** Pesquisar referências de marcas de laboratórios similares ao FeliciLab
**Para** Colaborar com a construção da Identidade do FeliciLab, reunindo referências de elementos visuais, como: tipografias, símbolos, ícones, grafismos, cores, entre outros, de iniciativas nacionais e internacionais com perfil similar.  

## **Contexto**

- A Pesquisa de Similares é um estágio previsto no Processo Metodológico, item Problematização, subitem Pesquisa de Similares/Matriz de Marca, conforme o diagrama [Processos para Identidade e Design System](https://miro.com/app/board/o9J_kvAuOls=/?moveToWidget=3074457354864187890&cot=14).  

## **Escopo**

- [x] Realizar Pesquisa Exploratória de Laboratórios Nacionais Internacionais com perfil de Inovação 
- [x] Criar perfil na plataforma [Bookmark OS](https://bookmarkos.com/) com pasta compartilhada com o Grupo de Trabalho
- [x] Copilar Marcas para um moodboard na pasta compartilhada, estabelecendo critérios de categorização (segmentação, abrangência de atuação, natureza institucional, entre outros). 
- [x] Sistematizar resultados, apontando incidência de elementos visuais e recorrências.
- [x] Transcrever visualmente os dados para síntese, sugestões e apontamentos.

## Observações
Links de apoio e informações adicionais

**Comment by RaniGub** [comment]
Disponível em https://miro.com/app/board/o9J_lR2-1ZQ=/
