### ISSUE TITLE
Protótipo 0 do Manejo Clínico - Fase 01

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#63]
## **Objetivo**

**Como** designer  
**Quero** desenvolver um protótipo
**Para** Manejo Clínico COVID-19

## **Contexto**

Após finalização da tarefa #61, será desenvolvido um protótipo de alta fidelidade no Wordpress do Manejo Clínico. Esse momento está relacionado somente com o nível 0 de informações e faz parte da Fase 01 projetada no plano de desenvolvimento (MIRO).

## **Escopo**
- [x] Protótipo em alta fidelidade Mobile - Wordpress
- [x] Protótipo em alta fidelidade Desktop - Wordpress

## Observações
Links de apoio e informações adicionais
Site atual
https://coronavirus.ceara.gov.br/profissional/manejoclinico/
AI
https://miro.com/welcomeonboard/L0kGOWfYfsv6zPEaGC1Itn07P7dE0k2saCxxWxn8wnRNc0OTQIMZegAWdWiUeVnp

**Comment by wforte88** [comment]
Protótipo 0 finalizado. Disponível para revisão em http://dev.servicos.ws/sus.ce/manejocovid19/
