### ISSUE TITLE
Ideação - Identidade Felicilab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#64]
## **Objetivo**

**Como** designer  
**Quero** gerar ideias e explorar aplicações
**Para** ter a definição da assinatura visual do Felicilab

## **Contexto**
Frente à conclusão da fase de problematização da identidade do Felicilab, devemos interpretar as informações coletadas para geração de ideias acerca de sua representação visual.

## **Escopo**

- [x] Processo de naming
- [x] Aplicar formulário de percepção sobre felicidade
- [x] Brainstorming/Definir características essenciais
- [x] Explorar aplicações (Símbolos, Família tipográfica, cores, elementos complementares e resistência)
- [x] Tagline
- [x] Refinamento da solução

## Observações
https://miro.com/welcomeonboard/L0kGOWfYfsv6zPEaGC1Itn07P7dE0k2saCxxWxn8wnRNc0OTQIMZegAWdWiUeVnp

**Comment by wforte88** [comment]
### Reunião de refinamento da ideação

**OP01**
Mais próxima de saúde, educação, cores efervescentes simbolizam bem a dinâmica das atividades.

**OP02**
Conceito dialoga com os valores do FeliciLab, espalhamento, rede, liberdade.

**Uirá**
- Elemento arco-íris enquanto símbolo;
- Testar: círculo com arco-íris, somente esporos e caule orgânico;
- Referência de aplicações web: Google e Facebook.

**Victor**
- Testar esporos no cérebro

**Clarisse**
- Sugestão de teste cego
