### ISSUE TITLE
Criar protótipo de podcast para uso do DaVinci Resolve

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/DesignLab#71]
## **Objetivo**

**Como** designer
**Quero** ter um protótipo de edição audiovisual
**Para** dinamizar os processos de trabalho

## **Contexto**

O DaVinci Resolve é uma ferramenta gratuita de edição audiovisual que permite uso colaborativo e online de seus projetos. Precisamos estudar e construir um ambiente para uso dessa ferramenta nos produtos que criamos na ESP. O primeiro passo é criar um produto a partir do programa e documentar os processos e fluxos de uso

## **Escopo**

- [ ] configurar ambiente local da ferramenta
- [ ] refazer um episódio do podcast Cuida! no Resolve
- [ ] criar tutorial de criação de podcast do Cuida
- [ ] documentar necessidades para criação de ambiente colaborativo online

## **Critérios de Aceitação**

**Dado que** vou editar um vídeo e/ou áudio
**Quando** entro no ambiente do Resolve
**então** consigo construir um projeto e exporta-lo

**Comment by RaniGub** [comment]
Prioridade média.

**Comment by ClarisCaval** [comment]
@danielgula, bora conversar sobre isso aqui?

**Comment by danielgula** [comment]
@Clarisse1983 no modo de ver essa demanda pode ser fechada, uma vez que temos as licenças de uso do Pacote Adobe e usamos o Adobe Audition para criarmos o Cuida.

**Comment by danielgula** [comment]
Em acordo com @Clarisse1983 essa demanda será encerrada.
