### ISSUE TITLE
Vídeo com entrevistas sobre o iSUS

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/DesignLab#73]
## **Objetivo**

**Como** usuário
**Quero** acessar o Youtube do Felicilab
**Para** ver depoimentos de profissionais que trabalharam no iSUS

## **Contexto**

O Ciêncialab está criando um capítulo de livro com conteúdo transmidiático sobre o iSUS. Um QRcode irá acessar um link do Youtube com depoimentos de profissionais que trabalharam no desenvolvimento do app. 

### **Ciêncialab**
- [x] Realizar curadoria dos depoimentos
- [x] Organizar roteiro do vídeo (chamadas e legendas)
- [x] Disponibilizar pasta com arquivos
- [ ] Gerar QRcode a partir do link do Youtube

### **Designlab**
- [x] Criar projeto do vídeo
- [x] Exportar versão em vídeo para o formato do Youtube

### **Publicilab**
- [ ] Criar link no Canal do Youtube

## **Critérios de Aceitação**

**Dado que** acesso a publicação do iSUS
**Quando** escaneio o QRcode
**Então** acesso o vídeo dos depoimentos do iSUS

## Observações
Links de apoio e informações adicionais

**Comment by drmarcos** [comment]
Perfeito @danielgula

**Comment by ClarisCaval** [comment]
Qual a diferença entre exportar a versão para o Youtube e criar link no canal?

**Comment by danielgula** [comment]
> Qual a diferença entre exportar a versão para o Youtube e criar link no canal?

Pronto @Clarisse1983, melhorei o texto para "Exportar versão em vídeo para o formato do Youtube". Designlab gera o vídeo e Publicilab posta no canal (ou alguém que tenha acesso).

**Comment by geniltonfaheinajr** [comment]
> ## **Objetivo**
> **Como** usuário
> **Quero** acessar o Youtube do Felicilab
> **Para** ver depoimentos de profissionais que trabalharam no iSUS
> 
> ## **Contexto**
> O Ciêncialab está criando um capítulo de livro com conteúdo transmidiático sobre o iSUS. Um QRcode irá acessar um link do Youtube com depoimentos de profissionais que trabalharam no desenvolvimento do app.
> 
> ## **Escopo**
> ### **Ciêncialab**
> * [ ]  Realizar curadoria dos depoimentos
> * [ ]  Organizar roteiro do vídeo (chamadas e legendas)
> * [ ]  Disponibilizar pasta com arquivos
> * [ ]  Gerar QRcode a partir do link do Youtube
> 
> ### **Designlab**
> * [ ]  Criar projeto do vídeo
> * [ ]  Exportar versão em vídeo para o formato do Youtube
> 
> ### **Publicilab**
> * [ ]  Criar link no Canal do Youtube
> 
> ## **Critérios de Aceitação**
> **Dado que** acesso a publicação do iSUS
> **Quando** escaneio o QRcode
> **Então** acesso o vídeo dos depoimentos do iSUS
> 
> ## Observações
> Links de apoio e informações adicionais

Muito bom, Daniel! Os relatos em vídeo estão em uma pasta do Drive. Vou passar logo pra vc .

**Comment by ClarisCaval** [comment]
@danielgula, achei bacana o vídeo, tenho só duas observações: sugiro alterar a fonte que vc escolheu para destacar os trechos das falas pra uma fonte mais usual nas redes sociais (te passei uma referência pelo telegram) e baixar mais o bg durante as falas das pessoas (achei muito alto).

**Comment by danielgula** [comment]
Alterações efetuadas no vídeo, que se encontra pronto para ser enviado para o Youtube. O arquivo se encontra dentro da pasta do projeto no Ciêncialab
