### ISSUE TITLE
Refinamento final da Assinatura Visual

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#77]
## **Objetivo**

**Como** designer  
**Quero** utilizar de técnicas de grid e experimentações
**Para** refinar a Assinatura Visual selecionada

## **Contexto**

Em 30/06/21 foi apresentado ao Grupo Tático do Felicilab o resultado do teste de compreensibilidade dos símbolos das propostas de Assinatura Visual. Feitas as devidas considerações técnicas e limitações, o grupo decidiu que a Assinatura do Dente-de-Leão com Fluxo Expandido é a solução que passará pela etapa final de refinamento.

## **Escopo**

- [x] Refinamento dos elementos básicos
- [x] Refinamento da paleta de cores
- [x] Refinamento da proporção em Grid
- [x] Experimentos de resistência à redução
- [x] Experimentos de resistência em fundos coloridos/inconstantes
- [ ] Validação

## Observações
https://docs.google.com/presentation/d/1lPLYLYnY7bCwyVYQOWq3kMRrpomvAD_kv70SU9yXBQs/edit?usp=sharing

**Comment by RaniGub** [comment]
Enviado e-mail para ASCOM dia 27/09/2021, 14:20, formalizando solicitação de avaliação técnica das propostas.

**Comment by RaniGub** [comment]
Atualização: Sem retorno da ASCOM até o momento.

**Comment by RaniGub** [comment]
Resposta ASCOM:
![Captura de Tela 2021-10-07 às 09 41 27](https://user-images.githubusercontent.com/79097920/136385991-497a542a-4e8e-4323-ba6c-667740769311.png)

**Comment by uira** [comment]
@RaniGub Isso aqui, havíamos combinado de definir um prazo e se ASCOM não pudesse cumprir, avancariamos sem eles.

Nesse caso, chegamos na metade de outubro, e ainda não temos um prazo.

Por favor, Rani, liga pra Ariane, explica que se não puder ser feito até sexta, faremos sem eles.

**Comment by RaniGub** [comment]
![Captura de Tela 2021-11-25 às 14 43 15](https://user-images.githubusercontent.com/79097920/143484298-51d2eb32-71d7-47ee-ac2c-3a9367babc0a.png)

**Comment by RaniGub** [comment]
Encaminhamento: Serão realizados mínimos incrementos no Logotipo atual (com sorriso) e desenvolvimento do Manual com diretrizes de aplicação pelos novos bolsistas do edital 26/2021.
