### ISSUE TITLE
Oficina de Design de Serviços Públicos

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#83]
## **Objetivo**

**Como** designer  
**Quero** ministrar uma oficina de Design Thinking
**Para** colaborar com a institucionalização do Design nas Políticas da Sesa

## **Contexto**

Frente a Agenda de Prioridades 2021-2022 da Secretaria Executiva de Políticas de Saúde (SEPOS), surgiu a necessidade de ofertar uma Oficina de Design de Serviços Públicos para as coordenadorias das Políticas de Saúde da Sesa. O referido instrumento tem a 'solução/produto' como foco, sem considerar um modelo transversal de soluções que podem partir de um conjunto de problemas eventualmente interligados.

## **Escopo**

- [x] Sistematização dos participantes e áreas
- [x] Definição dos conteúdos
- [x] Desenvolvimento de material de divulgação
- [x] Definição da metodologia e etapas
- [x] Definição do material de operacionalização (organizacional, itens de consumo e infraestrutura necessária)
- [x] Produção de recursos de apoio (slides, programação, formulário de avaliação)
- [x] Aprovação do Material de apoio
- [x] Automação da Matriz GUT
- [x] Definição dos papéis dos facilitadores (Paulo, Daniel, Rani e mais um a ser definido)
- [x] Refinamento 1 com stakeholders
- [x] Refinamento 2 com stakeholders
- [x] Refinamento 3 com stakeholders

## Observações
Links de apoio e informações adicionais
https://docs.google.com/document/d/1_IiyEwx2dhK-9_keiBNyX1hRnJeNU3uktc0E_-heu80/edit?usp=sharing
Link para pasta com recursos de apoio produzidos
https://drive.google.com/drive/folders/1HmjLTSlp032D3eLyBSixFTwSS3PiN-Zy?usp=sharing

**Comment by pauloamoreira** [comment]
@Clarisse1983 segue layout para divulgação da oficina (esse material foi disponibilizado no drive do PubliciLab). fica faltando o PubliciLab produzir o texto para a legenda e agendar as publicações de divulgação. para quaisquer dúvidas, estou à disposição.
![OficinaDesignServicoPublico-quadrada-Instagram_Telegram_7](https://user-images.githubusercontent.com/79201419/127507882-0b594ece-106a-47ad-add9-b57fd8480c8f.png)

**Comment by RaniGub** [comment]
Aguardando aprovação do layout das placas de sinalização.
![Plaquinhas_Prancheta 1](https://user-images.githubusercontent.com/79097920/127906304-6e76f65a-e43c-4b99-b94f-6e45dbefb2eb.png)

**Comment by ClarisCaval** [comment]
Ei Paulo! Dando um retorno aqui sobre a arte. Acho que o miolo tem
muuuuitaaa informação, é bastante emaranhado, e não diz muito sobre o que é
a Oficina. Vamos tentar fazer uma coisa mais simples? E depois vi que Rani
fez uma proposta para as sinalizações que já é uma outra coisa, com outros
elementos. Precisamos de uma identidade geral pro evento.

Em qua., 28 de jul. de 2021 15:18, Paulo Amoreira ***@***.***>
escreveu:

**Comment by RaniGub** [comment]
@Clarisse1983 você tem razão. Vendo pelo celular fica menos perceptível e é algo simples de ser resolvido. Hoje nos concentramos mais no geral, amanhã podemos ver esses detalhes e unificar. Teremos refinamento no final da tarde.

**Comment by pauloamoreira** [comment]
@Clarisse1983 segue nova 
![OficinaDesignServicosPublicos](https://user-images.githubusercontent.com/79201419/128233181-64d0a41f-d8ab-47a2-93f6-f7c1b3fdd3e4.png)
proposta de card para mídias sociais e aplicativos de comunicação, para aprovação:

**Comment by uira** [comment]
@pauloamoreira Muda a Data, paulo, pra 11 a 13

**Comment by pauloamoreira** [comment]
@Clarisse1983 e @uira segue novo layout, com data corrigida:
![OficinaDesignServicosPublicos](https://user-images.githubusercontent.com/79201419/128261374-584058ea-e0ad-41fe-abff-06a446ce8369.png)
