### ISSUE TITLE
Feedback dos participantes | Oficina DSP

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#95]
## **Objetivo**

**Como** designer  
**Quero** receber o feedback dos participantes
**Para** compreender os pontos positivos e negativos da Oficina DSP

## **Contexto**

Na Oficina de Design de Serviços Públicos foi possível vislumbrar uma série de integrações entre as possíveis soluções da Agenda de Prioridades 2021-2022 da Sepos. Em vista disso, faz-se necessário a consolidação das informações em um único documento contributivo para norteamento e tomada de decisões da gestão das Políticas do SUS-CE.

## **DesignLAB**

- [x] Desenvolver um Forms para avaliação da Metodologia, Estrutura e Organização
- [x] Validar com Uirá
- [x] Enviar aos participantes (?)

## **PubliciLAB**
- [x] Validar com Clarisse

## Observações
https://www.figma.com/file/Avf3SQNDfeglilqOoXXVEY/Agenda-de-Prioridades-2021-2022-SEPOS?node-id=0%3A1

**Comment by pauloamoreira** [comment]
@RaniGub criei uma proposta de Formulário de avaliação, para validação: https://docs.google.com/forms/d/1dWcrn27PYCE8nG4HupCWMaiAZ1JrSJNHNE95CWb7lJg/edit?usp=sharing

**Comment by RaniGub** [comment]
Oi @Clarisse1983. Acabei de adicionar você como editora do formulário de avaliação da Oficina. Não consigo adicionar o PubliciLAB na tarefa porque vocês não tem repositório no ZenHub. Quando você concluir é só me avisar que encerro a tarefa. Queria saber como se dá o processo de envio do link para os participantes. É o PubliciLAB que faz?
