### ISSUE TITLE
Refinamento da Assinatura Visual do Centro de Inteligência - CISEC

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#97]
## **Objetivo**

**Como** designer  
**Quero** refinar a Assinatura Visual do Centro de Inteligência
**Para** nortear a criação do Manual de Identidade

## **Contexto**
Visto que a opção do "Cérebro Fractal" foi aceita para representação do Centro de Inteligência em Saúde do Estado do Ceará, é necessário que a solução (já em circulação de forma inadequada) receba pequenos ajustes visuais para que a demanda do Manual de Identidade seja solicitada à Ascom/ESP-CE.

## **Escopo**

- [x] Refinamento Visual do Cérebro Fractal
- [x] Briefing do Centro de Inteligência
- [x] Criar a demanda para desenvolvimento do Manual de Identidade pela Ascom/ESP-CE

## Observações
Links de apoio e informações adicionais

**Comment by danielgula** [comment]
Segue relatório do refinamento da tarefa com a equipe. 

**Marca**
Sobre ela, precisamos fazer alguns ajustes visuais para melhor uso nas plataformas pretendidas.

**Soluções**
O Cisec está desenvolvendo diversas soluções que serão acessadas em formato web e mobile. A equipe composta por colegas do NIT + Cisec já possuem protótipos funcionais. Eles precisarão de um site e um ambiente mobile para rodar.
Link para o protótipo: https://www.figma.com/file/AF7SfWrTIvXlmGeEdUE3JG/Simulador?node-id=103%3A740

**Site**
De acordo com refinamento da equipe, a estrutura do Menu do site será a seguinte:

- Home - vai ser a própria logo
-- Institucional
-- Soluções
-- Como Usar
-- Simulador
-- Variantes
-- Derivadas
-- Vacinas
- Perguntas Frequentes
- Contato
- Área do gestor

Sobre os banners 
- Banner central - chamadas para notícias (Sesa, ESP)
- iSUS - publicidade de produtos

Link de acesso ao protótipo: https://www.figma.com/proto/a67eihcskHYp7HttQIg0GM/Dashboard?node-id=211%3A69&scaling=min-zoom&page-id=3%3A2

**Papéis**
Quem vai atualizar as páginas estáticas - usuário no WP do Cisec
Quem vai montar o site - Felicilab
Quem vai integrar as soluções - Cisec + NIT
Quem vai refinar a Assinatura - Felicilab

**Encaminhamentos**
Nesta etapa, solicitamos um stakeholder apresentar o projeto visual para a ASCOM, de maneira que possa criar um manual de identidade para toda a plataforma. Dessa forma iniciaremos a execução da demanda de criação do site.

**Comment by uira** [comment]
@danielgula @danielgula, esse "menu do site" precisa ser refinado em forma de arquitetura .

**Comment by RaniGub** [comment]
@danielgula temos vários modelos de AI em nosso grupo no Figma, você pode consultar algum lá. É importante que seja o primeiro passo antes do desenho das telas e definição de jornada de experiência. Sugiro ainda que a Assinatura Visual no topo do site não seja usada com a Tagline nessa versão vertical. Vou começar agora uns experimentos para que você realize os teste com a horizontal. Ainda assim, acho que somente o uso do símbolo e o descritor textual ao lado direito (como no site da escola) pode ser um caminho melhor.

**Comment by RaniGub** [comment]
[Logo_cisec.pdf](https://github.com/EscolaDeSaudePublica/DesignLab/files/7068756/Logo_cisec.pdf)

**Comment by RaniGub** [comment]
![Captura de Tela 2021-08-27 às 14 59 35](https://user-images.githubusercontent.com/79097920/131169850-eadcae67-4fcb-43ea-8088-309c920bffc9.png)

**Comment by RaniGub** [comment]
—Ajustes—

- Família tipográfica modificada para Cabin (Fonte livre)
- Redução de 18 para 12 fractais
- Tamanho do Símbolo na versão vertical reduzido
- Mudança para caixa-alta na Tagline
- Distância da Tagline para o Logotipo, letra “O” da Tag como referência
- Ajuste óptico da Tagline com o Logotipo
- Definição da distância entre Logotipo e Símbolo (considerar a letra “O”/2 da Tagline)
- Arredondamento dos cantos do Logotipo em 1px
- Kerning do Logotipo em -20px
- Balanço visual (letra ‘C’ para caixa-baixa)
- Versão horizontal adicionada (considerar haste da letra “A” da Tag para distância do símbolo e Logotipo.)
- Considerar “miolo” do cérebro com a mesma altura de X (partindo do cerebelo até o topo) da versão horizontal da assinatura.
- Versão em P&B adicionada
- Fonte primária: Cabin (Google Fonts)

**Comment by RaniGub** [comment]
@matheuscpl refinamento de Assinatura concluído.

**Comment by pauloamoreira** [comment]
.segue sugestões para proposta de Manual de Identidade.

**Orientações para o Manual de Identidade**

**CLIENTE**
•	Centro de Inteligência - CISEC

**PEÇA A SER CRIADA**
•	Manual de Identidade

**PÚBLICO A QUE SE DESTINA**
•	Todas as pessoas que necessitarem aplicar a marca do Centro de Inteligência – CISEC em peças de comunicação visual institucionais ou publicitárias.

**NECESSIDADES BÁSICAS**
O Manual de Identidade deve:
•	Ser conciso, com arquitetura de informação lógica, clara e objetiva, com linguagem simples (caso seja necessário incluir termos técnicos ou jargões, incluir notas de rodapé explicativas);
•	Contemplar esquemas, instruções de aplicação (horizontal e vertical, com ou sem marca associada. Exemplo: Cisec + Governo do Estado), aplicações em cores e preto e branco (positiva e negativa), área de segurança e grids de construção, conforme o caso;
•	Apresentar usos permitidos e usos não permitidos;
•	Contemplar aplicações em impressos (em qualquer suporte e formato), mídias digitais (online e offline), vídeos, brindes / objetos, sinalização (interna e externa), fachadas, mídia exterior, envelopamento de frota de veículos, uniformes, entre outros; com exemplos e instruções acessíveis;
•	Apresentar logo cores contemplando suporte digitais e analógicos, utilizando padrões universais estabelecidos para o tipo de suporte ou mídia mais comuns;
•	Apresentar as famílias tipográficas completas da marca (logotipo, fonte de assinatura, fonte segmentadora ou de slogam, etc);
•	Apresentar, sempre que possível, exemplos de aplicação;
•	Fornecer, quando for o caso, referência guia para assinatura eletrônica animada (Motion Graphics);
•	Fornecer qrcode ou links reduzidos para arquivos digitais com aplicações básicas (em cores - rgb e cmyk, e em preto e branco - positivo e negativo), em containers em formato vetor e imagem.

OBSERVAÇÕES / SUGESTÕES
•	Valorizar na proposta a lógica visual geométrica e as cores estabelecidas na marca.

**Comment by danielgula** [comment]
Atualizando: passei o briefing para Roberta e Marcos. Eles ficaram de conseguir mais algumas informações com Xavier. Prazo de entrega é na sexta.

**Comment by danielgula** [comment]
@drmarcos está acompanhando a Roberta na entrega desse material para repassarmos a Ascom.

**Comment by RaniGub** [comment]
Tarefa Bloqueada. Aguardando direcionamentos para finalização do Briefing.

**Comment by uira** [comment]
@RaniGub Qual o direcionamento necessário?

**Comment by RaniGub** [comment]
> @drmarcos está acompanhando a Roberta na entrega desse material para repassarmos a Ascom.

Oi @uira, dei Quote no direcionamento aguardado.

**Comment by RaniGub** [comment]
Ficou definido que a ASCOM-ESP/CE ficou responsável pela elaboração do Manual.
