### ISSUE TITLE
II Oficina de Construção da Política Estadual de Assistência Farmacêutica

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#98]
## **Objetivo**

**Como** designer  
**Quero** facilitar a aplicação do instrumento da Árvore de Problemas
**Para** contribuir nas definições da PEAF

## **Contexto**

Foi solicitado à ESP-CE, através do Memorando 137/2021, contribuição para aplicação do instrumento 'Árvore de Problemas' na II Oficina de Construção da Política Estadual de Assistência Farmacêutica, que será realizada no dia 31/08/2021 das 09h às 12h, pela plataforma Google Meet, com uso paralelo a ferramenta online Figma  (https://www.figma.com/)

Descrição: a atividade consiste na aplicação do instrumento Árvore de Problemas, para refinar informações do Diagnóstico Situcional da Assistência Farmacêutica, à partir de descritores (acesso a medicamentos, uso racional de medicamentos, estrutura física, processos, resultados, acessibilidade, cuidado) que irão despertar a árvore.

Resultado esperado: Problemas Refinados, com causas e consequências apontadas, para orientar a elaboração das Diretrizes para a Política Estadual de Assistências Farmacêutica.

Beneficiados: cerca de 30 participantes da célula de assistência farmacêutica

Modalidade: à distância (ferramentas: Google Meet e Figma). O link do Google Meet será gerado pela Coordenadoria de Assistência Farmacêutica. O link do Figma será gerado pelo DesignLab.

Facilitadores: Paulo Amoreira (DesignLab), com apoio da equipe da Coordenadoria de Assistência Farmacêutica.

Orientações Técnicas Iniciais - os participantes devem:
- utilizar um notebook com câmera conectado a internet de banda larga
- dispor, preferencialmente, de um fone de ouvido
- fazer anotações prévias sobre os tópicos de interesse para agilizar o processo de trabalho
- dispor de bloco de anotações e caneta no momento da atividade
- acessar a atividade em local que facilite a concentração (acomodações adequadas, ambiente silencioso ou com pouco ruído, evitar interferências externas)

## **Escopo**

- [x] Refinar a demanda
- [x] Estabelecer critérios técnicos mínimos
- [x] Estabelecer dinâmica de trabalho
- [x] Preparar board do Figma para a atividade
- [x] Realizar reunião online de alinhamento
- [x] Aplicar o instrumento na Oficina
- [x] Gerar relatório com sistematização dos resultados
- [x] Aplicar Formulário de Avaliação

## Observações
Responsável: Fernanda França Cabral

Board no Figma da atividade:
https://www.figma.com/file/jzqph6ZEzFISa6lUPzzNHt/II-Oficina-de-Constru%C3%A7%C3%A3o-da-Pol%C3%ADtica-Estadual-de-Assist%C3%AAncia-Farmac%C3%AAutica

**Comment by uira** [comment]
@RaniGub @RaniGub , por favor, encaminha o e-mail de solicitação para o nit@esp, e depois também um email com a sua resposta pra Fernanda, confirmando a participação, com cópia para o mesmo e-mail.

**Comment by RaniGub** [comment]
@pauloamoreira você pode fazer a atualização desse card com os encaminhamentos?

**Comment by pauloamoreira** [comment]
.ok, @RaniGub . vou atualizar o card assim que possível.

**Comment by pauloamoreira** [comment]
.card atualizado.

**Comment by RaniGub** [comment]
@Clarisse1983 isso dá um bom conteúdo para o Cuida.

**Comment by pauloamoreira** [comment]
.imagem de registro de momento da oficina: 
![1ºencontro](https://user-images.githubusercontent.com/79201419/131559827-04b55616-2167-4e87-a018-86c01a4c76a6.jpg)

**Comment by pauloamoreira** [comment]
.foi solicitado que a atividade dessa oficina seja continuada no dia 14/09, de 08 às 12h. para tanto, solicitei a Fernanda França Cabral que houvesse a formalização através de memorando. estamos aguardando a a chegada desse documento para confirmar esse 2º momento.

**Comment by pauloamoreira** [comment]
conforme informado anteriormente, esta atividade terá um novo momento no dia 14/09, das 9h às 12h, gerando o card #115 III Oficina de Construção da Política Estadual de Assistência Farmacêutica. portanto, os itens : "Gerar relatório com sistematização dos resultados" e "Aplicar Formulário de Avaliação" serão apresentados no card #115
