### ISSUE TITLE
Reunião de avaliação sobre Oficina DSP

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#99]
## **Objetivo**

**Como** organizadores  
**Queremos** avaliar pontos da Oficina DSP
**Para** melhorar a experiência dos participantes e otimizar a condução da metodologia aplicada

## **Contexto**

Frente à Oficina de Design de Serviços Públicos realizada, fez-se necessário o mapeamento de alguns pontos para melhorias de ações similares.

## **Escopo**
- [x] Condução dos instrumentos
- [x] Avaliação do espaço
- [x] Organização pré-oficina
- [x] Discussão sobre quantidade de participantes e alocação no espaço
- [x] Relacionamento com os participantes
- [x] Consolidação de feedback dos participantes
- [x] Documento de estruturação de custos, recursos humanos e material de operacionalização da Oficina (Clarissa Peixoto)

## Observações

**Comment by RaniGub** [comment]
@clarissagpeixoto quando eu lhe passar o Feedback dos participantes e você concluir o documento, podemos refinar com o Uirá e encerrar a tarefa. Posso ter esquecido algo, você pode editar o card.

**Comment by clarissagpeixoto** [comment]
@RaniGub OK. trabalhando no arquivo para finalizarmos.

**Comment by clarissagpeixoto** [comment]
@RaniGub , os custos da primeira oficina estão aqui: https://docs.google.com/spreadsheets/d/13_p2hQJ_oNkE0fdMXkohhWxubFhDdiYcQSiqn5Gkil8/edit#gid=1544367084

Melhorias estão sendo construídas na segunda aba.

**Comment by RaniGub** [comment]
Obrigado @clarissagpeixoto, @pauloamoreira sugeri inserir no final após o Glossário. Mas vamos finalizando o conteúdo e depois essa formatação.

**Comment by RaniGub** [comment]
3 pessoas responderam o feedback. A estrutura de custos foi repassada pela Clarissa.
